package defpackage;

import android.content.Context;
import com.google.android.apps.messaging.R;
import java.util.List;

/* compiled from: PG */
/* loaded from: classes2.dex */
final class agtc extends fcyz implements fdat {
    final /* synthetic */ agtd a;
    final /* synthetic */ egbs b;
    final /* synthetic */ String c;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public agtc(agtd agtdVar, egbs egbsVar, String str, fcxy fcxyVar) {
        super(2, fcxyVar);
        this.a = agtdVar;
        this.b = egbsVar;
        this.c = str;
    }

    @Override // defpackage.fdat
    public final /* bridge */ /* synthetic */ Object a(Object obj, Object obj2) {
        return ((agtc) c((fdjx) obj, (fcxy) obj2)).b(fctx.a);
    }

    @Override // defpackage.fcyt
    public final Object b(Object obj) throws Throwable {
        fctl.b(obj);
        agtd agtdVar = this.a;
        aguc agucVar = (aguc) agtdVar.c.b();
        String str = this.b.c;
        str.getClass();
        etrh etrhVar = (etrh) etrk.a.createBuilder();
        etri etriVar = (etri) etrj.a.createBuilder();
        etriVar.copyOnWrite();
        etrj etrjVar = (etrj) etriVar.instance;
        etrjVar.b = 1;
        etrjVar.c = str;
        etrj etrjVar2 = (etrj) etriVar.build();
        etrhVar.copyOnWrite();
        etrk etrkVar = (etrk) etrhVar.instance;
        etrjVar2.getClass();
        etrkVar.c = etrjVar2;
        etrkVar.b |= 1;
        etrd etrdVar = (etrd) etre.a.createBuilder();
        etrl etrlVar = (etrl) etrm.a.createBuilder();
        etrlVar.copyOnWrite();
        etrm etrmVar = (etrm) etrlVar.instance;
        etrmVar.c = 629;
        etrmVar.b |= 1;
        etrdVar.copyOnWrite();
        etre etreVar = (etre) etrdVar.instance;
        etrm etrmVar2 = (etrm) etrlVar.build();
        etrmVar2.getClass();
        etreVar.e = etrmVar2;
        etreVar.b |= 4;
        etrdVar.copyOnWrite();
        etre etreVar2 = (etre) etrdVar.instance;
        etrk etrkVar2 = (etrk) etrhVar.build();
        etrkVar2.getClass();
        etreVar2.c = etrkVar2;
        etreVar2.b |= 1;
        etrdVar.copyOnWrite();
        etre etreVar3 = (etre) etrdVar.instance;
        etrk etrkVar3 = (etrk) etrhVar.build();
        etrkVar3.getClass();
        etreVar3.d = etrkVar3;
        etreVar3.b |= 2;
        etrx etrxVar = (etrx) etry.a.createBuilder();
        etib etibVar = etib.iH;
        etrxVar.copyOnWrite();
        etry etryVar = (etry) etrxVar.instance;
        etryVar.c = etibVar.a();
        etryVar.b |= 1;
        etrv etrvVar = (etrv) etrw.a.createBuilder();
        etrp etrpVar = (etrp) etrq.a.createBuilder();
        etru etruVar = etru.a;
        etrt etrtVar = (etrt) etruVar.createBuilder();
        etrtVar.copyOnWrite();
        etru etruVar2 = (etru) etrtVar.instance;
        etruVar2.b |= 1;
        etruVar2.c = R.string.gemini_eea_tos_title;
        etro etroVar = etro.a;
        etrn etrnVar = (etrn) etroVar.createBuilder();
        etrnVar.copyOnWrite();
        etro etroVar2 = (etro) etrnVar.instance;
        etroVar2.b |= 1;
        etroVar2.c = "%1$s";
        int iA = agucVar.c.a();
        etrnVar.copyOnWrite();
        etro etroVar3 = (etro) etrnVar.instance;
        etroVar3.b |= 4;
        etroVar3.e = iA;
        etrtVar.copyOnWrite();
        etru etruVar3 = (etru) etrtVar.instance;
        etro etroVar4 = (etro) etrnVar.build();
        etroVar4.getClass();
        etruVar3.a();
        etruVar3.d.add(etroVar4);
        etrpVar.copyOnWrite();
        etrq etrqVar = (etrq) etrpVar.instance;
        etru etruVar4 = (etru) etrtVar.build();
        etruVar4.getClass();
        etrqVar.c = etruVar4;
        etrqVar.b |= 1;
        etrs etrsVar = etrs.a;
        etrr etrrVar = (etrr) etrsVar.createBuilder();
        etrt etrtVar2 = (etrt) etruVar.createBuilder();
        etrtVar2.copyOnWrite();
        etru etruVar5 = (etru) etrtVar2.instance;
        etruVar5.b |= 1;
        etruVar5.c = R.string.gemini_tos_preamble;
        etrrVar.copyOnWrite();
        etrs etrsVar2 = (etrs) etrrVar.instance;
        etru etruVar6 = (etru) etrtVar2.build();
        etruVar6.getClass();
        etrsVar2.c = etruVar6;
        etrsVar2.b |= 1;
        etrr etrrVar2 = (etrr) etrsVar.createBuilder();
        etrt etrtVar3 = (etrt) etruVar.createBuilder();
        etrtVar3.copyOnWrite();
        etru etruVar7 = (etru) etrtVar3.instance;
        etruVar7.b |= 1;
        etruVar7.c = R.string.gemini_tos_header1;
        etrrVar2.copyOnWrite();
        etrs etrsVar3 = (etrs) etrrVar2.instance;
        etru etruVar8 = (etru) etrtVar3.build();
        etruVar8.getClass();
        etrsVar3.c = etruVar8;
        etrsVar3.b |= 1;
        etrt etrtVar4 = (etrt) etruVar.createBuilder();
        etrtVar4.copyOnWrite();
        etru etruVar9 = (etru) etrtVar4.instance;
        etruVar9.b |= 1;
        etruVar9.c = R.string.gemini_tos_body1_extend;
        etrn etrnVar2 = (etrn) etroVar.createBuilder();
        etrnVar2.copyOnWrite();
        etro etroVar5 = (etro) etrnVar2.instance;
        etroVar5.b |= 1;
        etroVar5.c = "%1$s";
        etrnVar2.copyOnWrite();
        etro etroVar6 = (etro) etrnVar2.instance;
        etroVar6.b |= 4;
        etroVar6.e = R.string.gemini_eea_activity_link_text;
        Context context = agucVar.b;
        String string = context.getString(R.string.penpal_activity_link);
        etrnVar2.copyOnWrite();
        etro etroVar7 = (etro) etrnVar2.instance;
        string.getClass();
        etroVar7.b |= 8;
        etroVar7.f = string;
        etrn etrnVar3 = (etrn) etroVar.createBuilder();
        etrnVar3.copyOnWrite();
        etro etroVar8 = (etro) etrnVar3.instance;
        etroVar8.b |= 1;
        etroVar8.c = "%2$s";
        etrnVar3.copyOnWrite();
        etro etroVar9 = (etro) etrnVar3.instance;
        etroVar9.b |= 4;
        etroVar9.e = R.string.gemini_tos_how_it_works;
        String string2 = context.getString(R.string.penpal_privacy_help_hub_link);
        etrnVar3.copyOnWrite();
        etro etroVar10 = (etro) etrnVar3.instance;
        string2.getClass();
        etroVar10.b |= 8;
        etroVar10.f = string2;
        etrn etrnVar4 = (etrn) etroVar.createBuilder();
        etrnVar4.copyOnWrite();
        etro etroVar11 = (etro) etrnVar4.instance;
        etroVar11.b |= 1;
        etroVar11.c = "{3}";
        etrnVar4.copyOnWrite();
        etro etroVar12 = (etro) etrnVar4.instance;
        etroVar12.b |= 2;
        etroVar12.d = "3";
        etrn etrnVar5 = (etrn) etroVar.createBuilder();
        etrnVar5.copyOnWrite();
        etro etroVar13 = (etro) etrnVar5.instance;
        etroVar13.b |= 1;
        etroVar13.c = "{72}";
        etrnVar5.copyOnWrite();
        etro etroVar14 = (etro) etrnVar5.instance;
        etroVar14.b |= 2;
        etroVar14.d = "72";
        etrtVar4.a(fcva.g((etro) etrnVar2.build(), (etro) etrnVar3.build(), (etro) etrnVar4.build(), (etro) etrnVar5.build()));
        etrrVar2.copyOnWrite();
        etrs etrsVar4 = (etrs) etrrVar2.instance;
        etru etruVar10 = (etru) etrtVar4.build();
        etruVar10.getClass();
        etrsVar4.e = etruVar10;
        etrsVar4.b |= 4;
        etrr etrrVar3 = (etrr) etrsVar.createBuilder();
        etrt etrtVar5 = (etrt) etruVar.createBuilder();
        etrtVar5.copyOnWrite();
        etru etruVar11 = (etru) etrtVar5.instance;
        etruVar11.b |= 1;
        etruVar11.c = R.string.gemini_tos_footnote;
        etrn etrnVar6 = (etrn) etroVar.createBuilder();
        etrnVar6.copyOnWrite();
        etro etroVar15 = (etro) etrnVar6.instance;
        etroVar15.b |= 1;
        etroVar15.c = "%1$s";
        etrnVar6.copyOnWrite();
        etro etroVar16 = (etro) etrnVar6.instance;
        etroVar16.b |= 4;
        etroVar16.e = R.string.penpal_eea_tos_confirm_button;
        etrn etrnVar7 = (etrn) etroVar.createBuilder();
        etrnVar7.copyOnWrite();
        etro etroVar17 = (etro) etrnVar7.instance;
        etroVar17.b |= 1;
        etroVar17.c = "%2$s";
        etrnVar7.copyOnWrite();
        etro etroVar18 = (etro) etrnVar7.instance;
        etroVar18.b |= 4;
        etroVar18.e = R.string.penpal_tos_link_text;
        String string3 = context.getString(R.string.penpal_tos_link);
        etrnVar7.copyOnWrite();
        etro etroVar19 = (etro) etrnVar7.instance;
        string3.getClass();
        etroVar19.b |= 8;
        etroVar19.f = string3;
        etrn etrnVar8 = (etrn) etroVar.createBuilder();
        etrnVar8.copyOnWrite();
        etro etroVar20 = (etro) etrnVar8.instance;
        etroVar20.b |= 1;
        etroVar20.c = "%3$s";
        etrnVar8.copyOnWrite();
        etro etroVar21 = (etro) etrnVar8.instance;
        etroVar21.b |= 4;
        etroVar21.e = R.string.penpal_ai_terms_link_text;
        String string4 = context.getString(R.string.penpal_ai_terms_link);
        etrnVar8.copyOnWrite();
        etro etroVar22 = (etro) etrnVar8.instance;
        string4.getClass();
        etroVar22.b |= 8;
        etroVar22.f = string4;
        etrn etrnVar9 = (etrn) etroVar.createBuilder();
        etrnVar9.copyOnWrite();
        etro etroVar23 = (etro) etrnVar9.instance;
        etroVar23.b |= 1;
        etroVar23.c = "%4$s";
        etrnVar9.copyOnWrite();
        etro etroVar24 = (etro) etrnVar9.instance;
        etroVar24.b |= 4;
        etroVar24.e = R.string.penpal_privacy_notice_link_text;
        String string5 = context.getString(R.string.penpal_privacy_notice_link);
        etrnVar9.copyOnWrite();
        etro etroVar25 = (etro) etrnVar9.instance;
        string5.getClass();
        etroVar25.b |= 8;
        etroVar25.f = string5;
        etrtVar5.a(fcva.g((etro) etrnVar6.build(), (etro) etrnVar7.build(), (etro) etrnVar8.build(), (etro) etrnVar9.build()));
        etrrVar3.copyOnWrite();
        etrs etrsVar5 = (etrs) etrrVar3.instance;
        etru etruVar12 = (etru) etrtVar5.build();
        etruVar12.getClass();
        etrsVar5.d = etruVar12;
        etrsVar5.b |= 2;
        List listG = fcva.g((etrs) etrrVar.build(), (etrs) etrrVar2.build(), (etrs) etrrVar3.build());
        etrpVar.copyOnWrite();
        etrq etrqVar2 = (etrq) etrpVar.instance;
        evtg evtgVar = etrqVar2.d;
        if (!evtgVar.c()) {
            etrqVar2.d = evsn.mutableCopy(evtgVar);
        }
        String str2 = this.c;
        evpz.addAll(listG, etrqVar2.d);
        etrpVar.copyOnWrite();
        etrq etrqVar3 = (etrq) etrpVar.instance;
        etrqVar3.b |= 2;
        etrqVar3.e = R.string.penpal_eea_tos_confirm_button;
        etrpVar.copyOnWrite();
        etrq etrqVar4 = (etrq) etrpVar.instance;
        etrqVar4.b |= 4;
        etrqVar4.f = R.string.penpal_tos_deny;
        etrq etrqVar5 = (etrq) etrpVar.build();
        etrvVar.copyOnWrite();
        etrw etrwVar = (etrw) etrvVar.instance;
        etrqVar5.getClass();
        etrwVar.c = etrqVar5;
        etrwVar.b |= Integer.MIN_VALUE;
        etrxVar.copyOnWrite();
        etry etryVar2 = (etry) etrxVar.instance;
        etrw etrwVar2 = (etrw) etrvVar.build();
        etrwVar2.getClass();
        etryVar2.d = etrwVar2;
        etryVar2.b |= 8;
        etrdVar.copyOnWrite();
        etre etreVar4 = (etre) etrdVar.instance;
        etry etryVar3 = (etry) etrxVar.build();
        etryVar3.getClass();
        etreVar4.f = etryVar3;
        etreVar4.b |= 8;
        evsn evsnVarBuild = etrdVar.build();
        evsnVarBuild.getClass();
        ekrw ekrwVarH = aguc.a.h();
        ekrwVarH.X(eksq.a, "Bugle");
        ((ekrd) ekrwVarH.h("com/google/android/apps/messaging/penpal/consent/PenpalTosAriRequestScheduler", "grantGeminiNonEeaTos", 152, "PenpalTosAriRequestScheduler.kt")).q("queue penpal non-eea tos ari request.");
        aolt aoltVar = (aolt) agucVar.d.b();
        aolu aoluVar = (aolu) aolv.a.createBuilder();
        aoluVar.copyOnWrite();
        aolv aolvVar = (aolv) aoluVar.instance;
        aolvVar.b |= 1;
        aolvVar.c = str2;
        aoluVar.copyOnWrite();
        aolv aolvVar2 = (aolv) aoluVar.instance;
        aolvVar2.d = (etre) evsnVarBuild;
        aolvVar2.b |= 2;
        ((cazj) aoltVar.a.b()).a(cbcu.f("ari_work_handler", (aolv) aoluVar.build()));
        cgte cgteVar = agtdVar.d;
        Object objB = agtdVar.f.b();
        objB.getClass();
        cgteVar.o((efwo) objB);
        if (((Boolean) ((cczi) crbf.bt.get()).e()).booleanValue()) {
            auvw.k(agtdVar.l, null, null, new agta(agtdVar, null), 3);
        }
        return fctx.a;
    }

    @Override // defpackage.fcyt
    public final fcxy c(Object obj, fcxy fcxyVar) {
        return new agtc(this.a, this.b, this.c, fcxyVar);
    }
}
