package defpackage;

import androidx.car.app.hardware.common.CarZone;
import androidx.car.app.hardware.info.EnergyProfile;
import androidx.car.app.navigation.model.Maneuver;
import com.android.vcard.VCardConstants;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;
import com.sun.jna.Function;

/* compiled from: PG */
/* loaded from: classes3.dex */
class aili extends ejvj {
    @Override // defpackage.ejvj
    protected final /* bridge */ /* synthetic */ Object a(Object obj) {
        emxt emxtVar = (emxt) obj;
        switch (emxtVar.ordinal()) {
            case 15:
                return ellf.BUGLE_APP;
            case 16:
                return ellf.BUGLE_MESSAGE;
            case 17:
                return ellf.BUGLE_CONTACTS_EVENT;
            case 18:
                return ellf.BUGLE_SUPER_SORT_EVENT;
            case 19:
                return ellf.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 20:
                return ellf.REACTIONS_PROMO_EVENT;
            case 21:
                return ellf.BUGLE_SMART_COMPOSE;
            case 22:
                return ellf.EXTERNAL_API_SERVICE_CALL_START;
            case 23:
                return ellf.EXTERNAL_API_SERVICE_CALL_END;
            case 24:
                return ellf.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 25:
                return ellf.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 26:
                return ellf.BUGLE_CONVERSATION;
            case 27:
                return ellf.BUGLE_PERFORMANCE;
            case 28:
                return ellf.BUGLE_SEARCH;
            case 29:
                return ellf.BUGLE_SETTING;
            case 30:
                return ellf.BUGLE_USER_AND_DEVICE_INFO;
            case 31:
                return ellf.BUGLE_TRANSCODING;
            case 32:
                return ellf.BUGLE_RCS_PROVISIONING;
            case 33:
                return ellf.BUGLE_P2P_SUGGESTION;
            case 34:
                return ellf.BUGLE_APP_CONFIGURATION;
            case 35:
                return ellf.BUGLE_RBM_BUSINESS_INFO;
            case 36:
                return ellf.BUGLE_ANNOTATION;
            case 37:
                return ellf.DITTO_GRPC_MESSAGE;
            case 38:
                return ellf.BUGLE_TELEPHONY_EVENT;
            case Maneuver.TYPE_DESTINATION /* 39 */:
                return ellf.BUGLE_GIF_CHOOSER;
            case 40:
                return ellf.BUGLE_GROUP;
            case 41:
                return ellf.BUGLE_ADD_CONTACT;
            case 42:
                return ellf.DITTO_IMAGE;
            case 43:
                return ellf.BUGLE_CONTACT_BANNER;
            case 44:
                return ellf.BUGLE_REPORT_SPAM;
            case 45:
                return ellf.BUGLE_COMPOSE;
            case 46:
                return ellf.BUGLE_FILE_PREVIEW_CLICK;
            case 47:
                return ellf.BUGLE_INDEXING;
            case 48:
                return ellf.BUGLE_PARTICIPANTS_TABLE;
            case Maneuver.TYPE_FERRY_TRAIN_LEFT /* 49 */:
                return ellf.BUGLE_SPAM_DETECTION;
            case 50:
                return ellf.BUGLE_EDIT_CONTACT;
            case 51:
                return ellf.BUGLE_BLOCK_FILE_ATTACH;
            case 52:
                return ellf.BUGLE_ASSISTANT;
            case 53:
                return ellf.BUGLE_CONSENT;
            case 54:
                return ellf.BUGLE_ICING_SEARCH;
            case 55:
                return ellf.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case 56:
                return ellf.BUGLE_FEDERATED_LEARNING;
            case 57:
                return ellf.BUGLE_MDD_LIB;
            case 58:
                return ellf.BUGLE_VERIFIED_SMS;
            case 59:
                return ellf.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case 60:
                return ellf.BUGLE_SHAKE_TO_REPORT;
            case 61:
                return ellf.BUGLE_SCYTALE_EVENT;
            case 62:
                return ellf.BUGLE_SELECTED_MESSAGES_ACTION;
            case Function.ALT_CONVENTION /* 63 */:
                return ellf.BUGLE_REMINDER;
            case 64:
                return ellf.DITTO_SESSION_INFO;
            case 65:
                return ellf.DITTO_QR_CODE_PAIRING_EVENT;
            case 66:
                return ellf.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 67:
                return ellf.BUGLE_E2EE_STATE_TRANSITION;
            case 68:
                return ellf.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 69:
                return ellf.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 70:
                return ellf.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 71:
                return ellf.BUGLE_CONTACT_PICKER;
            case 72:
                return ellf.BUGLE_MEDIA_VIEWER;
            case 73:
                return ellf.BUGLE_VIDEO_CALL_EVENT;
            case 74:
                return ellf.BUGLE_NOTIFICATION;
            case 75:
                return ellf.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 76:
                return ellf.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 77:
                return ellf.BUGLE_WELCOME_EVENT;
            case 78:
                return ellf.DITTO_BINDING_STATUS;
            case 79:
                return ellf.ICING_INDEX_UPDATE_EVENT;
            case CarZone.CAR_ZONE_COLUMN_DRIVER /* 80 */:
                return ellf.TELEPHONY_DATABASE_EVENT;
            case 81:
                return ellf.TELEPHONY_DATABASE_ACTION_EVENT;
            case 82:
                return ellf.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 83:
                return ellf.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 84:
                return ellf.BUGLE_REPORT_ISSUE_EVENT;
            case 85:
                return ellf.SPAM_FOLDER_EVENT;
            case 86:
                return ellf.AVAILABILITY_LOG;
            case 87:
                return ellf.SEARCH_QUERY;
            case 88:
                return ellf.HOME_SCREEN;
            case 89:
                return ellf.BUGLE_MULTI_DEVICE_EVENT;
            case 90:
                return ellf.ICING_INDEX_REBUILD;
            case 91:
                return ellf.RCS_EVENT;
            case 92:
                return ellf.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 93:
                return ellf.MMS_METADATA_EXPERIMENT;
            case 94:
                return ellf.HADES_SDK_EVENT;
            case 95:
                return ellf.CUSTODIAN_REPORT;
            case CarZone.CAR_ZONE_COLUMN_PASSENGER /* 96 */:
                return ellf.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 97:
                return ellf.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 98:
                return ellf.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 99:
                return ellf.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return ellf.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case EnergyProfile.EVCONNECTOR_TYPE_OTHER /* 101 */:
                return ellf.DATA_DONATION_EVENT;
            case 102:
                return ellf.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 103:
                return ellf.SCHEDULED_SEND_EVENT;
            case 104:
                return ellf.JIBE_SERVICE_CONNECTION;
            case 105:
                return ellf.DATABASE_UPGRADE;
            case 106:
                return ellf.FORWARD_TELEPHONY_SYNC;
            case 107:
                return ellf.RBM_EVENT;
            case 108:
                return ellf.TOGGLE_CHAT_FEATURES_EVENT;
            case 109:
                return ellf.SYNC_TELEPHONY_THREADS;
            case 110:
                return ellf.FUZZY_MATCH_LENGTH;
            case 111:
                return ellf.BUGLE_TABLET_MODE_SWITCH;
            case 112:
                return ellf.RCS_PROVISIONING;
            case 113:
                return ellf.BUGLE_CONVERSATION_MATCHING;
            case 114:
                return ellf.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 115:
                return ellf.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 116:
                return ellf.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 117:
                return ellf.WEAR_FAILURE_EVENT;
            case 118:
                return ellf.BUGLE_STAR_EVENT;
            case 119:
                return ellf.BUBBLE_SETTING_EVENT;
            case 120:
                return ellf.XSL_REQUEST_EVENT;
            case 121:
                return ellf.PIN_TO_TOP_EVENT;
            case 122:
                return ellf.TACHYGRAM_EVENT;
            case 123:
                return ellf.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 124:
                return ellf.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 125:
                return ellf.BUGLE_MESSAGE_CLASSIFICATION;
            case 126:
                return ellf.BANNER_EVENT;
            case 127:
                return ellf.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 128:
                return ellf.RCS_CHAT_SESSION_SERVICE;
            case 129:
                return ellf.SPAM_ABUSE_EVENT;
            case 130:
                return ellf.BUGLE_CONVERSATION_CLASSIFICATION;
            case 131:
                return ellf.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 132:
                return ellf.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 133:
                return ellf.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 134:
                return ellf.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 135:
                return ellf.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 136:
                return ellf.RCS_CONTACTS_CALLER_EVENT;
            case 137:
                return ellf.NOTIFICATION_METRICS_EVENT;
            case 138:
                return ellf.BUGLE_GAIA_INTEGRATION_EVENT;
            case 139:
                return ellf.WEAR_USER_AND_DEVICE_INFO;
            case 140:
                return ellf.LIGHTER_EVENT;
            case 141:
                return ellf.BUGLE_YOUTUBE_EVENT;
            case 142:
                return ellf.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 143:
                return ellf.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 144:
                return ellf.WELCOME_FLOW_UI_EVENT;
            case 145:
                return ellf.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 146:
                return ellf.BUGLE_CAPABILITIES_EVENT;
            case 147:
                return ellf.WELCOME_FLOW_PAGE_EVENT;
            case 148:
                return ellf.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 149:
                return ellf.WELCOME_FLOW_LAUNCH_EVENT;
            case 150:
                return ellf.VMT_SESSION_EVENT;
            case 151:
                return ellf.BUGLE_SMS_CAPABILITY_EVENT;
            case 152:
                return ellf.BUGLE_APP_CONTROL_EVENT;
            case 153:
                return ellf.CONVERSATION_E2EE_STATUS_UPDATE;
            case 154:
                return ellf.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 155:
                return ellf.PROFILE_EVENT;
            case 156:
                return ellf.IN_APP_UPDATE_EVENT;
            case 157:
                return ellf.HOME_SCREEN_METRICS_EVENT;
            case 158:
                return ellf.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 159:
                return ellf.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 160:
                return ellf.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 161:
                return ellf.CONVERSATION_SCREEN_METRIC_EVENT;
            case 162:
                return ellf.DATABASE_OPERATION;
            case 163:
                return ellf.THREAD_UTILIZATION;
            case 164:
                return ellf.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 165:
                return ellf.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 166:
                return ellf.MODIFIED_BY_EVENT;
            case 167:
                return ellf.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 168:
                return ellf.MAGIC_COMPOSE_FEEDBACK;
            case 169:
                return ellf.MAGIC_COMPOSE_CONSENT;
            case 170:
                return ellf.SIM_STATE_TRACKER_EVENT;
            case 171:
                return ellf.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 172:
                return ellf.BUGLE_SYSTEM_BACKUP_EVENT;
            case 173:
                return ellf.MAGIC_COMPOSE_ERROR;
            case 174:
                return ellf.MAGIC_COMPOSE_EVENT;
            case 175:
                return ellf.MAGIC_COMPOSE_DISPLAY;
            case 176:
                return ellf.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 177:
                return ellf.HOME_SCREEN_FIRST_VISIT;
            case 178:
                return ellf.DANGLING_PARTS_EVENT;
            case 179:
                return ellf.MAGIC_COMPOSE_ICON_EVENT;
            case 180:
                return ellf.MAGIC_COMPOSE_SETTING;
            case 181:
                return ellf.SMS_SUBJECT_REPORT_EVENT;
            case 182:
                return ellf.MULTI_SHARE_EVENT;
            case 183:
                return ellf.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 184:
                return ellf.TOGGLE_RCS_CHATS_EVENT;
            case 185:
                return ellf.EMOTIFY_CREATE_EVENT;
            case 186:
                return ellf.EMOTIFY_IMPRESSION_EVENT;
            case 187:
                return ellf.EMOTIFY_MESSAGE_SEND_EVENT;
            case 188:
                return ellf.EMOTIFY_DELETE_EVENT;
            case 189:
                return ellf.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 190:
                return ellf.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 191:
                return ellf.MEET_CALLING_EVENT;
            case 192:
                return ellf.RCS_PROVISIONING_MANAGER_EVENT;
            case 193:
                return ellf.VOICE_MOOD_EVENT;
            case 194:
                return ellf.BARD_EVENT;
            case 195:
                return ellf.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 196:
                return ellf.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 197:
                return ellf.REVOKE_CONSENT_EVENT;
            case 198:
                return ellf.RCS_LOCAL_IDENTITY_EVENT;
            case 199:
                return ellf.D2D_BACKUP_AND_RESTORE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return ellf.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return ellf.GAIA_SIGN_IN_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return ellf.SELFIE_GIF_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return ellf.GAIA_SIGN_IN_STATE;
            case 204:
                return ellf.SATELLITE_EVENT;
            case 205:
                return ellf.MMS_GROUP_UPGRADE_EVENT;
            case 206:
                return ellf.RESTORE_WORKFLOW_EVENT;
            case 207:
                return ellf.BACKUP_WORKFLOW_EVENT;
            case 208:
                return ellf.VIDEO_CALLING_EVENT;
            case 209:
                return ellf.TELEPHONY_PERSISTENCE_EVENT;
            case 210:
                return ellf.MMS_GROUP_EVENT;
            case 211:
                return ellf.OPEN_PENPAL_CHAT_EVENT;
            case 212:
                return ellf.BUGLE_COMPOSE_DISABLED_EVENT;
            case 213:
                return ellf.GAIA_REPORT_EVENT;
            case 214:
                return ellf.MMS_MERGING_EVENT;
            case 215:
                return ellf.BUGLE_FILE_PROCESSING;
            case 216:
                return ellf.CONVERSATION_SCREEN_FIRST_VISIT;
            case 217:
                return ellf.TYCHO_GRPC_EVENT;
            case 218:
                return ellf.SCREEN_EFFECTS_EVENT;
            case 219:
                return ellf.TOOLSTONE_EVENT;
            case 220:
                return ellf.RCS_AVAILABILITY_ON_FIRST_APP_OPEN;
            case 221:
                return ellf.BUGLE_WELCOME_V1_EVENT;
            case 222:
                return ellf.BUGLE_MLS_EVENT;
            case 223:
                return ellf.RCS_REFLECTION_EVENT;
            case 224:
                return ellf.OUT_OF_ORDER_RCS_MESSAGE_DELIVERY;
            case 225:
                return ellf.MISSING_RCS_MESSAGE_EVENT;
            default:
                throw new IllegalArgumentException("unknown enum value: ".concat(emxtVar.toString()));
        }
    }

    @Override // defpackage.ejvj
    protected final /* bridge */ /* synthetic */ Object b(Object obj) {
        switch (((ellf) obj).ordinal()) {
            case 1:
                return emxt.BUGLE_APP;
            case 2:
                return emxt.BUGLE_MESSAGE;
            case 3:
                return emxt.BUGLE_CONVERSATION;
            case 4:
                return emxt.BUGLE_PERFORMANCE;
            case 5:
                return emxt.BUGLE_SEARCH;
            case 6:
                return emxt.BUGLE_SETTING;
            case 7:
            case 10:
            case 14:
            case 27:
            case 30:
            case 31:
            case 72:
            case 86:
            case 87:
            case 98:
            default:
                return c();
            case 8:
                return emxt.BUGLE_USER_AND_DEVICE_INFO;
            case 9:
                return emxt.BUGLE_TRANSCODING;
            case 11:
                return emxt.BUGLE_RCS_PROVISIONING;
            case 12:
                return emxt.BUGLE_P2P_SUGGESTION;
            case 13:
                return emxt.BUGLE_APP_CONFIGURATION;
            case 15:
                return emxt.BUGLE_RBM_BUSINESS_INFO;
            case 16:
                return emxt.BUGLE_ANNOTATION;
            case 17:
                return emxt.DITTO_GRPC_MESSAGE;
            case 18:
                return emxt.BUGLE_TELEPHONY_EVENT;
            case 19:
                return emxt.BUGLE_GIF_CHOOSER;
            case 20:
                return emxt.BUGLE_GROUP;
            case 21:
                return emxt.BUGLE_ADD_CONTACT;
            case 22:
                return emxt.DITTO_IMAGE;
            case 23:
                return emxt.BUGLE_CONTACT_BANNER;
            case 24:
                return emxt.BUGLE_REPORT_SPAM;
            case 25:
                return emxt.BUGLE_COMPOSE;
            case 26:
                return emxt.BUGLE_FILE_PREVIEW_CLICK;
            case 28:
                return emxt.BUGLE_INDEXING;
            case 29:
                return emxt.BUGLE_PARTICIPANTS_TABLE;
            case 32:
                return emxt.BUGLE_SPAM_DETECTION;
            case 33:
                return emxt.BUGLE_EDIT_CONTACT;
            case 34:
                return emxt.BUGLE_BLOCK_FILE_ATTACH;
            case 35:
                return emxt.BUGLE_ASSISTANT;
            case 36:
                return emxt.BUGLE_CONSENT;
            case 37:
                return emxt.BUGLE_ICING_SEARCH;
            case 38:
                return emxt.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case Maneuver.TYPE_DESTINATION /* 39 */:
                return emxt.BUGLE_FEDERATED_LEARNING;
            case 40:
                return emxt.BUGLE_MDD_LIB;
            case 41:
                return emxt.BUGLE_VERIFIED_SMS;
            case 42:
                return emxt.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case 43:
                return emxt.BUGLE_SHAKE_TO_REPORT;
            case 44:
                return emxt.BUGLE_SCYTALE_EVENT;
            case 45:
                return emxt.BUGLE_SELECTED_MESSAGES_ACTION;
            case 46:
                return emxt.BUGLE_REMINDER;
            case 47:
                return emxt.DITTO_SESSION_INFO;
            case 48:
                return emxt.DITTO_QR_CODE_PAIRING_EVENT;
            case Maneuver.TYPE_FERRY_TRAIN_LEFT /* 49 */:
                return emxt.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 50:
                return emxt.BUGLE_E2EE_STATE_TRANSITION;
            case 51:
                return emxt.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 52:
                return emxt.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 53:
                return emxt.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 54:
                return emxt.BUGLE_CONTACT_PICKER;
            case 55:
                return emxt.BUGLE_MEDIA_VIEWER;
            case 56:
                return emxt.BUGLE_VIDEO_CALL_EVENT;
            case 57:
                return emxt.BUGLE_NOTIFICATION;
            case 58:
                return emxt.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 59:
                return emxt.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 60:
                return emxt.BUGLE_WELCOME_EVENT;
            case 61:
                return emxt.DITTO_BINDING_STATUS;
            case 62:
                return emxt.ICING_INDEX_UPDATE_EVENT;
            case Function.ALT_CONVENTION /* 63 */:
                return emxt.TELEPHONY_DATABASE_EVENT;
            case 64:
                return emxt.TELEPHONY_DATABASE_ACTION_EVENT;
            case 65:
                return emxt.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 66:
                return emxt.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 67:
                return emxt.BUGLE_REPORT_ISSUE_EVENT;
            case 68:
                return emxt.SPAM_FOLDER_EVENT;
            case 69:
                return emxt.AVAILABILITY_LOG;
            case 70:
                return emxt.SEARCH_QUERY;
            case 71:
                return emxt.HOME_SCREEN;
            case 73:
                return emxt.BUGLE_MULTI_DEVICE_EVENT;
            case 74:
                return emxt.ICING_INDEX_REBUILD;
            case 75:
                return emxt.RCS_EVENT;
            case 76:
                return emxt.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 77:
                return emxt.MMS_METADATA_EXPERIMENT;
            case 78:
                return emxt.HADES_SDK_EVENT;
            case 79:
                return emxt.CUSTODIAN_REPORT;
            case CarZone.CAR_ZONE_COLUMN_DRIVER /* 80 */:
                return emxt.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 81:
                return emxt.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 82:
                return emxt.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 83:
                return emxt.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case 84:
                return emxt.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case 85:
                return emxt.DATA_DONATION_EVENT;
            case 88:
                return emxt.BUGLE_CONTACTS_EVENT;
            case 89:
                return emxt.BUGLE_SUPER_SORT_EVENT;
            case 90:
                return emxt.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 91:
                return emxt.REACTIONS_PROMO_EVENT;
            case 92:
                return emxt.BUGLE_SMART_COMPOSE;
            case 93:
                return emxt.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 94:
                return emxt.EXTERNAL_API_SERVICE_CALL_START;
            case 95:
                return emxt.EXTERNAL_API_SERVICE_CALL_END;
            case CarZone.CAR_ZONE_COLUMN_PASSENGER /* 96 */:
                return emxt.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 97:
                return emxt.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 99:
                return emxt.SCHEDULED_SEND_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return emxt.JIBE_SERVICE_CONNECTION;
            case EnergyProfile.EVCONNECTOR_TYPE_OTHER /* 101 */:
                return emxt.DATABASE_UPGRADE;
            case 102:
                return emxt.FORWARD_TELEPHONY_SYNC;
            case 103:
                return emxt.RBM_EVENT;
            case 104:
                return emxt.TOGGLE_CHAT_FEATURES_EVENT;
            case 105:
                return emxt.SYNC_TELEPHONY_THREADS;
            case 106:
                return emxt.FUZZY_MATCH_LENGTH;
            case 107:
                return emxt.BUGLE_TABLET_MODE_SWITCH;
            case 108:
                return emxt.RCS_PROVISIONING;
            case 109:
                return emxt.BUGLE_CONVERSATION_MATCHING;
            case 110:
                return emxt.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 111:
                return emxt.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 112:
                return emxt.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 113:
                return emxt.WEAR_FAILURE_EVENT;
            case 114:
                return emxt.BUGLE_STAR_EVENT;
            case 115:
                return emxt.BUBBLE_SETTING_EVENT;
            case 116:
                return emxt.XSL_REQUEST_EVENT;
            case 117:
                return emxt.PIN_TO_TOP_EVENT;
            case 118:
                return emxt.TACHYGRAM_EVENT;
            case 119:
                return emxt.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 120:
                return emxt.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 121:
                return emxt.BUGLE_MESSAGE_CLASSIFICATION;
            case 122:
                return emxt.BANNER_EVENT;
            case 123:
                return emxt.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 124:
                return emxt.RCS_CHAT_SESSION_SERVICE;
            case 125:
                return emxt.SPAM_ABUSE_EVENT;
            case 126:
                return emxt.BUGLE_CONVERSATION_CLASSIFICATION;
            case 127:
                return emxt.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 128:
                return emxt.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 129:
                return emxt.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 130:
                return emxt.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 131:
                return emxt.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 132:
                return emxt.RCS_CONTACTS_CALLER_EVENT;
            case 133:
                return emxt.NOTIFICATION_METRICS_EVENT;
            case 134:
                return emxt.BUGLE_GAIA_INTEGRATION_EVENT;
            case 135:
                return emxt.WEAR_USER_AND_DEVICE_INFO;
            case 136:
                return emxt.LIGHTER_EVENT;
            case 137:
                return emxt.BUGLE_YOUTUBE_EVENT;
            case 138:
                return emxt.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 139:
                return emxt.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 140:
                return emxt.WELCOME_FLOW_UI_EVENT;
            case 141:
                return emxt.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 142:
                return emxt.BUGLE_CAPABILITIES_EVENT;
            case 143:
                return emxt.WELCOME_FLOW_PAGE_EVENT;
            case 144:
                return emxt.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 145:
                return emxt.WELCOME_FLOW_LAUNCH_EVENT;
            case 146:
                return emxt.VMT_SESSION_EVENT;
            case 147:
                return emxt.BUGLE_SMS_CAPABILITY_EVENT;
            case 148:
                return emxt.BUGLE_APP_CONTROL_EVENT;
            case 149:
                return emxt.CONVERSATION_E2EE_STATUS_UPDATE;
            case 150:
                return emxt.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 151:
                return emxt.PROFILE_EVENT;
            case 152:
                return emxt.IN_APP_UPDATE_EVENT;
            case 153:
                return emxt.HOME_SCREEN_METRICS_EVENT;
            case 154:
                return emxt.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 155:
                return emxt.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 156:
                return emxt.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 157:
                return emxt.CONVERSATION_SCREEN_METRIC_EVENT;
            case 158:
                return emxt.DATABASE_OPERATION;
            case 159:
                return emxt.THREAD_UTILIZATION;
            case 160:
                return emxt.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 161:
                return emxt.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 162:
                return emxt.MODIFIED_BY_EVENT;
            case 163:
                return emxt.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 164:
                return emxt.MAGIC_COMPOSE_FEEDBACK;
            case 165:
                return emxt.MAGIC_COMPOSE_CONSENT;
            case 166:
                return emxt.SIM_STATE_TRACKER_EVENT;
            case 167:
                return emxt.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 168:
                return emxt.BUGLE_SYSTEM_BACKUP_EVENT;
            case 169:
                return emxt.MAGIC_COMPOSE_ERROR;
            case 170:
                return emxt.MAGIC_COMPOSE_EVENT;
            case 171:
                return emxt.MAGIC_COMPOSE_DISPLAY;
            case 172:
                return emxt.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 173:
                return emxt.HOME_SCREEN_FIRST_VISIT;
            case 174:
                return emxt.DANGLING_PARTS_EVENT;
            case 175:
                return emxt.MAGIC_COMPOSE_ICON_EVENT;
            case 176:
                return emxt.MAGIC_COMPOSE_SETTING;
            case 177:
                return emxt.SMS_SUBJECT_REPORT_EVENT;
            case 178:
                return emxt.MULTI_SHARE_EVENT;
            case 179:
                return emxt.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 180:
                return emxt.TOGGLE_RCS_CHATS_EVENT;
            case 181:
                return emxt.EMOTIFY_CREATE_EVENT;
            case 182:
                return emxt.EMOTIFY_IMPRESSION_EVENT;
            case 183:
                return emxt.EMOTIFY_MESSAGE_SEND_EVENT;
            case 184:
                return emxt.EMOTIFY_DELETE_EVENT;
            case 185:
                return emxt.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 186:
                return emxt.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 187:
                return emxt.MEET_CALLING_EVENT;
            case 188:
                return emxt.RCS_PROVISIONING_MANAGER_EVENT;
            case 189:
                return emxt.VOICE_MOOD_EVENT;
            case 190:
                return emxt.BARD_EVENT;
            case 191:
                return emxt.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 192:
                return emxt.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 193:
                return emxt.REVOKE_CONSENT_EVENT;
            case 194:
                return emxt.RCS_LOCAL_IDENTITY_EVENT;
            case 195:
                return emxt.D2D_BACKUP_AND_RESTORE_EVENT;
            case 196:
                return emxt.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case 197:
                return emxt.GAIA_SIGN_IN_EVENT;
            case 198:
                return emxt.SELFIE_GIF_EVENT;
            case 199:
                return emxt.GAIA_SIGN_IN_STATE;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return emxt.SATELLITE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return emxt.MMS_GROUP_UPGRADE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return emxt.RESTORE_WORKFLOW_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return emxt.BACKUP_WORKFLOW_EVENT;
            case 204:
                return emxt.VIDEO_CALLING_EVENT;
            case 205:
                return emxt.TELEPHONY_PERSISTENCE_EVENT;
            case 206:
                return emxt.MMS_GROUP_EVENT;
            case 207:
                return emxt.OPEN_PENPAL_CHAT_EVENT;
            case 208:
                return emxt.BUGLE_COMPOSE_DISABLED_EVENT;
            case 209:
                return emxt.GAIA_REPORT_EVENT;
            case 210:
                return emxt.MMS_MERGING_EVENT;
            case 211:
                return emxt.BUGLE_FILE_PROCESSING;
            case 212:
                return emxt.CONVERSATION_SCREEN_FIRST_VISIT;
            case 213:
                return emxt.TYCHO_GRPC_EVENT;
            case 214:
                return emxt.SCREEN_EFFECTS_EVENT;
            case 215:
                return emxt.TOOLSTONE_EVENT;
            case 216:
                return emxt.RCS_AVAILABILITY_ON_FIRST_APP_OPEN;
            case 217:
                return emxt.BUGLE_WELCOME_V1_EVENT;
            case 218:
                return emxt.BUGLE_MLS_EVENT;
            case 219:
                return emxt.RCS_REFLECTION_EVENT;
            case 220:
                return emxt.OUT_OF_ORDER_RCS_MESSAGE_DELIVERY;
            case 221:
                return emxt.MISSING_RCS_MESSAGE_EVENT;
        }
    }

    public emxt c() {
        throw null;
    }
}
