package defpackage;

import com.google.android.apps.messaging.shared.api.messaging.conversation.bugle.BugleConversationId;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class amdy implements alzb {
    private final fcsu A;
    private final fcsu B;
    private final fcsu C;
    private final fcsu D;
    private final fcsu E;
    private final fcsu F;
    private final fcsu G;
    private final fcsu H;
    private final fcsu I;
    private final fcsu J;
    private final fcsu K;
    private final fcsu L;
    private final fcsu M;
    private final fcsu N;
    private final fcsu O;
    private final fcsu P;
    private final fcsu Q;
    private final fcsu R;
    private final fcsu S;
    private final fcsu T;
    private final fcsu U;
    private final fcsu V;
    private final fcsu W;
    private final fcsu X;
    private final fcsu Y;
    private final fcsu Z;
    private final fcsu a;
    private final fcsu aa;
    private final fcsu ab;
    private final fcsu ac;
    private final fcsu ad;
    private final fcsu ae;
    private final fcsu af;
    private final fcsu b;
    private final fcsu c;
    private final fcsu d;
    private final fcsu e;
    private final fcsu f;
    private final fcsu g;
    private final fcsu h;
    private final fcsu i;
    private final fcsu j;
    private final fcsu k;
    private final fcsu l;
    private final fcsu m;
    private final fcsu n;
    private final fcsu o;
    private final fcsu p;
    private final fcsu q;
    private final fcsu r;
    private final fcsu s;
    private final fcsu t;
    private final fcsu u;
    private final fcsu v;
    private final fcsu w;
    private final fcsu x;
    private final fcsu y;
    private final fcsu z;

    public amdy(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4, fcsu fcsuVar5, fcsu fcsuVar6, fcsu fcsuVar7, fcsu fcsuVar8, fcsu fcsuVar9, fcsu fcsuVar10, fcsu fcsuVar11, fcsu fcsuVar12, fcsu fcsuVar13, fcsu fcsuVar14, fcsu fcsuVar15, fcsu fcsuVar16, fcsu fcsuVar17, fcsu fcsuVar18, fcsu fcsuVar19, fcsu fcsuVar20, fcsu fcsuVar21, fcsu fcsuVar22, fcsu fcsuVar23, fcsu fcsuVar24, fcsu fcsuVar25, fcsu fcsuVar26, fcsu fcsuVar27, fcsu fcsuVar28, fcsu fcsuVar29, fcsu fcsuVar30, fcsu fcsuVar31, fcsu fcsuVar32, fcsu fcsuVar33, fcsu fcsuVar34, fcsu fcsuVar35, fcsu fcsuVar36, fcsu fcsuVar37, fcsu fcsuVar38, fcsu fcsuVar39, fcsu fcsuVar40, fcsu fcsuVar41, fcsu fcsuVar42, fcsu fcsuVar43, fcsu fcsuVar44, fcsu fcsuVar45, fcsu fcsuVar46, fcsu fcsuVar47, fcsu fcsuVar48, fcsu fcsuVar49, fcsu fcsuVar50, fcsu fcsuVar51, fcsu fcsuVar52, fcsu fcsuVar53, fcsu fcsuVar54, fcsu fcsuVar55, fcsu fcsuVar56, fcsu fcsuVar57, fcsu fcsuVar58, fcsu fcsuVar59) {
        fcsuVar.getClass();
        this.a = fcsuVar;
        fcsuVar2.getClass();
        this.b = fcsuVar2;
        fcsuVar3.getClass();
        this.c = fcsuVar3;
        this.d = fcsuVar4;
        fcsuVar5.getClass();
        this.e = fcsuVar5;
        fcsuVar6.getClass();
        this.f = fcsuVar6;
        this.g = fcsuVar7;
        this.h = fcsuVar8;
        fcsuVar9.getClass();
        this.i = fcsuVar9;
        fcsuVar10.getClass();
        this.j = fcsuVar10;
        fcsuVar11.getClass();
        this.k = fcsuVar11;
        this.l = fcsuVar12;
        this.m = fcsuVar13;
        this.n = fcsuVar14;
        this.o = fcsuVar15;
        fcsuVar16.getClass();
        this.p = fcsuVar16;
        fcsuVar17.getClass();
        this.q = fcsuVar17;
        fcsuVar18.getClass();
        this.r = fcsuVar18;
        fcsuVar19.getClass();
        this.s = fcsuVar19;
        fcsuVar20.getClass();
        this.t = fcsuVar20;
        fcsuVar21.getClass();
        this.u = fcsuVar21;
        this.v = fcsuVar22;
        fcsuVar23.getClass();
        this.w = fcsuVar23;
        fcsuVar24.getClass();
        this.x = fcsuVar24;
        fcsuVar25.getClass();
        this.y = fcsuVar25;
        this.z = fcsuVar26;
        this.A = fcsuVar27;
        this.B = fcsuVar28;
        this.C = fcsuVar29;
        this.D = fcsuVar30;
        this.E = fcsuVar31;
        fcsuVar32.getClass();
        this.F = fcsuVar32;
        this.G = fcsuVar33;
        fcsuVar34.getClass();
        this.H = fcsuVar34;
        this.I = fcsuVar35;
        this.J = fcsuVar36;
        fcsuVar37.getClass();
        this.K = fcsuVar37;
        fcsuVar38.getClass();
        this.L = fcsuVar38;
        this.M = fcsuVar39;
        this.N = fcsuVar40;
        this.O = fcsuVar41;
        fcsuVar42.getClass();
        this.P = fcsuVar42;
        fcsuVar43.getClass();
        this.Q = fcsuVar43;
        this.R = fcsuVar44;
        fcsuVar45.getClass();
        this.S = fcsuVar45;
        fcsuVar46.getClass();
        this.T = fcsuVar46;
        this.U = fcsuVar47;
        this.V = fcsuVar48;
        this.W = fcsuVar49;
        this.X = fcsuVar50;
        fcsuVar51.getClass();
        this.Y = fcsuVar51;
        fcsuVar52.getClass();
        this.Z = fcsuVar53;
        this.aa = fcsuVar54;
        this.ab = fcsuVar55;
        this.ac = fcsuVar56;
        this.ad = fcsuVar57;
        fcsuVar58.getClass();
        this.ae = fcsuVar58;
        this.af = fcsuVar59;
    }

    @Override // defpackage.alzb
    public final /* synthetic */ alza a(BugleConversationId bugleConversationId, anpj anpjVar, anpj anpjVar2, anpj anpjVar3, alxh alxhVar, boolean z, boolean z2) {
        return b(bugleConversationId, anpjVar, anpjVar2, anpjVar3, alxhVar, z, z2, null);
    }

    public final amdx b(BugleConversationId bugleConversationId, anpj anpjVar, anpj anpjVar2, anpj anpjVar3, alxh alxhVar, boolean z, boolean z2, alza alzaVar) {
        cqtp cqtpVar = (cqtp) this.a.b();
        cqtpVar.getClass();
        eosc eoscVar = (eosc) this.b.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.c.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.d.b();
        eoscVar3.getClass();
        amli amliVar = (amli) this.e.b();
        amliVar.getClass();
        ankd ankdVar = (ankd) this.f.b();
        ankdVar.getClass();
        amet ametVar = (amet) this.g.b();
        ametVar.getClass();
        anes anesVar = (anes) this.h.b();
        anesVar.getClass();
        amer amerVar = (amer) this.k.b();
        amerVar.getClass();
        alyz alyzVar = (alyz) this.l.b();
        alyzVar.getClass();
        alzh alzhVar = (alzh) this.m.b();
        alzhVar.getClass();
        anph anphVar = (anph) this.q.b();
        anphVar.getClass();
        alzw alzwVar = (alzw) this.r.b();
        alzwVar.getClass();
        amhr amhrVar = (amhr) this.B.b();
        amhrVar.getClass();
        aqkk aqkkVar = (aqkk) this.C.b();
        aqkkVar.getClass();
        ankx ankxVar = (ankx) this.E.b();
        ankxVar.getClass();
        amhd amhdVar = (amhd) this.G.b();
        amhdVar.getClass();
        Optional optional = (Optional) this.H.b();
        optional.getClass();
        fcsu fcsuVar = this.L;
        fcsu fcsuVar2 = this.K;
        fcsu fcsuVar3 = this.J;
        fcsu fcsuVar4 = this.I;
        fcsu fcsuVar5 = this.F;
        fcsu fcsuVar6 = this.D;
        fcsu fcsuVar7 = this.A;
        fcsu fcsuVar8 = this.z;
        fcsu fcsuVar9 = this.y;
        fcsu fcsuVar10 = this.x;
        fcsu fcsuVar11 = this.w;
        fcsu fcsuVar12 = this.v;
        fcsu fcsuVar13 = this.u;
        fcsu fcsuVar14 = this.t;
        fcsu fcsuVar15 = this.s;
        fcsu fcsuVar16 = this.p;
        fcsu fcsuVar17 = this.o;
        fcsu fcsuVar18 = this.n;
        fcsu fcsuVar19 = this.j;
        fcsu fcsuVar20 = this.i;
        fcsu fcsuVar21 = this.M;
        fcsu fcsuVar22 = this.N;
        fcsu fcsuVar23 = this.O;
        fcsu fcsuVar24 = this.P;
        fcsu fcsuVar25 = this.Q;
        fcsu fcsuVar26 = this.R;
        fcsu fcsuVar27 = this.S;
        fcsu fcsuVar28 = this.T;
        fcsu fcsuVar29 = this.U;
        fcsu fcsuVar30 = this.V;
        fcsu fcsuVar31 = this.W;
        anoj anojVar = (anoj) this.X.b();
        anojVar.getClass();
        fcsu fcsuVar32 = this.Y;
        fcsu fcsuVar33 = this.Z;
        fcsu fcsuVar34 = this.aa;
        fcsu fcsuVar35 = this.ab;
        fcsu fcsuVar36 = this.ac;
        fcsu fcsuVar37 = this.ad;
        anpjVar.getClass();
        anpjVar2.getClass();
        anpjVar3.getClass();
        arkz arkzVar = (arkz) this.ae.b();
        arkzVar.getClass();
        return new amdx(cqtpVar, eoscVar, eoscVar2, eoscVar3, amliVar, ankdVar, ametVar, anesVar, fcsuVar20, fcsuVar19, amerVar, alyzVar, alzhVar, fcsuVar18, fcsuVar17, fcsuVar16, anphVar, alzwVar, fcsuVar15, fcsuVar14, fcsuVar13, fcsuVar12, fcsuVar11, fcsuVar10, fcsuVar9, fcsuVar8, fcsuVar7, amhrVar, aqkkVar, fcsuVar6, ankxVar, fcsuVar5, amhdVar, optional, fcsuVar4, fcsuVar3, fcsuVar2, fcsuVar, fcsuVar21, fcsuVar22, fcsuVar23, fcsuVar24, fcsuVar25, fcsuVar26, fcsuVar27, fcsuVar28, fcsuVar29, fcsuVar30, fcsuVar31, anojVar, fcsuVar32, fcsuVar33, fcsuVar34, fcsuVar35, fcsuVar36, fcsuVar37, bugleConversationId, anpjVar, anpjVar2, anpjVar3, alxhVar, z, z2, alzaVar, arkzVar, this.af);
    }
}
