package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class av {
    public int b;
    public int c;
    int d;
    boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public final av clone() {
        av avVar = new av();
        avVar.a = this.a;
        avVar.b = this.b;
        avVar.c = this.c;
        avVar.e = this.e;
        avVar.f = this.f;
        avVar.g = this.g;
        avVar.h = this.h;
        avVar.i = this.i;
        avVar.j = this.j;
        avVar.k = this.k;
        avVar.l = this.l;
        avVar.m = this.m;
        avVar.n = this.n;
        avVar.o = this.o;
        avVar.p = this.p;
        avVar.q = this.q;
        avVar.r = this.r;
        avVar.s = this.s;
        avVar.t = this.t;
        avVar.u = this.u;
        avVar.v = this.v;
        avVar.w = this.w;
        avVar.x = this.x;
        avVar.y = this.y;
        avVar.u = this.u;
        avVar.u = this.u;
        avVar.u = this.u;
        avVar.u = this.u;
        avVar.u = this.u;
        avVar.z = this.z;
        avVar.A = this.A;
        avVar.B = this.B;
        avVar.C = this.C;
        avVar.D = this.D;
        avVar.E = this.E;
        avVar.F = this.F;
        avVar.G = this.G;
        avVar.H = this.H;
        avVar.I = this.I;
        avVar.J = this.J;
        avVar.K = this.K;
        avVar.L = this.L;
        avVar.M = this.M;
        avVar.N = this.N;
        avVar.O = this.O;
        avVar.P = this.P;
        avVar.Q = this.Q;
        avVar.R = this.R;
        avVar.S = this.S;
        avVar.T = this.T;
        avVar.U = this.U;
        avVar.V = this.V;
        avVar.W = this.W;
        avVar.X = this.X;
        avVar.Y = this.Y;
        avVar.Z = this.Z;
        avVar.aa = this.aa;
        avVar.ab = this.ab;
        avVar.ac = this.ac;
        avVar.ad = this.ad;
        avVar.ae = this.ae;
        avVar.af = this.af;
        avVar.ag = this.ag;
        avVar.ah = this.ah;
        avVar.ai = this.ai;
        return avVar;
    }

    public final void b(au auVar) {
        auVar.d = this.h;
        auVar.e = this.i;
        auVar.f = this.j;
        auVar.g = this.k;
        auVar.h = this.l;
        auVar.i = this.m;
        auVar.j = this.n;
        auVar.k = this.o;
        auVar.l = this.p;
        auVar.m = this.q;
        auVar.n = this.r;
        auVar.o = this.s;
        auVar.p = this.t;
        auVar.leftMargin = this.A;
        auVar.rightMargin = this.B;
        auVar.topMargin = this.C;
        auVar.bottomMargin = this.D;
        auVar.u = this.M;
        auVar.v = this.L;
        auVar.w = this.u;
        auVar.x = this.v;
        auVar.y = this.w;
        auVar.K = this.x;
        auVar.L = this.y;
        auVar.B = this.N;
        auVar.A = this.O;
        auVar.D = this.Q;
        auVar.C = this.P;
        auVar.E = this.ad;
        auVar.F = this.ae;
        auVar.I = this.af;
        auVar.J = this.ag;
        auVar.G = this.ah;
        auVar.H = this.ai;
        auVar.M = this.z;
        auVar.c = this.g;
        auVar.a = this.e;
        auVar.b = this.f;
        auVar.width = this.b;
        auVar.height = this.c;
        auVar.setMarginStart(this.F);
        auVar.setMarginEnd(this.E);
        auVar.a();
    }
}
