package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class axtn {
    public final fcsu A;
    public final fcsu B;
    public final fcsu C;
    public final fcsu D;
    public final fcsu E;
    public final fcsu F;
    public final fcsu G;
    public final fcsu H;
    public final fcsu I;
    public final fcsu J;
    public final fcsu K;
    public final fcsu L;
    public final fcsu a;
    public final fcsu b;
    public final fcsu c;
    public final fcsu d;
    public final fcsu e;
    public final fcsu f;
    public final fcsu g;
    public final fcsu h;
    public final fcsu i;
    public final fcsu j;
    public final fcsu k;
    public final fcsu l;
    public final fcsu m;
    public final fcsu n;
    public final fcsu o;
    public final fcsu p;
    public final fcsu q;
    public final fcsu r;
    public final fcsu s;
    public final fcsu t;
    public final fcsu u;
    public final fcsu v;
    public final fcsu w;
    public final fcsu x;
    public final fcsu y;
    public final fcsu z;

    public axtn(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4, fcsu fcsuVar5, fcsu fcsuVar6, fcsu fcsuVar7, fcsu fcsuVar8, fcsu fcsuVar9, fcsu fcsuVar10, fcsu fcsuVar11, fcsu fcsuVar12, fcsu fcsuVar13, fcsu fcsuVar14, fcsu fcsuVar15, fcsu fcsuVar16, fcsu fcsuVar17, fcsu fcsuVar18, fcsu fcsuVar19, fcsu fcsuVar20, fcsu fcsuVar21, fcsu fcsuVar22, fcsu fcsuVar23, fcsu fcsuVar24, fcsu fcsuVar25, fcsu fcsuVar26, fcsu fcsuVar27, fcsu fcsuVar28, fcsu fcsuVar29, fcsu fcsuVar30, fcsu fcsuVar31, fcsu fcsuVar32, fcsu fcsuVar33, fcsu fcsuVar34, fcsu fcsuVar35, fcsu fcsuVar36, fcsu fcsuVar37, fcsu fcsuVar38, fcsu fcsuVar39) {
        fcsuVar.getClass();
        this.a = fcsuVar;
        this.b = fcsuVar2;
        this.c = fcsuVar3;
        fcsuVar4.getClass();
        this.d = fcsuVar4;
        fcsuVar5.getClass();
        this.e = fcsuVar5;
        fcsuVar6.getClass();
        this.f = fcsuVar6;
        fcsuVar7.getClass();
        this.g = fcsuVar7;
        this.h = fcsuVar8;
        fcsuVar9.getClass();
        this.i = fcsuVar9;
        this.j = fcsuVar10;
        fcsuVar11.getClass();
        this.k = fcsuVar11;
        fcsuVar12.getClass();
        this.l = fcsuVar12;
        fcsuVar13.getClass();
        this.m = fcsuVar13;
        fcsuVar14.getClass();
        this.n = fcsuVar14;
        fcsuVar15.getClass();
        this.o = fcsuVar15;
        fcsuVar16.getClass();
        this.p = fcsuVar16;
        fcsuVar17.getClass();
        this.q = fcsuVar17;
        fcsuVar18.getClass();
        this.r = fcsuVar18;
        fcsuVar19.getClass();
        this.s = fcsuVar19;
        fcsuVar20.getClass();
        this.t = fcsuVar20;
        fcsuVar21.getClass();
        this.u = fcsuVar21;
        fcsuVar22.getClass();
        this.v = fcsuVar22;
        fcsuVar23.getClass();
        this.w = fcsuVar23;
        fcsuVar24.getClass();
        this.x = fcsuVar24;
        fcsuVar25.getClass();
        this.y = fcsuVar25;
        fcsuVar26.getClass();
        this.z = fcsuVar26;
        fcsuVar27.getClass();
        this.A = fcsuVar27;
        fcsuVar28.getClass();
        this.B = fcsuVar28;
        fcsuVar29.getClass();
        this.C = fcsuVar29;
        fcsuVar30.getClass();
        this.D = fcsuVar30;
        fcsuVar31.getClass();
        this.E = fcsuVar31;
        fcsuVar32.getClass();
        this.F = fcsuVar32;
        fcsuVar33.getClass();
        this.G = fcsuVar33;
        fcsuVar34.getClass();
        this.H = fcsuVar34;
        fcsuVar35.getClass();
        this.I = fcsuVar35;
        fcsuVar36.getClass();
        this.J = fcsuVar36;
        fcsuVar37.getClass();
        fcsuVar38.getClass();
        this.K = fcsuVar38;
        fcsuVar39.getClass();
        this.L = fcsuVar39;
    }
}
