package defpackage;

import android.net.Uri;
import android.os.Parcel;
import com.google.android.apps.messaging.shared.datamodel.action.ProcessMessageUpdateAsyncAction;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class axxv implements aypu {
    private final fcsu A;
    private final fcsu B;
    private final fcsu C;
    private final fcsu D;
    private final fcsu E;
    private final fcsu F;
    private final fcsu a;
    private final fcsu b;
    private final fcsu c;
    private final fcsu d;
    private final fcsu e;
    private final fcsu f;
    private final fcsu g;
    private final fcsu h;
    private final fcsu i;
    private final fcsu j;
    private final fcsu k;
    private final fcsu l;
    private final fcsu m;
    private final fcsu n;
    private final fcsu o;
    private final fcsu p;
    private final fcsu q;
    private final fcsu r;
    private final fcsu s;
    private final fcsu t;
    private final fcsu u;
    private final fcsu v;
    private final fcsu w;
    private final fcsu x;
    private final fcsu y;
    private final fcsu z;

    public axxv(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4, fcsu fcsuVar5, fcsu fcsuVar6, fcsu fcsuVar7, fcsu fcsuVar8, fcsu fcsuVar9, fcsu fcsuVar10, fcsu fcsuVar11, fcsu fcsuVar12, fcsu fcsuVar13, fcsu fcsuVar14, fcsu fcsuVar15, fcsu fcsuVar16, fcsu fcsuVar17, fcsu fcsuVar18, fcsu fcsuVar19, fcsu fcsuVar20, fcsu fcsuVar21, fcsu fcsuVar22, fcsu fcsuVar23, fcsu fcsuVar24, fcsu fcsuVar25, fcsu fcsuVar26, fcsu fcsuVar27, fcsu fcsuVar28, fcsu fcsuVar29, fcsu fcsuVar30, fcsu fcsuVar31, fcsu fcsuVar32) {
        fcsuVar.getClass();
        this.a = fcsuVar;
        fcsuVar2.getClass();
        this.b = fcsuVar2;
        fcsuVar3.getClass();
        this.c = fcsuVar3;
        fcsuVar4.getClass();
        this.d = fcsuVar4;
        fcsuVar5.getClass();
        this.e = fcsuVar5;
        fcsuVar6.getClass();
        this.f = fcsuVar6;
        fcsuVar7.getClass();
        this.g = fcsuVar7;
        fcsuVar8.getClass();
        this.h = fcsuVar8;
        fcsuVar9.getClass();
        this.i = fcsuVar9;
        fcsuVar10.getClass();
        this.j = fcsuVar10;
        fcsuVar11.getClass();
        this.k = fcsuVar11;
        fcsuVar12.getClass();
        this.l = fcsuVar12;
        this.m = fcsuVar13;
        fcsuVar14.getClass();
        this.n = fcsuVar14;
        this.o = fcsuVar15;
        fcsuVar16.getClass();
        this.p = fcsuVar16;
        this.q = fcsuVar17;
        fcsuVar18.getClass();
        this.r = fcsuVar18;
        this.s = fcsuVar19;
        fcsuVar20.getClass();
        this.t = fcsuVar20;
        this.u = fcsuVar21;
        this.v = fcsuVar22;
        fcsuVar23.getClass();
        this.w = fcsuVar23;
        fcsuVar24.getClass();
        this.x = fcsuVar24;
        fcsuVar25.getClass();
        this.y = fcsuVar25;
        fcsuVar26.getClass();
        this.z = fcsuVar26;
        fcsuVar27.getClass();
        this.A = fcsuVar27;
        this.B = fcsuVar28;
        fcsuVar29.getClass();
        this.C = fcsuVar29;
        fcsuVar30.getClass();
        this.D = fcsuVar30;
        fcsuVar31.getClass();
        this.E = fcsuVar31;
        fcsuVar32.getClass();
        this.F = fcsuVar32;
    }

    @Override // defpackage.ayms
    /* renamed from: a, reason: merged with bridge method [inline-methods] */
    public final ProcessMessageUpdateAsyncAction c(Parcel parcel) {
        bvkr bvkrVar = (bvkr) this.a.b();
        bvkrVar.getClass();
        cfeh cfehVar = (cfeh) this.d.b();
        cfehVar.getClass();
        ains ainsVar = (ains) this.f.b();
        ainsVar.getClass();
        ayps aypsVar = (ayps) this.g.b();
        aypsVar.getClass();
        aypz aypzVar = (aypz) this.h.b();
        aypzVar.getClass();
        ayqp ayqpVar = (ayqp) this.i.b();
        ayqpVar.getClass();
        baeb baebVar = (baeb) this.j.b();
        baebVar.getClass();
        eosc eoscVar = (eosc) this.k.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.l.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.m.b();
        eoscVar3.getClass();
        bael baelVar = (bael) this.o.b();
        baelVar.getClass();
        baes baesVar = (baes) this.p.b();
        baesVar.getClass();
        cogw cogwVar = (cogw) this.s.b();
        cogwVar.getClass();
        aqmq aqmqVar = (aqmq) this.v.b();
        aqmqVar.getClass();
        ((aqox) this.z.b()).getClass();
        aqad aqadVar = (aqad) this.D.b();
        aqadVar.getClass();
        parcel.getClass();
        fcsu fcsuVar = this.w;
        fcsu fcsuVar2 = this.x;
        fcsu fcsuVar3 = this.y;
        fcsu fcsuVar4 = this.A;
        fcsu fcsuVar5 = this.B;
        fcsu fcsuVar6 = this.C;
        fcsu fcsuVar7 = this.t;
        fcsu fcsuVar8 = this.u;
        fcsu fcsuVar9 = this.q;
        fcsu fcsuVar10 = this.r;
        fcsu fcsuVar11 = this.n;
        return new ProcessMessageUpdateAsyncAction(bvkrVar, this.b, this.c, cfehVar, this.e, ainsVar, aypsVar, aypzVar, ayqpVar, baebVar, eoscVar, eoscVar2, eoscVar3, fcsuVar11, baelVar, baesVar, fcsuVar9, fcsuVar10, cogwVar, fcsuVar7, fcsuVar8, aqmqVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, fcsuVar6, aqadVar, parcel);
    }

    public final ProcessMessageUpdateAsyncAction b(ezol ezolVar, String str, long j) {
        bvkr bvkrVar = (bvkr) this.a.b();
        bvkrVar.getClass();
        cfeh cfehVar = (cfeh) this.d.b();
        cfehVar.getClass();
        ains ainsVar = (ains) this.f.b();
        ainsVar.getClass();
        ayps aypsVar = (ayps) this.g.b();
        aypsVar.getClass();
        aypz aypzVar = (aypz) this.h.b();
        aypzVar.getClass();
        ayqp ayqpVar = (ayqp) this.i.b();
        ayqpVar.getClass();
        baeb baebVar = (baeb) this.j.b();
        baebVar.getClass();
        eosc eoscVar = (eosc) this.k.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.l.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.m.b();
        eoscVar3.getClass();
        bael baelVar = (bael) this.o.b();
        baelVar.getClass();
        baes baesVar = (baes) this.p.b();
        baesVar.getClass();
        cogw cogwVar = (cogw) this.s.b();
        cogwVar.getClass();
        aqmq aqmqVar = (aqmq) this.v.b();
        aqmqVar.getClass();
        ((aqox) this.z.b()).getClass();
        aqad aqadVar = (aqad) this.D.b();
        aqadVar.getClass();
        fcsu fcsuVar = this.w;
        fcsu fcsuVar2 = this.x;
        fcsu fcsuVar3 = this.y;
        fcsu fcsuVar4 = this.A;
        fcsu fcsuVar5 = this.B;
        fcsu fcsuVar6 = this.C;
        fcsu fcsuVar7 = this.t;
        fcsu fcsuVar8 = this.u;
        fcsu fcsuVar9 = this.q;
        fcsu fcsuVar10 = this.r;
        fcsu fcsuVar11 = this.n;
        return new ProcessMessageUpdateAsyncAction(bvkrVar, this.b, this.c, cfehVar, this.e, ainsVar, aypsVar, aypzVar, ayqpVar, baebVar, eoscVar, eoscVar2, eoscVar3, fcsuVar11, baelVar, baesVar, fcsuVar9, fcsuVar10, cogwVar, fcsuVar7, fcsuVar8, aqmqVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, fcsuVar6, aqadVar, ezolVar, str, j);
    }

    public final ProcessMessageUpdateAsyncAction d(ezol ezolVar, String str, Uri uri) {
        bvkr bvkrVar = (bvkr) this.a.b();
        bvkrVar.getClass();
        Optional optional = (Optional) this.E.b();
        optional.getClass();
        cfeh cfehVar = (cfeh) this.d.b();
        cfehVar.getClass();
        ains ainsVar = (ains) this.f.b();
        ainsVar.getClass();
        ayps aypsVar = (ayps) this.g.b();
        aypsVar.getClass();
        aypz aypzVar = (aypz) this.h.b();
        aypzVar.getClass();
        ayqp ayqpVar = (ayqp) this.i.b();
        ayqpVar.getClass();
        baeb baebVar = (baeb) this.j.b();
        baebVar.getClass();
        eosc eoscVar = (eosc) this.k.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.l.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.m.b();
        eoscVar3.getClass();
        bael baelVar = (bael) this.o.b();
        baelVar.getClass();
        baes baesVar = (baes) this.p.b();
        baesVar.getClass();
        cogw cogwVar = (cogw) this.s.b();
        cogwVar.getClass();
        aqmq aqmqVar = (aqmq) this.v.b();
        aqmqVar.getClass();
        ((aqox) this.z.b()).getClass();
        aqad aqadVar = (aqad) this.D.b();
        aqadVar.getClass();
        fcsu fcsuVar = this.w;
        fcsu fcsuVar2 = this.x;
        fcsu fcsuVar3 = this.y;
        fcsu fcsuVar4 = this.A;
        fcsu fcsuVar5 = this.B;
        fcsu fcsuVar6 = this.C;
        fcsu fcsuVar7 = this.t;
        fcsu fcsuVar8 = this.u;
        fcsu fcsuVar9 = this.q;
        fcsu fcsuVar10 = this.r;
        fcsu fcsuVar11 = this.n;
        return new ProcessMessageUpdateAsyncAction(bvkrVar, optional, this.b, this.c, cfehVar, this.e, ainsVar, aypsVar, aypzVar, ayqpVar, baebVar, eoscVar, eoscVar2, eoscVar3, fcsuVar11, baelVar, baesVar, fcsuVar9, fcsuVar10, cogwVar, fcsuVar7, fcsuVar8, aqmqVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, fcsuVar6, aqadVar, ezolVar, str, uri);
    }

    public final ProcessMessageUpdateAsyncAction e(ezol ezolVar, String str, Uri uri, long j) {
        bvkr bvkrVar = (bvkr) this.a.b();
        bvkrVar.getClass();
        Optional optional = (Optional) this.E.b();
        optional.getClass();
        cfeh cfehVar = (cfeh) this.d.b();
        cfehVar.getClass();
        ains ainsVar = (ains) this.f.b();
        ainsVar.getClass();
        ayps aypsVar = (ayps) this.g.b();
        aypsVar.getClass();
        aypz aypzVar = (aypz) this.h.b();
        aypzVar.getClass();
        ayqp ayqpVar = (ayqp) this.i.b();
        ayqpVar.getClass();
        baeb baebVar = (baeb) this.j.b();
        baebVar.getClass();
        eosc eoscVar = (eosc) this.k.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.l.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.m.b();
        eoscVar3.getClass();
        bael baelVar = (bael) this.o.b();
        baelVar.getClass();
        baes baesVar = (baes) this.p.b();
        baesVar.getClass();
        cogw cogwVar = (cogw) this.s.b();
        cogwVar.getClass();
        aqmq aqmqVar = (aqmq) this.v.b();
        aqmqVar.getClass();
        ((aqox) this.z.b()).getClass();
        fcsu fcsuVar = this.w;
        fcsu fcsuVar2 = this.x;
        fcsu fcsuVar3 = this.y;
        fcsu fcsuVar4 = this.A;
        fcsu fcsuVar5 = this.B;
        fcsu fcsuVar6 = this.C;
        aqad aqadVar = (aqad) this.D.b();
        aqadVar.getClass();
        fcsu fcsuVar7 = this.F;
        fcsu fcsuVar8 = this.t;
        fcsu fcsuVar9 = this.u;
        fcsu fcsuVar10 = this.q;
        fcsu fcsuVar11 = this.r;
        fcsu fcsuVar12 = this.n;
        return new ProcessMessageUpdateAsyncAction(bvkrVar, optional, this.b, this.c, cfehVar, this.e, ainsVar, aypsVar, aypzVar, ayqpVar, baebVar, eoscVar, eoscVar2, eoscVar3, fcsuVar12, baelVar, baesVar, fcsuVar10, fcsuVar11, cogwVar, fcsuVar8, fcsuVar9, aqmqVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, fcsuVar6, aqadVar, fcsuVar7, ezolVar, str, uri, j);
    }

    @Override // defpackage.aypu
    public final /* bridge */ /* synthetic */ Action f(ezol ezolVar, String str, long j) {
        bvkr bvkrVar = (bvkr) this.a.b();
        bvkrVar.getClass();
        cfeh cfehVar = (cfeh) this.d.b();
        cfehVar.getClass();
        ains ainsVar = (ains) this.f.b();
        ainsVar.getClass();
        ayps aypsVar = (ayps) this.g.b();
        aypsVar.getClass();
        aypz aypzVar = (aypz) this.h.b();
        aypzVar.getClass();
        ayqp ayqpVar = (ayqp) this.i.b();
        ayqpVar.getClass();
        baeb baebVar = (baeb) this.j.b();
        baebVar.getClass();
        eosc eoscVar = (eosc) this.k.b();
        eoscVar.getClass();
        eosc eoscVar2 = (eosc) this.l.b();
        eoscVar2.getClass();
        eosc eoscVar3 = (eosc) this.m.b();
        eoscVar3.getClass();
        bael baelVar = (bael) this.o.b();
        baelVar.getClass();
        baes baesVar = (baes) this.p.b();
        baesVar.getClass();
        cogw cogwVar = (cogw) this.s.b();
        cogwVar.getClass();
        aqmq aqmqVar = (aqmq) this.v.b();
        aqmqVar.getClass();
        ((aqox) this.z.b()).getClass();
        aqad aqadVar = (aqad) this.D.b();
        aqadVar.getClass();
        ezolVar.getClass();
        str.getClass();
        fcsu fcsuVar = this.w;
        fcsu fcsuVar2 = this.x;
        fcsu fcsuVar3 = this.y;
        fcsu fcsuVar4 = this.A;
        fcsu fcsuVar5 = this.B;
        fcsu fcsuVar6 = this.t;
        fcsu fcsuVar7 = this.u;
        fcsu fcsuVar8 = this.q;
        fcsu fcsuVar9 = this.r;
        fcsu fcsuVar10 = this.n;
        return new ProcessMessageUpdateAsyncAction(bvkrVar, this.b, this.c, cfehVar, this.e, ainsVar, aypsVar, aypzVar, ayqpVar, baebVar, eoscVar, eoscVar2, eoscVar3, fcsuVar10, baelVar, baesVar, fcsuVar8, fcsuVar9, cogwVar, fcsuVar6, fcsuVar7, aqmqVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, this.C, aqadVar, ezolVar, str, j, (byte[]) null);
    }
}
