package defpackage;

import android.content.Context;
import android.os.Parcel;
import com.google.android.apps.messaging.shared.datamodel.action.SendMessageAction;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class aygy implements ayql {
    private final fcsu A;
    private final fcsu B;
    private final fcsu C;
    private final fcsu D;
    private final fcsu E;
    private final fcsu F;
    private final fcsu G;
    private final fcsu H;
    private final fcsu I;
    private final fcsu J;
    private final fcsu K;
    private final fcsu L;
    private final fcsu M;
    private final fcsu N;
    private final fcsu O;
    private final fcsu P;
    private final fcsu Q;
    private final fcsu R;
    private final fcsu S;
    private final fcsu T;
    private final fcsu U;
    private final fcsu V;
    private final fcsu W;
    private final fcsu X;
    private final fcsu Y;
    private final fcsu Z;
    private final fcsu a;
    private final fcsu aa;
    private final fcsu ab;
    private final fcsu ac;
    private final fcsu b;
    private final fcsu c;
    private final fcsu d;
    private final fcsu e;
    private final fcsu f;
    private final fcsu g;
    private final fcsu h;
    private final fcsu i;
    private final fcsu j;
    private final fcsu k;
    private final fcsu l;
    private final fcsu m;
    private final fcsu n;
    private final fcsu o;
    private final fcsu p;
    private final fcsu q;
    private final fcsu r;
    private final fcsu s;
    private final fcsu t;
    private final fcsu u;
    private final fcsu v;
    private final fcsu w;
    private final fcsu x;
    private final fcsu y;
    private final fcsu z;

    public aygy(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4, fcsu fcsuVar5, fcsu fcsuVar6, fcsu fcsuVar7, fcsu fcsuVar8, fcsu fcsuVar9, fcsu fcsuVar10, fcsu fcsuVar11, fcsu fcsuVar12, fcsu fcsuVar13, fcsu fcsuVar14, fcsu fcsuVar15, fcsu fcsuVar16, fcsu fcsuVar17, fcsu fcsuVar18, fcsu fcsuVar19, fcsu fcsuVar20, fcsu fcsuVar21, fcsu fcsuVar22, fcsu fcsuVar23, fcsu fcsuVar24, fcsu fcsuVar25, fcsu fcsuVar26, fcsu fcsuVar27, fcsu fcsuVar28, fcsu fcsuVar29, fcsu fcsuVar30, fcsu fcsuVar31, fcsu fcsuVar32, fcsu fcsuVar33, fcsu fcsuVar34, fcsu fcsuVar35, fcsu fcsuVar36, fcsu fcsuVar37, fcsu fcsuVar38, fcsu fcsuVar39, fcsu fcsuVar40, fcsu fcsuVar41, fcsu fcsuVar42, fcsu fcsuVar43, fcsu fcsuVar44, fcsu fcsuVar45, fcsu fcsuVar46, fcsu fcsuVar47, fcsu fcsuVar48, fcsu fcsuVar49, fcsu fcsuVar50, fcsu fcsuVar51, fcsu fcsuVar52, fcsu fcsuVar53, fcsu fcsuVar54, fcsu fcsuVar55, fcsu fcsuVar56) {
        fcsuVar.getClass();
        this.a = fcsuVar;
        fcsuVar2.getClass();
        this.b = fcsuVar2;
        fcsuVar3.getClass();
        this.c = fcsuVar3;
        fcsuVar4.getClass();
        this.d = fcsuVar4;
        fcsuVar5.getClass();
        this.e = fcsuVar5;
        fcsuVar6.getClass();
        this.f = fcsuVar6;
        fcsuVar7.getClass();
        this.g = fcsuVar7;
        fcsuVar8.getClass();
        this.h = fcsuVar8;
        this.i = fcsuVar9;
        fcsuVar10.getClass();
        this.j = fcsuVar10;
        fcsuVar11.getClass();
        this.k = fcsuVar11;
        fcsuVar12.getClass();
        this.l = fcsuVar12;
        fcsuVar13.getClass();
        this.m = fcsuVar13;
        fcsuVar14.getClass();
        this.n = fcsuVar14;
        fcsuVar15.getClass();
        this.o = fcsuVar15;
        fcsuVar16.getClass();
        this.p = fcsuVar16;
        fcsuVar17.getClass();
        this.q = fcsuVar17;
        this.r = fcsuVar18;
        fcsuVar19.getClass();
        this.s = fcsuVar19;
        fcsuVar20.getClass();
        this.t = fcsuVar20;
        fcsuVar21.getClass();
        this.u = fcsuVar21;
        fcsuVar22.getClass();
        this.v = fcsuVar22;
        fcsuVar23.getClass();
        this.w = fcsuVar23;
        fcsuVar24.getClass();
        this.x = fcsuVar24;
        fcsuVar25.getClass();
        this.y = fcsuVar25;
        fcsuVar26.getClass();
        this.z = fcsuVar26;
        fcsuVar27.getClass();
        this.A = fcsuVar27;
        fcsuVar28.getClass();
        fcsuVar29.getClass();
        this.B = fcsuVar29;
        fcsuVar30.getClass();
        this.C = fcsuVar30;
        fcsuVar31.getClass();
        this.D = fcsuVar31;
        fcsuVar32.getClass();
        this.E = fcsuVar32;
        fcsuVar33.getClass();
        this.F = fcsuVar33;
        fcsuVar34.getClass();
        this.G = fcsuVar34;
        fcsuVar35.getClass();
        this.H = fcsuVar35;
        fcsuVar36.getClass();
        this.I = fcsuVar36;
        fcsuVar37.getClass();
        this.J = fcsuVar37;
        fcsuVar38.getClass();
        this.K = fcsuVar38;
        fcsuVar39.getClass();
        this.L = fcsuVar39;
        fcsuVar40.getClass();
        this.M = fcsuVar40;
        fcsuVar41.getClass();
        this.N = fcsuVar41;
        fcsuVar42.getClass();
        this.O = fcsuVar42;
        fcsuVar43.getClass();
        this.P = fcsuVar43;
        fcsuVar44.getClass();
        this.Q = fcsuVar44;
        fcsuVar45.getClass();
        this.R = fcsuVar45;
        fcsuVar46.getClass();
        this.S = fcsuVar46;
        fcsuVar47.getClass();
        this.T = fcsuVar47;
        fcsuVar48.getClass();
        this.U = fcsuVar48;
        fcsuVar49.getClass();
        this.V = fcsuVar49;
        fcsuVar50.getClass();
        this.W = fcsuVar50;
        fcsuVar51.getClass();
        this.X = fcsuVar51;
        fcsuVar52.getClass();
        this.Y = fcsuVar52;
        fcsuVar53.getClass();
        this.Z = fcsuVar53;
        fcsuVar54.getClass();
        this.aa = fcsuVar54;
        fcsuVar55.getClass();
        this.ab = fcsuVar55;
        fcsuVar56.getClass();
        this.ac = fcsuVar56;
    }

    @Override // defpackage.ayql
    public final /* bridge */ /* synthetic */ Action a() {
        Context context = (Context) this.a.b();
        context.getClass();
        cogw cogwVar = (cogw) this.i.b();
        cogwVar.getClass();
        eosc eoscVar = (eosc) this.r.b();
        eoscVar.getClass();
        fcsu fcsuVar = this.s;
        fcsu fcsuVar2 = this.t;
        fcsu fcsuVar3 = this.u;
        fcsu fcsuVar4 = this.v;
        fcsu fcsuVar5 = this.w;
        fcsu fcsuVar6 = this.x;
        fcsu fcsuVar7 = this.y;
        fcsu fcsuVar8 = this.z;
        fcsu fcsuVar9 = this.A;
        fcsu fcsuVar10 = this.B;
        fcsu fcsuVar11 = this.C;
        fcsu fcsuVar12 = this.D;
        fcsu fcsuVar13 = this.E;
        fcsu fcsuVar14 = this.F;
        fcsu fcsuVar15 = this.G;
        fcsu fcsuVar16 = this.H;
        fcsu fcsuVar17 = this.I;
        fcsu fcsuVar18 = this.J;
        fcsu fcsuVar19 = this.K;
        fcsu fcsuVar20 = this.L;
        fcsu fcsuVar21 = this.M;
        fcsu fcsuVar22 = this.N;
        fcsu fcsuVar23 = this.O;
        fcsu fcsuVar24 = this.P;
        fcsu fcsuVar25 = this.Q;
        fcsu fcsuVar26 = this.R;
        fcsu fcsuVar27 = this.S;
        fcsu fcsuVar28 = this.T;
        fcsu fcsuVar29 = this.U;
        fcsu fcsuVar30 = this.V;
        fcsu fcsuVar31 = this.W;
        fcsu fcsuVar32 = this.X;
        fcsu fcsuVar33 = this.Y;
        fcsu fcsuVar34 = this.Z;
        fcsu fcsuVar35 = this.aa;
        fcsu fcsuVar36 = this.ab;
        fcsu fcsuVar37 = this.ac;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, cogwVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, eoscVar, fcsuVar, fcsuVar2, fcsuVar3, fcsuVar4, fcsuVar5, fcsuVar6, fcsuVar7, fcsuVar8, fcsuVar9, fcsuVar10, fcsuVar11, fcsuVar12, fcsuVar13, fcsuVar14, fcsuVar15, fcsuVar16, fcsuVar17, fcsuVar18, fcsuVar19, fcsuVar20, fcsuVar21, fcsuVar22, fcsuVar23, fcsuVar24, fcsuVar25, fcsuVar26, fcsuVar27, fcsuVar28, fcsuVar29, fcsuVar30, fcsuVar31, fcsuVar32, fcsuVar33, fcsuVar34, fcsuVar35, fcsuVar36, fcsuVar37);
    }

    @Override // defpackage.ayms
    public final /* bridge */ /* synthetic */ Action c(Parcel parcel) {
        Context context = (Context) this.a.b();
        context.getClass();
        cogw cogwVar = (cogw) this.i.b();
        cogwVar.getClass();
        eosc eoscVar = (eosc) this.r.b();
        eoscVar.getClass();
        parcel.getClass();
        fcsu fcsuVar = this.aa;
        fcsu fcsuVar2 = this.ab;
        fcsu fcsuVar3 = this.ac;
        fcsu fcsuVar4 = this.s;
        fcsu fcsuVar5 = this.t;
        fcsu fcsuVar6 = this.u;
        fcsu fcsuVar7 = this.v;
        fcsu fcsuVar8 = this.w;
        fcsu fcsuVar9 = this.x;
        fcsu fcsuVar10 = this.y;
        fcsu fcsuVar11 = this.z;
        fcsu fcsuVar12 = this.A;
        fcsu fcsuVar13 = this.B;
        fcsu fcsuVar14 = this.C;
        fcsu fcsuVar15 = this.D;
        fcsu fcsuVar16 = this.E;
        fcsu fcsuVar17 = this.F;
        fcsu fcsuVar18 = this.G;
        fcsu fcsuVar19 = this.H;
        fcsu fcsuVar20 = this.I;
        fcsu fcsuVar21 = this.J;
        fcsu fcsuVar22 = this.L;
        fcsu fcsuVar23 = this.M;
        fcsu fcsuVar24 = this.K;
        fcsu fcsuVar25 = this.N;
        fcsu fcsuVar26 = this.O;
        fcsu fcsuVar27 = this.P;
        fcsu fcsuVar28 = this.Q;
        fcsu fcsuVar29 = this.R;
        fcsu fcsuVar30 = this.S;
        fcsu fcsuVar31 = this.T;
        fcsu fcsuVar32 = this.U;
        fcsu fcsuVar33 = this.V;
        fcsu fcsuVar34 = this.W;
        fcsu fcsuVar35 = this.X;
        fcsu fcsuVar36 = this.Y;
        fcsu fcsuVar37 = this.Z;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, cogwVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, eoscVar, fcsuVar4, fcsuVar5, fcsuVar6, fcsuVar7, fcsuVar8, fcsuVar9, fcsuVar10, fcsuVar11, fcsuVar12, fcsuVar13, fcsuVar14, fcsuVar15, fcsuVar16, fcsuVar17, fcsuVar18, fcsuVar19, fcsuVar20, fcsuVar21, fcsuVar22, fcsuVar23, fcsuVar24, fcsuVar25, fcsuVar26, fcsuVar27, fcsuVar28, fcsuVar29, fcsuVar30, fcsuVar31, fcsuVar32, fcsuVar33, fcsuVar34, fcsuVar35, fcsuVar36, fcsuVar37, parcel, fcsuVar, fcsuVar2, fcsuVar3);
    }
}
