package defpackage;

import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.MessageIdType;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes7.dex */
public final class bfsd extends dqpg {
    public final MessageIdType A;
    public final MessageIdType B;
    public final MessageIdType a;
    public final ConversationIdType b;
    public final basd c;
    public final bvdz d;
    public final String e;
    public final basd f;
    public final cpyi g;
    public final cgrd h;
    public final bvdn i;
    public final bvec j;
    public final MessageIdType k;
    public final bvdt l;
    public final ConversationIdType m;
    public final bvdg n;
    public final bvdg o;
    public final bvef p;
    public final bvdy q;
    public final bvdq r;
    public final bvdz s;
    public final chpq t;
    public final chpq u;
    public final MessageIdType v;
    public final MessageIdType w;
    public final MessageIdType x;
    public final Optional y;
    public final MessageIdType z;

    public bfsd() {
        super(bgvl.d());
        MessageIdType messageIdType = bary.a;
        this.a = messageIdType;
        ConversationIdType conversationIdType = barn.a;
        this.b = conversationIdType;
        basd basdVar = basd.a;
        this.c = basdVar;
        bvdz bvdzVar = bvdz.VERIFICATION_NA;
        this.d = bvdzVar;
        this.e = "";
        this.f = basdVar;
        this.g = cpyi.UNKNOWN;
        this.h = cgrd.c;
        this.i = bvdn.UNKNOWN;
        this.j = bvec.UNKNOWN;
        this.k = messageIdType;
        this.l = bvdt.SUCCEEDED;
        this.m = conversationIdType;
        this.n = new bvdg(-1);
        this.o = new bvdg(-1);
        this.p = bvef.UNKNOWN;
        this.q = bvdy.NONE;
        this.r = bvdq.DEFAULT_NO_VERDICT;
        this.s = bvdzVar;
        chpq chpqVar = chpq.PROFILE_CONTACT_SOURCE;
        this.t = chpqVar;
        this.u = chpqVar;
        this.v = messageIdType;
        this.w = messageIdType;
        this.x = messageIdType;
        this.y = basb.b(-1L);
        this.z = messageIdType;
        this.A = messageIdType;
        this.B = messageIdType;
    }

    public final bfsb a() {
        bfsc bfscVar = new bfsc();
        bfscVar.aD(aB());
        bfscVar.a = this.a;
        bfscVar.b = this.b;
        bfscVar.c = null;
        bfscVar.d = 0L;
        bfscVar.e = 0L;
        bfscVar.f = 0;
        bfscVar.g = 0;
        bfscVar.h = 0;
        bfscVar.i = false;
        bfscVar.j = false;
        bfscVar.k = null;
        bfscVar.l = 0;
        bfscVar.m = 0L;
        bfscVar.n = null;
        bfscVar.o = 0L;
        bfscVar.p = 0L;
        bfscVar.q = null;
        bfscVar.r = 0;
        bfscVar.s = null;
        bfscVar.t = this.c;
        bfscVar.u = 0;
        bfscVar.v = this.d;
        bfscVar.w = false;
        bfscVar.x = -1L;
        bfscVar.y = -1;
        bfscVar.z = null;
        bfscVar.A = null;
        bfscVar.B = this.e;
        bfscVar.C = 0L;
        bfscVar.D = this.f;
        bfscVar.E = -2;
        bfscVar.F = this.g;
        bfscVar.G = this.h;
        bfscVar.H = this.i;
        bfscVar.I = null;
        bfscVar.J = this.j;
        bfscVar.K = null;
        bfscVar.L = null;
        bfscVar.M = this.k;
        bfscVar.N = null;
        bfscVar.O = null;
        bfscVar.P = null;
        bfscVar.Q = null;
        bfscVar.R = null;
        bfscVar.S = null;
        bfscVar.T = null;
        bfscVar.U = null;
        bfscVar.V = 0L;
        bfscVar.W = null;
        bfscVar.X = null;
        bfscVar.Y = this.l;
        bfscVar.Z = null;
        bfscVar.aa = this.m;
        bfscVar.ab = this.n;
        bfscVar.ac = this.o;
        bfscVar.ad = -1L;
        bfscVar.ae = 0.0d;
        bfscVar.af = 0.0d;
        bfscVar.ag = null;
        bfscVar.ah = null;
        bfscVar.ai = null;
        bfscVar.aj = null;
        bfscVar.ak = null;
        bfscVar.al = null;
        bfscVar.am = null;
        bfscVar.an = null;
        bfscVar.ao = null;
        bfscVar.ap = null;
        bfscVar.aq = null;
        bfscVar.ar = null;
        bfscVar.as = null;
        bfscVar.at = null;
        bfscVar.au = null;
        bfscVar.av = null;
        bfscVar.aw = null;
        bfscVar.ax = null;
        bfscVar.ay = null;
        bfscVar.az = null;
        bfscVar.aA = null;
        bfscVar.aB = null;
        bfscVar.aC = false;
        bfscVar.aD = 0L;
        bfscVar.aE = null;
        bfscVar.aF = null;
        bfscVar.aG = null;
        bfscVar.aH = this.p;
        bfscVar.aI = null;
        bfscVar.aJ = this.q;
        bfscVar.aK = this.r;
        bfscVar.aL = false;
        bfscVar.aM = null;
        bfscVar.aO = null;
        bfscVar.aP = null;
        bfscVar.aQ = null;
        bfscVar.aR = null;
        bfscVar.aS = null;
        bfscVar.aT = null;
        bfscVar.aU = -1L;
        bfscVar.aV = null;
        bfscVar.aW = -1;
        bfscVar.aX = 0;
        bfscVar.aY = 0;
        bfscVar.aZ = false;
        bfscVar.ba = 0;
        bfscVar.bb = false;
        bfscVar.bc = this.s;
        bfscVar.bd = -1L;
        bfscVar.be = this.t;
        bfscVar.bf = this.u;
        bfscVar.bh = null;
        bfscVar.bi = this.v;
        bfscVar.bj = null;
        bfscVar.bk = null;
        bfscVar.bl = null;
        bfscVar.bm = null;
        bfscVar.bn = null;
        bfscVar.bp = this.w;
        bfscVar.bq = null;
        bfscVar.br = null;
        bfscVar.bs = null;
        bfscVar.bt = null;
        bfscVar.bu = null;
        bfscVar.bv = null;
        bfscVar.bw = null;
        bfscVar.bx = null;
        bfscVar.by = null;
        bfscVar.bz = null;
        bfscVar.bA = null;
        bfscVar.bB = null;
        bfscVar.bD = this.x;
        bfscVar.bE = null;
        bfscVar.bF = 0L;
        bfscVar.bG = null;
        bfscVar.bH = null;
        bfscVar.bI = null;
        bfscVar.bJ = null;
        bfscVar.bK = null;
        bfscVar.bL = false;
        bfscVar.bM = false;
        bfscVar.bO = null;
        bfscVar.bP = null;
        bfscVar.bQ = null;
        bfscVar.bS = null;
        bfscVar.bT = 0;
        bfscVar.bU = false;
        bfscVar.bV = null;
        bfscVar.bW = null;
        bfscVar.bX = true;
        bfscVar.bY = this.y;
        bfscVar.bZ = null;
        bfscVar.ca = null;
        bfscVar.cb = this.z;
        bfscVar.cc = null;
        bfscVar.cd = null;
        bfscVar.ce = null;
        bfscVar.cf = null;
        bfscVar.cg = null;
        bfscVar.ch = null;
        bfscVar.cj = this.A;
        bfscVar.ck = this.B;
        bfscVar.cl = 0L;
        bfscVar.cm = null;
        bfscVar.cn = 0;
        bfscVar.co = null;
        bfscVar.cp = null;
        bfscVar.cq = null;
        bfscVar.cr = null;
        bfscVar.cs = null;
        bfscVar.ct = null;
        bfscVar.cu = null;
        bfscVar.cv = null;
        bfscVar.cw = null;
        bfscVar.cx = null;
        bfscVar.cy = null;
        bfscVar.cz = null;
        bfscVar.cA = 0L;
        bfscVar.cB = null;
        bfscVar.cC = null;
        bfscVar.cD = false;
        bfscVar.cF = null;
        bfscVar.cG = null;
        bfscVar.i();
        bfscVar.cM = aC();
        return bfscVar;
    }
}
