package defpackage;

/* compiled from: PG */
/* loaded from: classes7.dex */
public enum bmqz {
    INITIAL_RESTORE_NON_RETRIABLE,
    INITIAL_RESTORE_MAX_RETRIED,
    BACKUP_CREATE,
    BACKUP_UPDATE,
    BACKUP_DELETE,
    BACKUP_UPDATE_FREQUENT,
    BACKUP_UPDATE_RARE,
    BACKUP_UPDATE_ADDITIONAL_FIELDS,
    BACKUP_UPDATE_URI,
    BACKUP_UNKNOWN_OPERATION,
    INITIAL_BACKUP_CREATE,
    INCREMENTAL_BACKUP_CREATE
}
