package defpackage;

/* compiled from: PG */
/* loaded from: classes7.dex */
public enum cdpi {
    LIGHTER_CONVERSATION_STATUS_DEFAULT,
    LIGHTER_CONVERSATION_STATUS_PENDING_TO_DELETE,
    LIGHTER_CONVERSATION_STATUS_FAILED_TO_DELETE,
    LIGHTER_CONVERSATION_STATUS_PENDING_TO_BLOCK,
    LIGHTER_CONVERSATION_STATUS_FAILED_TO_BLOCK
}
