package defpackage;

import androidx.car.app.hardware.info.EnergyProfile;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class cptt {
    public static final ekgp a;
    public static final ekcb b;
    public static final ekcb c;
    public static final ekcb d;
    public static final ekcb e;
    public static final ekcb f;
    public static final ekcb g;
    public static final ekcb h;
    public static final ekcb i;
    public static final ekcb j;
    public static final ekcb k;
    private static final ekgp l;

    static {
        ekgi ekgiVar = new ekgi();
        ekgiVar.i(eplg.STATUS_UNKNOWN, 0);
        ekgiVar.i(eplg.OUTGOING_COMPLETE, 1);
        ekgiVar.i(eplg.OUTGOING_DELIVERED, 2);
        ekgiVar.i(eplg.OUTGOING_DISPLAYED, 11);
        ekgiVar.i(eplg.OUTGOING_DRAFT, 3);
        ekgiVar.i(eplg.OUTGOING_VALIDATING, 20);
        ekgiVar.i(eplg.OUTGOING_SEND_AFTER_PROCESSING, 8);
        ekgiVar.i(eplg.OUTGOING_YET_TO_SEND, 8);
        ekgiVar.i(eplg.OUTGOING_SENDING, 8);
        ekgiVar.i(eplg.OUTGOING_RESENDING, 8);
        ekgiVar.i(eplg.OUTGOING_AWAITING_RETRY, 8);
        ekgiVar.i(eplg.OUTGOING_FAILED_GENERIC, 8);
        ekgiVar.i(eplg.OUTGOING_FAILED_EMERGENCY_NUMBER, 9);
        ekgiVar.i(eplg.OUTGOING_CANCELED, 12);
        ekgiVar.i(eplg.OUTGOING_FAILED_TOO_LARGE, 13);
        ekgiVar.i(eplg.OUTGOING_NOT_DELIVERED_YET, 14);
        ekgiVar.i(eplg.OUTGOING_REVOCATION_PENDING, 15);
        ekgiVar.i(eplg.OUTGOING_SCHEDULED, 16);
        ekgiVar.i(eplg.OUTGOING_FAILED_RECIPIENT_LOST_RCS, 17);
        ekgiVar.i(eplg.OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION, 21);
        ekgiVar.i(eplg.INCOMING_COMPLETE, 100);
        ekgiVar.i(eplg.OUTGOING_FAILED_NO_RETRY_NO_FALLBACK, 18);
        ekgiVar.i(eplg.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT, 19);
        ekgiVar.i(eplg.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY, 22);
        ekgiVar.i(eplg.OUTGOING_FAILED_RECIPIENT_NEGATIVE_DELIVERY, 24);
        ekgiVar.i(eplg.MESSAGE_STATUS_OUTGOING_FAILED_EMERGENCY_PROTOCOL_DETERMINATION_MESSAGE, 25);
        eplg eplgVar = eplg.INCOMING_YET_TO_MANUAL_DOWNLOAD;
        Integer numValueOf = Integer.valueOf(EnergyProfile.EVCONNECTOR_TYPE_OTHER);
        ekgiVar.i(eplgVar, numValueOf);
        ekgiVar.i(eplg.INCOMING_RETRYING_MANUAL_DOWNLOAD, 102);
        ekgiVar.i(eplg.INCOMING_MANUAL_DOWNLOADING, 103);
        ekgiVar.i(eplg.INCOMING_RETRYING_AUTO_DOWNLOAD, 104);
        ekgiVar.i(eplg.INCOMING_AUTO_DOWNLOADING, 105);
        ekgiVar.i(eplg.INCOMING_DOWNLOAD_FAILED, 106);
        ekgiVar.i(eplg.INCOMING_EXPIRED_OR_NOT_AVAILABLE, 107);
        ekgiVar.i(eplg.INCOMING_DELIVERED, 108);
        ekgiVar.i(eplg.INCOMING_DISPLAYED, 109);
        ekgiVar.i(eplg.INCOMING_DOWNLOAD_CANCELED, 110);
        ekgiVar.i(eplg.INCOMING_DOWNLOAD_FAILED_TOO_LARGE, 111);
        ekgiVar.i(eplg.INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA, 112);
        ekgiVar.i(eplg.INCOMING_FAILED_TO_DECRYPT, 113);
        ekgiVar.i(eplg.INCOMING_DECRYPTION_ABORTED, 114);
        ekgiVar.i(eplg.INCOMING_AWAITING_AUTO_DOWNLOAD, 115);
        ekgiVar.i(eplg.INCOMING_UNKNOWN_CONTENT_TYPE, 116);
        eplg eplgVar2 = eplg.TOMBSTONE_PARTICIPANT_JOINED;
        Integer numValueOf2 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_FAILED);
        ekgiVar.i(eplgVar2, numValueOf2);
        eplg eplgVar3 = eplg.TOMBSTONE_PARTICIPANT_LEFT;
        Integer numValueOf3 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_TIMEOUT);
        ekgiVar.i(eplgVar3, numValueOf3);
        eplg eplgVar4 = eplg.TOMBSTONE_SELF_LEFT;
        Integer numValueOf4 = Integer.valueOf(BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED);
        ekgiVar.i(eplgVar4, numValueOf4);
        eplg eplgVar5 = eplg.TOMBSTONE_RCS_GROUP_CREATED;
        Integer numValueOf5 = Integer.valueOf(BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED);
        ekgiVar.i(eplgVar5, numValueOf5);
        ekgiVar.i(eplg.TOMBSTONE_MMS_GROUP_CREATED, 204);
        ekgiVar.i(eplg.TOMBSTONE_SMS_BROADCAST_CREATED, 205);
        ekgiVar.i(eplg.TOMBSTONE_ONE_ON_ONE_SMS_CREATED, 206);
        ekgiVar.i(eplg.TOMBSTONE_ONE_ON_ONE_RCS_CREATED, 207);
        ekgiVar.i(eplg.TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED, 213);
        ekgiVar.i(eplg.TOMBSTONE_SWITCH_TO_GROUP_MMS, 208);
        ekgiVar.i(eplg.TOMBSTONE_SWITCH_TO_BROADCAST_SMS, 209);
        ekgiVar.i(eplg.TOMBSTONE_SHOW_LINK_PREVIEWS, 210);
        ekgiVar.i(eplg.TOMBSTONE_GROUP_RENAMED_LOCAL, 211);
        ekgiVar.i(eplg.TOMBSTONE_GROUP_RENAMED_GLOBAL, 217);
        ekgiVar.i(eplg.TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL, 218);
        ekgiVar.i(eplg.TOMBSTONE_VERIFIED_SMS_APPLICABLE, 212);
        ekgiVar.i(eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT, 214);
        ekgiVar.i(eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_RCS, 215);
        ekgiVar.i(eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS, 216);
        ekgiVar.i(eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO, 219);
        ekgiVar.i(eplg.TOMBSTONE_SELF_REMOVED_FROM_GROUP, 220);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP, 221);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED, 222);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED, 223);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED, 224);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED, 225);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO, 226);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT, 227);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT, 228);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED, 229);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP, 230);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP, 231);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE, 232);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE, 233);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS, 234);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE, 235);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT, 236);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE, 237);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS, 238);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION, 239);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH, 240);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE, 241);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE, 242);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE, 243);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL, 244);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE, 245);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED, 246);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED, 247);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED, 248);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED, 249);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END, 250);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE, 251);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS, 252);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE, 253);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE, 254);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT, 255);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT, 256);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED, 257);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED, 258);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED, 259);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL, 260);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL, 261);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR, 262);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR, 263);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED, 264);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK, 266);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK, 267);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT_NO_LINK, 269);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT_NO_LINK, 270);
        ekgiVar.i(eplg.OUTGOING_DELETED, 23);
        ekgiVar.i(eplg.INCOMING_DELETED, 117);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE, 265);
        ekgiVar.i(eplg.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_QUESTIONNAIRE, 268);
        a = ekgiVar.c();
        ekgi ekgiVar2 = new ekgi();
        ekgiVar2.i(0, eplg.STATUS_UNKNOWN);
        ekgiVar2.i(1, eplg.OUTGOING_COMPLETE);
        ekgiVar2.i(2, eplg.OUTGOING_DELIVERED);
        ekgiVar2.i(11, eplg.OUTGOING_DISPLAYED);
        ekgiVar2.i(3, eplg.OUTGOING_DRAFT);
        ekgiVar2.i(20, eplg.OUTGOING_VALIDATING);
        ekgiVar2.i(10, eplg.OUTGOING_SEND_AFTER_PROCESSING);
        ekgiVar2.i(4, eplg.OUTGOING_YET_TO_SEND);
        ekgiVar2.i(5, eplg.OUTGOING_SENDING);
        ekgiVar2.i(6, eplg.OUTGOING_RESENDING);
        ekgiVar2.i(7, eplg.OUTGOING_AWAITING_RETRY);
        ekgiVar2.i(8, eplg.OUTGOING_FAILED_GENERIC);
        ekgiVar2.i(9, eplg.OUTGOING_FAILED_EMERGENCY_NUMBER);
        ekgiVar2.i(12, eplg.OUTGOING_CANCELED);
        ekgiVar2.i(13, eplg.OUTGOING_FAILED_TOO_LARGE);
        ekgiVar2.i(14, eplg.OUTGOING_NOT_DELIVERED_YET);
        ekgiVar2.i(15, eplg.OUTGOING_REVOCATION_PENDING);
        ekgiVar2.i(16, eplg.OUTGOING_SCHEDULED);
        ekgiVar2.i(17, eplg.OUTGOING_FAILED_RECIPIENT_LOST_RCS);
        ekgiVar2.i(21, eplg.OUTGOING_FAILED_RECIPIENT_LOST_ENCRYPTION);
        ekgiVar2.i(100, eplg.INCOMING_COMPLETE);
        ekgiVar2.i(18, eplg.OUTGOING_FAILED_NO_RETRY_NO_FALLBACK);
        ekgiVar2.i(19, eplg.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT);
        ekgiVar2.i(22, eplg.OUTGOING_FAILED_RECIPIENT_DID_NOT_DECRYPT_NO_MORE_RETRY);
        ekgiVar2.i(24, eplg.OUTGOING_FAILED_RECIPIENT_NEGATIVE_DELIVERY);
        ekgiVar2.i(25, eplg.MESSAGE_STATUS_OUTGOING_FAILED_EMERGENCY_PROTOCOL_DETERMINATION_MESSAGE);
        ekgiVar2.i(numValueOf, eplg.INCOMING_YET_TO_MANUAL_DOWNLOAD);
        ekgiVar2.i(102, eplg.INCOMING_RETRYING_MANUAL_DOWNLOAD);
        ekgiVar2.i(103, eplg.INCOMING_MANUAL_DOWNLOADING);
        ekgiVar2.i(104, eplg.INCOMING_RETRYING_AUTO_DOWNLOAD);
        ekgiVar2.i(105, eplg.INCOMING_AUTO_DOWNLOADING);
        ekgiVar2.i(106, eplg.INCOMING_DOWNLOAD_FAILED);
        ekgiVar2.i(107, eplg.INCOMING_EXPIRED_OR_NOT_AVAILABLE);
        ekgiVar2.i(108, eplg.INCOMING_DELIVERED);
        ekgiVar2.i(109, eplg.INCOMING_DISPLAYED);
        ekgiVar2.i(110, eplg.INCOMING_DOWNLOAD_CANCELED);
        ekgiVar2.i(111, eplg.INCOMING_DOWNLOAD_FAILED_TOO_LARGE);
        ekgiVar2.i(112, eplg.INCOMING_DOWNLOAD_FAILED_SIM_HAS_NO_DATA);
        ekgiVar2.i(113, eplg.INCOMING_FAILED_TO_DECRYPT);
        ekgiVar2.i(114, eplg.INCOMING_DECRYPTION_ABORTED);
        ekgiVar2.i(115, eplg.INCOMING_AWAITING_AUTO_DOWNLOAD);
        ekgiVar2.i(116, eplg.INCOMING_UNKNOWN_CONTENT_TYPE);
        ekgiVar2.i(numValueOf2, eplg.TOMBSTONE_PARTICIPANT_JOINED);
        ekgiVar2.i(numValueOf3, eplg.TOMBSTONE_PARTICIPANT_LEFT);
        ekgiVar2.i(numValueOf4, eplg.TOMBSTONE_SELF_LEFT);
        ekgiVar2.i(numValueOf5, eplg.TOMBSTONE_RCS_GROUP_CREATED);
        ekgiVar2.i(204, eplg.TOMBSTONE_MMS_GROUP_CREATED);
        ekgiVar2.i(205, eplg.TOMBSTONE_SMS_BROADCAST_CREATED);
        ekgiVar2.i(206, eplg.TOMBSTONE_ONE_ON_ONE_SMS_CREATED);
        ekgiVar2.i(207, eplg.TOMBSTONE_ONE_ON_ONE_RCS_CREATED);
        ekgiVar2.i(213, eplg.TOMBSTONE_ENCRYPTED_ONE_ON_ONE_RCS_CREATED);
        ekgiVar2.i(208, eplg.TOMBSTONE_SWITCH_TO_GROUP_MMS);
        ekgiVar2.i(209, eplg.TOMBSTONE_SWITCH_TO_BROADCAST_SMS);
        ekgiVar2.i(210, eplg.TOMBSTONE_SHOW_LINK_PREVIEWS);
        ekgiVar2.i(211, eplg.TOMBSTONE_GROUP_RENAMED_LOCAL);
        ekgiVar2.i(217, eplg.TOMBSTONE_GROUP_RENAMED_GLOBAL);
        ekgiVar2.i(218, eplg.TOMBSTONE_GROUP_NAME_CLEARED_GLOBAL);
        ekgiVar2.i(212, eplg.TOMBSTONE_VERIFIED_SMS_APPLICABLE);
        ekgiVar2.i(214, eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_TEXT);
        ekgiVar2.i(215, eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_RCS);
        ekgiVar2.i(216, eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS);
        ekgiVar2.i(219, eplg.TOMBSTONE_PROTOCOL_SWITCH_TO_ENCRYPTED_RCS_INFO);
        ekgiVar2.i(220, eplg.TOMBSTONE_SELF_REMOVED_FROM_GROUP);
        ekgiVar2.i(221, eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_GROUP);
        ekgiVar2.i(222, eplg.MESSAGE_STATUS_TOMBSTONE_SMS_NORM_PARTICIPANT_UPGRADED);
        ekgiVar2.i(223, eplg.MESSAGE_STATUS_TOMBSTONE_RCS_NORM_PARTICIPANT_UPGRADED);
        ekgiVar2.i(224, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_RCS_NORM_PARTICIPANT_UPGRADED);
        ekgiVar2.i(225, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED);
        ekgiVar2.i(226, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_JOINED_INFO);
        ekgiVar2.i(227, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_PARTICIPANT_LEFT);
        ekgiVar2.i(228, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_SELF_LEFT);
        ekgiVar2.i(229, eplg.MESSAGE_STATUS_TOMBSTONE_ENCRYPTED_GROUP_CREATED);
        ekgiVar2.i(230, eplg.MESSAGE_STATUS_TOMBSTONE_SELF_REMOVED_FROM_ENCRYPTED_GROUP);
        ekgiVar2.i(231, eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_REMOVED_FROM_ENCRYPTED_GROUP);
        ekgiVar2.i(232, eplg.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_SHORTCUT_STAR_TOOLSTONE);
        ekgiVar2.i(233, eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_RCS_TO_E2EE);
        ekgiVar2.i(234, eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_RCS);
        ekgiVar2.i(235, eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_TEXT_TO_E2EE);
        ekgiVar2.i(236, eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_TEXT);
        ekgiVar2.i(237, eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_RCS_TO_E2EE);
        ekgiVar2.i(238, eplg.MESSAGE_STATUS_TOMBSTONE_PROTOCOL_SWITCH_E2EE_TO_RCS);
        ekgiVar2.i(239, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_EDUCATION);
        ekgiVar2.i(240, eplg.MESSAGE_STATUS_TOMBSTONE_RBM_SIM_SWITCH);
        ekgiVar2.i(241, eplg.MESSAGE_STATUS_TOMBSTONE_RBM_PRIVACY_NOTICE);
        ekgiVar2.i(242, eplg.MESSAGE_STATUS_TOMBSTONE_PENPAL_CONVERSATION_NOTICE);
        ekgiVar2.i(243, eplg.MESSAGE_STATUS_TOMBSTONE_MEET_OTHER_PARTICIPANT_REACHABLE);
        ekgiVar2.i(244, eplg.MESSAGE_STATUS_TOMBSTONE_MISSED_VIDEO_CALL);
        ekgiVar2.i(245, eplg.MESSAGE_STATUS_TOMBSTONE_PARTICIPANT_THEME_CHANGE);
        ekgiVar2.i(246, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_STILL_NEEDED);
        ekgiVar2.i(247, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_SUCCESS_HELP_NO_LONGER_NEEDED);
        ekgiVar2.i(248, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_STILL_NEEDED);
        ekgiVar2.i(249, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_FAILURE_HELP_NO_LONGER_NEEDED);
        ekgiVar2.i(250, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_END_OF_EMERGENCY_UNEXPECTED_END);
        ekgiVar2.i(251, eplg.MESSAGE_STATUS_TOMBSTONE_SATELLITE_MESSAGING_TOOLSTONE);
        ekgiVar2.i(252, eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_PROTOCOL_SWITCH_E2EE_TO_MMS);
        ekgiVar2.i(253, eplg.MESSAGE_STATUS_TOMBSTONE_PENPAL_PROACTIVE_MESSAGE_NOTICE);
        ekgiVar2.i(254, eplg.MESSAGE_STATUS_TOMBSTONE_SUGGESTION_POSSIBLE_SCAM_TOOLSTONE);
        ekgiVar2.i(255, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT);
        ekgiVar2.i(256, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT);
        ekgiVar2.i(257, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED);
        ekgiVar2.i(258, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED);
        ekgiVar2.i(259, eplg.MESSAGE_STATUS_TOMBSTONE_ACTIVE_SELF_IDENTITY_CHANGED);
        ekgiVar2.i(260, eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CHANGED_GLOBAL);
        ekgiVar2.i(261, eplg.MESSAGE_STATUS_TOMBSTONE_GROUP_ICON_CLEARED_GLOBAL);
        ekgiVar2.i(262, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_ERROR);
        ekgiVar2.i(263, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_ERROR);
        ekgiVar2.i(264, eplg.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_CONVERSATION_CREATED);
        ekgiVar2.i(266, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_CONFIRMED_NO_LINK);
        ekgiVar2.i(267, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_CONFIRMED_NO_LINK);
        ekgiVar2.i(269, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_UNSUBSCRIBE_SENT_NO_LINK);
        ekgiVar2.i(270, eplg.MESSAGE_STATUS_TOMBSTONE_CHATBOT_SUBSCRIBE_SENT_NO_LINK);
        ekgiVar2.i(23, eplg.OUTGOING_DELETED);
        ekgiVar2.i(117, eplg.INCOMING_DELETED);
        ekgiVar2.i(265, eplg.MESSAGE_STATUS_TOMBSTONE_SENSITIVE_CONTENT_WARNING_TOOLSTONE);
        ekgiVar2.i(268, eplg.MESSAGE_STATUS_TOMBSTONE_EMERGENCY_QUESTIONNAIRE);
        l = ekgiVar2.c();
        ekfi ekfiVar = new ekfi();
        ekfiVar.d(eplh.SMS, 0);
        ekfiVar.d(eplh.MMS, 1);
        ekfiVar.d(eplh.RCS, 3);
        ekfiVar.d(eplh.CLOUD_SYNC, 4);
        ekfiVar.d(eplh.MMS_PUSH_NOTIFICATION, 2);
        ekfiVar.d(eplh.TOMBSTONE, 5);
        ekfiVar.d(eplh.TYPE_UNKNOWN, -1);
        b = ekfiVar.c();
        ekfi ekfiVar2 = new ekfi();
        ekfiVar2.d(epjt.CONVERSATION_TYPE_GROUP_RCS, 2);
        ekfiVar2.d(epjt.CONVERSATION_TYPE_GROUP_XMS, 1);
        ekfiVar2.d(epjt.CONVERSATION_TYPE_ONE_ON_ONE, 0);
        c = ekfiVar2.c();
        ekfi ekfiVar3 = new ekfi();
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_INVITED, 1);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_JOINED, 0);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_LEFT, 2);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_DIFFERENT_CONFIG, 3);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_RECOVERED_FROM_TELEPHONY, 4);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_RCS_GROUP_CREATION_FAILED, 5);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_FORKED, 6);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_SETTING_UP_FOR_VANILLA_RCS, 7);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_RCS_GROUP_CREATION_IN_PROGRESS, 8);
        ekfiVar3.d(epjq.CONVERSATION_JOIN_STATE_SATELLITE_ENDED, 9);
        d = ekfiVar3.c();
        ekfi ekfiVar4 = new ekfi();
        ekfiVar4.d(epjr.CONVERSATION_SEND_MODE_AUTO, 0);
        ekfiVar4.d(epjr.CONVERSATION_SEND_MODE_XMS, 1);
        ekfiVar4.d(epjr.CONVERSATION_SEND_MODE_XMS_LATCH, 2);
        e = ekfiVar4.c();
        ekfi ekfiVar5 = new ekfi();
        ekfiVar5.d(epll.PRIORITY_LOW, 128);
        ekfiVar5.d(epll.PRIORITY_NORMAL, 129);
        ekfiVar5.d(epll.PRIORITY_HIGH, 130);
        ekfiVar5.d(epll.PRIORITY_UNKNOWN, 0);
        f = ekfiVar5.c();
        ekfi ekfiVar6 = new ekfi();
        ekfiVar6.d(epkx.UNENCRYPTED, 0);
        ekfiVar6.d(epkx.ENCRYPTED, 2);
        ekfiVar6.d(epkx.CAN_FALLBACK, 1);
        g = ekfiVar6.c();
        ekfi ekfiVar7 = new ekfi();
        ekfiVar7.d(epkn.ATTACHMENT_TYPE_UNKNOWN, "*/*");
        ekfiVar7.d(epkn.IMAGE_JPEG, "image/jpeg");
        ekfiVar7.d(epkn.IMAGE_JPG, "image/jpg");
        ekfiVar7.d(epkn.IMAGE_PNG, "image/png");
        ekfiVar7.d(epkn.IMAGE_GIF, "image/gif");
        ekfiVar7.d(epkn.IMAGE_WBMP, "image/vnd.wap.wbmp");
        ekfiVar7.d(epkn.IMAGE_WEBP, "image/webp");
        ekfiVar7.d(epkn.IMAGE_X_MS_BMP, "image/x-ms-bmp");
        ekfiVar7.d(epkn.IMAGE_HEIF, "image/heif");
        ekfiVar7.d(epkn.IMAGE_HEIC, "image/heic");
        ekfiVar7.d(epkn.VIDEO_MP4, "video/mp4");
        ekfiVar7.d(epkn.VIDEO_3G2, "video/3gpp2");
        ekfiVar7.d(epkn.VIDEO_3GPP, "video/3gpp");
        ekfiVar7.d(epkn.VIDEO_MKV, "video/x-matroska");
        ekfiVar7.d(epkn.VIDEO_WEBM, "video/webm");
        ekfiVar7.d(epkn.VIDEO_M4V, "video/m4v");
        ekfiVar7.d(epkn.VIDEO_MPEG4, "video/mpeg4");
        ekfiVar7.d(epkn.VIDEO_MPEG, "video/mpeg");
        ekfiVar7.d(epkn.VIDEO_3GP, "video/3gp");
        ekfiVar7.d(epkn.VIDEO_HEVC, "video/hevc");
        ekfiVar7.d(epkn.AUDIO_AAC, "audio/aac");
        ekfiVar7.d(epkn.AUDIO_AMR, "audio/amr");
        ekfiVar7.d(epkn.AUDIO_MP3, "audio/mp3");
        ekfiVar7.d(epkn.AUDIO_MPEG, "audio/mpeg");
        ekfiVar7.d(epkn.AUDIO_MPG, "audio/mpg");
        ekfiVar7.d(epkn.AUDIO_MP4, "audio/mp4");
        ekfiVar7.d(epkn.AUDIO_MP4_LATM, "audio/mp4-latm");
        ekfiVar7.d(epkn.AUDIO_3GPP, "audio/3gpp");
        ekfiVar7.d(epkn.AUDIO_OGG, "application/ogg");
        ekfiVar7.d(epkn.AUDIO_OGG2, "audio/ogg");
        ekfiVar7.d(epkn.TEXT_VCARD, "text/x-vCard");
        ekfiVar7.d(epkn.TEXT_VCARD_RECEIVE, "text/x-vcard");
        ekfiVar7.d(epkn.APP_PDF, "application/pdf");
        ekfiVar7.d(epkn.APP_TXT, "application/txt");
        ekfiVar7.d(epkn.APP_HTML, "application/html");
        ekfiVar7.d(epkn.APP_SMIL, "application/smil");
        h = ekfiVar7.c();
        ekfi ekfiVar8 = new ekfi();
        ekfiVar8.d(epks.SUGGESTION_TYPE_INVALID, -1);
        ekfiVar8.d(epks.SUGGESTION_TYPE_REPLY, 0);
        ekfiVar8.d(epks.SUGGESTION_TYPE_WEB, 1);
        ekfiVar8.d(epks.SUGGESTION_TYPE_WEBVIEW, 11);
        ekfiVar8.d(epks.SUGGESTION_TYPE_PHONE, 2);
        ekfiVar8.d(epks.SUGGESTION_TYPE_MAP, 3);
        ekfiVar8.d(epks.SUGGESTION_TYPE_CALENDAR, 4);
        ekfiVar8.d(epks.SUGGESTION_TYPE_SHARE_LOCATION, 5);
        ekfiVar8.d(epks.SUGGESTION_TYPE_COMPOSE_TEXT, 8);
        ekfiVar8.d(epks.SUGGESTION_TYPE_COMPOSE_AUDIO, 9);
        ekfiVar8.d(epks.SUGGESTION_TYPE_COMPOSE_VIDEO, 10);
        i = ekfiVar8.c();
        ekfi ekfiVar9 = new ekfi();
        ekfiVar9.d(epjk.CMS_BACKUP_KEY, 2);
        ekfiVar9.d(epjk.CMS_ENCRYPTION_KEY, 1);
        ekfiVar9.d(epjk.CMS_HMAC_SHA256_KEY, 3);
        ekfiVar9.d(epjk.CMS_UNKNOWN_KEY, 0);
        j = ekfiVar9.c();
        ekfi ekfiVar10 = new ekfi();
        ekfiVar10.d(epjy.STATUS_UNKNOWN_MMS_GROUP_UPGRADE_STATUS, cins.a);
        ekfiVar10.d(epjy.STATUS_NOT_ELIGIBLE_BECAUSE_INACTIVE, cins.b);
        ekfiVar10.d(epjy.STATUS_NOT_ELIGIBLE_NOT_EVERYONE_RCS, cins.c);
        ekfiVar10.d(epjy.STATUS_NOT_ELIGIBLE_WAITING_FOR_OUTDATED_GM_CLIENT, cins.d);
        ekfiVar10.d(epjy.STATUS_ELIGIBLE_FOR_UPGRADE_BUT_NOT_ACTIVE_UPGRADER, cins.e);
        ekfiVar10.d(epjy.STATUS_UPGRADE_STARTED, cins.f);
        ekfiVar10.d(epjy.STATUS_RCS_GROUP_CREATION_FAILED, cins.g);
        ekfiVar10.d(epjy.STATUS_RCS_GROUP_CREATION_SUCCEEDED, cins.h);
        ekfiVar10.d(epjy.STATUS_UPGRADE_FAILED, cins.i);
        ekfiVar10.d(epjy.STATUS_UPGRADE_COMPLETE, cins.j);
        k = ekfiVar10.c();
    }

    static eplg a(int i2) {
        return (eplg) l.get(Integer.valueOf(i2));
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static eplh b(int i2) {
        return (eplh) ((ekod) b).d.get(Integer.valueOf(i2));
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static epll c(int i2) {
        return (epll) ((ekod) f).d.get(Integer.valueOf(i2));
    }
}
