package defpackage;

import j$.util.DesugarCollections;
import java.util.concurrent.atomic.AtomicReference;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class crvg {
    public static final fctc a = fctd.a(new fdae() { // from class: cruw
        @Override // defpackage.fdae
        public final Object invoke() {
            fctc fctcVar = crvg.a;
            return cqce.g("Bugle", "SpamVerdictEnforcementPolicyConfigManager");
        }
    });
    public static final fctc b = fctd.a(new fdae() { // from class: crux
        @Override // defpackage.fdae
        public final Object invoke() {
            fctc fctcVar = crvg.a;
            return new crus((cruu) crvg.c.a());
        }
    });
    public static final fctc c = fctd.a(new fdae() { // from class: cruy
        @Override // defpackage.fdae
        public final Object invoke() {
            fctc fctcVar = crvg.a;
            crut crutVar = (crut) cruu.a.createBuilder();
            crutVar.getClass();
            crutVar.copyOnWrite();
            ((cruu) crutVar.instance).d = "default";
            eykc eykcVar = eykc.DO_NOTHING;
            eykcVar.getClass();
            crutVar.copyOnWrite();
            ((cruu) crutVar.instance).b = eykcVar.a();
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvi crviVar = crvi.a;
            crvh crvhVar = (crvh) crviVar.createBuilder();
            crvhVar.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar.instance).b).getClass();
            crul crulVar = crul.a;
            cruj crujVar = (cruj) crulVar.createBuilder();
            crujVar.getClass();
            crum.d(5, crujVar);
            crum.c(0.0f, crujVar);
            eoff eoffVar = eoff.SPAM;
            crum.b(eoffVar, crujVar);
            crvj.d(crum.a(crujVar), crvhVar);
            DesugarCollections.unmodifiableList(((crvi) crvhVar.instance).e).getClass();
            crtk crtkVar = crtk.c;
            crtj crtjVar = (crtj) crtkVar.createBuilder();
            crtjVar.getClass();
            crtl.e(crtjVar);
            crtl.c(crtjVar);
            crtl.d(crtjVar);
            eofj eofjVar = eofj.SHORT_CODE;
            crtl.b(eofjVar, crtjVar);
            crtl.d(crtjVar);
            eofj eofjVar2 = eofj.ALPHA_CODE;
            crtl.b(eofjVar2, crtjVar);
            crvj.c(crtl.a(crtjVar), crvhVar);
            eykc eykcVar2 = eykc.SHOW_WARNING;
            crvj.b(eykcVar2, crvhVar);
            cruv.a(crvj.a(crvhVar), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar2 = (crvh) crviVar.createBuilder();
            crvhVar2.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar2.instance).b).getClass();
            cruj crujVar2 = (cruj) crulVar.createBuilder();
            crujVar2.getClass();
            crum.d(5, crujVar2);
            crum.c(1.0f, crujVar2);
            crum.b(eoffVar, crujVar2);
            crvj.d(crum.a(crujVar2), crvhVar2);
            DesugarCollections.unmodifiableList(((crvi) crvhVar2.instance).e).getClass();
            crtj crtjVar2 = (crtj) crtkVar.createBuilder();
            crtjVar2.getClass();
            crtl.e(crtjVar2);
            crtl.c(crtjVar2);
            crtl.d(crtjVar2);
            crtl.b(eofjVar, crtjVar2);
            crtl.d(crtjVar2);
            crtl.b(eofjVar2, crtjVar2);
            crvj.c(crtl.a(crtjVar2), crvhVar2);
            eykc eykcVar3 = eykc.MOVE_TO_SPAM_FOLDER;
            crvj.b(eykcVar3, crvhVar2);
            cruv.a(crvj.a(crvhVar2), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar3 = (crvh) crviVar.createBuilder();
            crvhVar3.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar3.instance).b).getClass();
            cruj crujVar3 = (cruj) crulVar.createBuilder();
            crujVar3.getClass();
            crum.d(6, crujVar3);
            crum.c(0.0f, crujVar3);
            crum.b(eoffVar, crujVar3);
            crvj.d(crum.a(crujVar3), crvhVar3);
            DesugarCollections.unmodifiableList(((crvi) crvhVar3.instance).e).getClass();
            crtj crtjVar3 = (crtj) crtkVar.createBuilder();
            crtjVar3.getClass();
            crtl.e(crtjVar3);
            crtl.c(crtjVar3);
            crtl.d(crtjVar3);
            crtl.b(eofjVar, crtjVar3);
            crtl.d(crtjVar3);
            crtl.b(eofjVar2, crtjVar3);
            crvj.c(crtl.a(crtjVar3), crvhVar3);
            crvj.b(eykcVar2, crvhVar3);
            cruv.a(crvj.a(crvhVar3), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar4 = (crvh) crviVar.createBuilder();
            crvhVar4.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar4.instance).b).getClass();
            cruj crujVar4 = (cruj) crulVar.createBuilder();
            crujVar4.getClass();
            crum.d(7, crujVar4);
            crum.c(0.0f, crujVar4);
            crum.b(eoffVar, crujVar4);
            crvj.d(crum.a(crujVar4), crvhVar4);
            DesugarCollections.unmodifiableList(((crvi) crvhVar4.instance).e).getClass();
            crtj crtjVar4 = (crtj) crtkVar.createBuilder();
            crtjVar4.getClass();
            crtl.e(crtjVar4);
            crtl.c(crtjVar4);
            crtl.d(crtjVar4);
            crtl.b(eofjVar, crtjVar4);
            crtl.d(crtjVar4);
            crtl.b(eofjVar2, crtjVar4);
            crvj.c(crtl.a(crtjVar4), crvhVar4);
            crvj.b(eykcVar2, crvhVar4);
            cruv.a(crvj.a(crvhVar4), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar5 = (crvh) crviVar.createBuilder();
            crvhVar5.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar5.instance).b).getClass();
            cruj crujVar5 = (cruj) crulVar.createBuilder();
            crujVar5.getClass();
            crum.d(7, crujVar5);
            crum.c(0.0f, crujVar5);
            crum.b(eoffVar, crujVar5);
            crvj.d(crum.a(crujVar5), crvhVar5);
            DesugarCollections.unmodifiableList(((crvi) crvhVar5.instance).b).getClass();
            cruj crujVar6 = (cruj) crulVar.createBuilder();
            crujVar6.getClass();
            crum.d(6, crujVar6);
            crum.c(0.0f, crujVar6);
            crum.b(eoffVar, crujVar6);
            crvj.d(crum.a(crujVar6), crvhVar5);
            DesugarCollections.unmodifiableList(((crvi) crvhVar5.instance).e).getClass();
            crtj crtjVar5 = (crtj) crtkVar.createBuilder();
            crtjVar5.getClass();
            crtl.e(crtjVar5);
            crtl.c(crtjVar5);
            crtl.d(crtjVar5);
            crtl.b(eofjVar, crtjVar5);
            crtl.d(crtjVar5);
            crtl.b(eofjVar2, crtjVar5);
            crvj.c(crtl.a(crtjVar5), crvhVar5);
            crvj.b(eykcVar3, crvhVar5);
            cruv.a(crvj.a(crvhVar5), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar6 = (crvh) crviVar.createBuilder();
            crvhVar6.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar6.instance).b).getClass();
            cruj crujVar7 = (cruj) crulVar.createBuilder();
            crujVar7.getClass();
            crum.d(4, crujVar7);
            crum.c(0.0f, crujVar7);
            crum.b(eoffVar, crujVar7);
            crvj.d(crum.a(crujVar7), crvhVar6);
            DesugarCollections.unmodifiableList(((crvi) crvhVar6.instance).b).getClass();
            cruj crujVar8 = (cruj) crulVar.createBuilder();
            crujVar8.getClass();
            crum.d(6, crujVar8);
            crum.c(0.0f, crujVar8);
            crum.b(eoffVar, crujVar8);
            crvj.d(crum.a(crujVar8), crvhVar6);
            DesugarCollections.unmodifiableList(((crvi) crvhVar6.instance).e).getClass();
            crtj crtjVar6 = (crtj) crtkVar.createBuilder();
            crtjVar6.getClass();
            crtl.e(crtjVar6);
            crtl.c(crtjVar6);
            crtl.d(crtjVar6);
            crtl.b(eofjVar, crtjVar6);
            crtl.d(crtjVar6);
            crtl.b(eofjVar2, crtjVar6);
            crvj.c(crtl.a(crtjVar6), crvhVar6);
            crvj.b(eykcVar3, crvhVar6);
            cruv.a(crvj.a(crvhVar6), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar7 = (crvh) crviVar.createBuilder();
            crvhVar7.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar7.instance).b).getClass();
            cruj crujVar9 = (cruj) crulVar.createBuilder();
            crujVar9.getClass();
            crum.d(6, crujVar9);
            crum.c(1.0f, crujVar9);
            crum.b(eoffVar, crujVar9);
            crvj.d(crum.a(crujVar9), crvhVar7);
            DesugarCollections.unmodifiableList(((crvi) crvhVar7.instance).e).getClass();
            crtj crtjVar7 = (crtj) crtkVar.createBuilder();
            crtjVar7.getClass();
            crtl.e(crtjVar7);
            crtl.c(crtjVar7);
            crtl.d(crtjVar7);
            crtl.b(eofjVar, crtjVar7);
            crtl.d(crtjVar7);
            crtl.b(eofjVar2, crtjVar7);
            crvj.c(crtl.a(crtjVar7), crvhVar7);
            crvj.b(eykcVar3, crvhVar7);
            cruv.a(crvj.a(crvhVar7), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar8 = (crvh) crviVar.createBuilder();
            crvhVar8.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar8.instance).b).getClass();
            cruj crujVar10 = (cruj) crulVar.createBuilder();
            crujVar10.getClass();
            crum.d(7, crujVar10);
            crum.c(1.0f, crujVar10);
            crum.b(eoffVar, crujVar10);
            crvj.d(crum.a(crujVar10), crvhVar8);
            DesugarCollections.unmodifiableList(((crvi) crvhVar8.instance).e).getClass();
            crtj crtjVar8 = (crtj) crtkVar.createBuilder();
            crtjVar8.getClass();
            crtl.e(crtjVar8);
            crtl.c(crtjVar8);
            crtl.d(crtjVar8);
            crtl.b(eofjVar, crtjVar8);
            crtl.d(crtjVar8);
            crtl.b(eofjVar2, crtjVar8);
            crvj.c(crtl.a(crtjVar8), crvhVar8);
            crvj.b(eykcVar3, crvhVar8);
            cruv.a(crvj.a(crvhVar8), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar9 = (crvh) crviVar.createBuilder();
            crvhVar9.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar9.instance).b).getClass();
            cruj crujVar11 = (cruj) crulVar.createBuilder();
            crujVar11.getClass();
            crum.d(6, crujVar11);
            crum.c(1.0f, crujVar11);
            crum.b(eoff.NOT_SPAM, crujVar11);
            crvj.d(crum.a(crujVar11), crvhVar9);
            crvj.b(eykc.ALLOW, crvhVar9);
            cruv.a(crvj.a(crvhVar9), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar10 = (crvh) crviVar.createBuilder();
            crvhVar10.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar10.instance).b).getClass();
            cruj crujVar12 = (cruj) crulVar.createBuilder();
            crujVar12.getClass();
            crum.d(10, crujVar12);
            crum.c(0.5f, crujVar12);
            crum.b(eoffVar, crujVar12);
            crvj.d(crum.a(crujVar12), crvhVar10);
            DesugarCollections.unmodifiableList(((crvi) crvhVar10.instance).e).getClass();
            crtj crtjVar9 = (crtj) crtkVar.createBuilder();
            crtjVar9.getClass();
            crtl.e(crtjVar9);
            crtl.c(crtjVar9);
            crtl.d(crtjVar9);
            crtl.b(eofjVar, crtjVar9);
            crtl.d(crtjVar9);
            crtl.b(eofjVar2, crtjVar9);
            crvj.c(crtl.a(crtjVar9), crvhVar10);
            crvj.b(eykcVar2, crvhVar10);
            cruv.a(crvj.a(crvhVar10), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar11 = (crvh) crviVar.createBuilder();
            crvhVar11.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar11.instance).b).getClass();
            cruj crujVar13 = (cruj) crulVar.createBuilder();
            crujVar13.getClass();
            crum.d(10, crujVar13);
            crum.c(0.9f, crujVar13);
            crum.b(eoffVar, crujVar13);
            crvj.d(crum.a(crujVar13), crvhVar11);
            DesugarCollections.unmodifiableList(((crvi) crvhVar11.instance).e).getClass();
            crtj crtjVar10 = (crtj) crtkVar.createBuilder();
            crtjVar10.getClass();
            crtl.e(crtjVar10);
            crtl.c(crtjVar10);
            crtl.d(crtjVar10);
            crtl.b(eofjVar, crtjVar10);
            crtl.d(crtjVar10);
            crtl.b(eofjVar2, crtjVar10);
            crvj.c(crtl.a(crtjVar10), crvhVar11);
            crvj.b(eykcVar3, crvhVar11);
            cruv.a(crvj.a(crvhVar11), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar12 = (crvh) crviVar.createBuilder();
            crvhVar12.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar12.instance).b).getClass();
            cruj crujVar14 = (cruj) crulVar.createBuilder();
            crujVar14.getClass();
            crum.d(8, crujVar14);
            crum.c(0.5f, crujVar14);
            crum.b(eoffVar, crujVar14);
            crvj.d(crum.a(crujVar14), crvhVar12);
            DesugarCollections.unmodifiableList(((crvi) crvhVar12.instance).e).getClass();
            crtj crtjVar11 = (crtj) crtkVar.createBuilder();
            crtjVar11.getClass();
            crtl.e(crtjVar11);
            crtl.c(crtjVar11);
            crtl.d(crtjVar11);
            crtl.b(eofjVar, crtjVar11);
            crtl.d(crtjVar11);
            crtl.b(eofjVar2, crtjVar11);
            crvj.c(crtl.a(crtjVar11), crvhVar12);
            crvj.b(eykcVar2, crvhVar12);
            cruv.a(crvj.a(crvhVar12), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar13 = (crvh) crviVar.createBuilder();
            crvhVar13.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar13.instance).b).getClass();
            cruj crujVar15 = (cruj) crulVar.createBuilder();
            crujVar15.getClass();
            crum.d(8, crujVar15);
            crum.c(1.0f, crujVar15);
            crum.b(eoffVar, crujVar15);
            crvj.d(crum.a(crujVar15), crvhVar13);
            DesugarCollections.unmodifiableList(((crvi) crvhVar13.instance).e).getClass();
            crtj crtjVar12 = (crtj) crtkVar.createBuilder();
            crtjVar12.getClass();
            crtl.e(crtjVar12);
            crtl.c(crtjVar12);
            crtl.d(crtjVar12);
            crtl.b(eofjVar, crtjVar12);
            crtl.d(crtjVar12);
            crtl.b(eofjVar2, crtjVar12);
            crvj.c(crtl.a(crtjVar12), crvhVar13);
            crvj.b(eykcVar3, crvhVar13);
            cruv.a(crvj.a(crvhVar13), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar14 = (crvh) crviVar.createBuilder();
            crvhVar14.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar14.instance).b).getClass();
            cruj crujVar16 = (cruj) crulVar.createBuilder();
            crujVar16.getClass();
            crum.d(9, crujVar16);
            crum.c(0.5f, crujVar16);
            crum.b(eoffVar, crujVar16);
            crvj.d(crum.a(crujVar16), crvhVar14);
            DesugarCollections.unmodifiableList(((crvi) crvhVar14.instance).e).getClass();
            crtj crtjVar13 = (crtj) crtkVar.createBuilder();
            crtjVar13.getClass();
            crtl.e(crtjVar13);
            crtl.c(crtjVar13);
            crtl.d(crtjVar13);
            crtl.b(eofjVar, crtjVar13);
            crtl.d(crtjVar13);
            crtl.b(eofjVar2, crtjVar13);
            crvj.c(crtl.a(crtjVar13), crvhVar14);
            crvj.b(eykcVar2, crvhVar14);
            cruv.a(crvj.a(crvhVar14), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar15 = (crvh) crviVar.createBuilder();
            crvhVar15.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar15.instance).b).getClass();
            cruj crujVar17 = (cruj) crulVar.createBuilder();
            crujVar17.getClass();
            crum.d(9, crujVar17);
            crum.c(0.5f, crujVar17);
            crum.b(eoffVar, crujVar17);
            crvj.d(crum.a(crujVar17), crvhVar15);
            DesugarCollections.unmodifiableList(((crvi) crvhVar15.instance).b).getClass();
            cruj crujVar18 = (cruj) crulVar.createBuilder();
            crujVar18.getClass();
            crum.d(7, crujVar18);
            crum.c(0.0f, crujVar18);
            crum.b(eoffVar, crujVar18);
            crvj.d(crum.a(crujVar18), crvhVar15);
            DesugarCollections.unmodifiableList(((crvi) crvhVar15.instance).e).getClass();
            crtj crtjVar14 = (crtj) crtkVar.createBuilder();
            crtjVar14.getClass();
            crtl.e(crtjVar14);
            crtl.c(crtjVar14);
            crtl.d(crtjVar14);
            crtl.b(eofjVar, crtjVar14);
            crtl.d(crtjVar14);
            crtl.b(eofjVar2, crtjVar14);
            crvj.c(crtl.a(crtjVar14), crvhVar15);
            crvj.b(eykcVar3, crvhVar15);
            cruv.a(crvj.a(crvhVar15), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar16 = (crvh) crviVar.createBuilder();
            crvhVar16.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar16.instance).b).getClass();
            cruj crujVar19 = (cruj) crulVar.createBuilder();
            crujVar19.getClass();
            crum.d(9, crujVar19);
            crum.c(1.0f, crujVar19);
            crum.b(eoffVar, crujVar19);
            crvj.d(crum.a(crujVar19), crvhVar16);
            DesugarCollections.unmodifiableList(((crvi) crvhVar16.instance).e).getClass();
            crtj crtjVar15 = (crtj) crtkVar.createBuilder();
            crtjVar15.getClass();
            crtl.e(crtjVar15);
            crtl.c(crtjVar15);
            crtl.d(crtjVar15);
            crtl.b(eofjVar, crtjVar15);
            crtl.d(crtjVar15);
            crtl.b(eofjVar2, crtjVar15);
            crvj.c(crtl.a(crtjVar15), crvhVar16);
            crvj.b(eykcVar3, crvhVar16);
            cruv.a(crvj.a(crvhVar16), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar17 = (crvh) crviVar.createBuilder();
            crvhVar17.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar17.instance).b).getClass();
            cruj crujVar20 = (cruj) crulVar.createBuilder();
            crujVar20.getClass();
            crum.d(5, crujVar20);
            crum.c(0.5f, crujVar20);
            crum.b(eoffVar, crujVar20);
            crvj.d(crum.a(crujVar20), crvhVar17);
            DesugarCollections.unmodifiableList(((crvi) crvhVar17.instance).b).getClass();
            cruj crujVar21 = (cruj) crulVar.createBuilder();
            crujVar21.getClass();
            crum.d(10, crujVar21);
            crum.c(0.5f, crujVar21);
            crum.b(eoffVar, crujVar21);
            crvj.d(crum.a(crujVar21), crvhVar17);
            DesugarCollections.unmodifiableList(((crvi) crvhVar17.instance).e).getClass();
            crtj crtjVar16 = (crtj) crtkVar.createBuilder();
            crtjVar16.getClass();
            crtl.e(crtjVar16);
            crtl.c(crtjVar16);
            crtl.d(crtjVar16);
            crtl.b(eofjVar, crtjVar16);
            crtl.d(crtjVar16);
            crtl.b(eofjVar2, crtjVar16);
            crvj.c(crtl.a(crtjVar16), crvhVar17);
            crvj.b(eykcVar3, crvhVar17);
            cruv.a(crvj.a(crvhVar17), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar18 = (crvh) crviVar.createBuilder();
            crvhVar18.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar18.instance).b).getClass();
            cruj crujVar22 = (cruj) crulVar.createBuilder();
            crujVar22.getClass();
            crum.d(6, crujVar22);
            crum.c(0.5f, crujVar22);
            crum.b(eoffVar, crujVar22);
            crvj.d(crum.a(crujVar22), crvhVar18);
            DesugarCollections.unmodifiableList(((crvi) crvhVar18.instance).b).getClass();
            cruj crujVar23 = (cruj) crulVar.createBuilder();
            crujVar23.getClass();
            crum.d(10, crujVar23);
            crum.c(0.5f, crujVar23);
            crum.b(eoffVar, crujVar23);
            crvj.d(crum.a(crujVar23), crvhVar18);
            DesugarCollections.unmodifiableList(((crvi) crvhVar18.instance).e).getClass();
            crtj crtjVar17 = (crtj) crtkVar.createBuilder();
            crtjVar17.getClass();
            crtl.e(crtjVar17);
            crtl.c(crtjVar17);
            crtl.d(crtjVar17);
            crtl.b(eofjVar, crtjVar17);
            crtl.d(crtjVar17);
            crtl.b(eofjVar2, crtjVar17);
            crvj.c(crtl.a(crtjVar17), crvhVar18);
            crvj.b(eykcVar3, crvhVar18);
            cruv.a(crvj.a(crvhVar18), crutVar);
            DesugarCollections.unmodifiableList(((cruu) crutVar.instance).c).getClass();
            crvh crvhVar19 = (crvh) crviVar.createBuilder();
            crvhVar19.getClass();
            DesugarCollections.unmodifiableList(((crvi) crvhVar19.instance).b).getClass();
            cruj crujVar24 = (cruj) crulVar.createBuilder();
            crujVar24.getClass();
            crum.d(9, crujVar24);
            crum.c(0.5f, crujVar24);
            crum.b(eoffVar, crujVar24);
            crvj.d(crum.a(crujVar24), crvhVar19);
            DesugarCollections.unmodifiableList(((crvi) crvhVar19.instance).b).getClass();
            cruj crujVar25 = (cruj) crulVar.createBuilder();
            crujVar25.getClass();
            crum.d(10, crujVar25);
            crum.c(0.5f, crujVar25);
            crum.b(eoffVar, crujVar25);
            crvj.d(crum.a(crujVar25), crvhVar19);
            DesugarCollections.unmodifiableList(((crvi) crvhVar19.instance).e).getClass();
            crtj crtjVar18 = (crtj) crtkVar.createBuilder();
            crtjVar18.getClass();
            crtl.e(crtjVar18);
            crtl.c(crtjVar18);
            crtl.d(crtjVar18);
            crtl.b(eofjVar, crtjVar18);
            crtl.d(crtjVar18);
            crtl.b(eofjVar2, crtjVar18);
            crvj.c(crtl.a(crtjVar18), crvhVar19);
            crvj.b(eykcVar3, crvhVar19);
            cruv.a(crvj.a(crvhVar19), crutVar);
            evsn evsnVarBuild = crutVar.build();
            evsnVarBuild.getClass();
            return (cruu) evsnVarBuild;
        }
    });
    public final fcsu d;
    public final fcsu e;
    public final fcsu f;
    public final fcsu g;
    public final AtomicReference h;

    public crvg(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4) {
        fcsuVar.getClass();
        fcsuVar2.getClass();
        fcsuVar3.getClass();
        fcsuVar4.getClass();
        this.d = fcsuVar;
        this.e = fcsuVar2;
        this.f = fcsuVar3;
        this.g = fcsuVar4;
        this.h = new AtomicReference(null);
    }
}
