package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dfof {
    public final dfoa A;
    public final dfoa B;
    public final dfoa C;
    public final dfoa D;
    public final dfoa E;
    public final dfoa F;
    public final dfoa G;
    public final dfoa H;
    public final dfoa I;
    public final dfoa J;
    public final dfoa K;
    public final dfoa L;
    public final dfoa M;
    public final dfoa N;
    public final dfoa O;
    public final dfoa P;
    public final dfny Q;
    public final dfny R;
    public final dfny S;
    public final dfny T;
    public final dfny U;
    public final dfny V;
    public final dfny W;
    public final dfny X;
    public final dfny Y;
    public final dfoa Z;
    public final dfoa a;
    public final dfny aA;
    public final dfny aB;
    public final dfoa aC;
    public final dfoa aD;
    public final dfoa aE;
    public final dfoa aF;
    public final dfoa aG;
    public final dfny aH;
    public final dfoa aI;
    public final dfoa aJ;
    public final dfoa aK;
    public final dfny aa;
    public final dfny ab;
    public final dfny ac;
    public final dfny ad;
    public final dfny ae;
    public final dfny af;
    public final dfny ag;
    public final dfny ah;
    public final dfoa ai;
    public final dfny aj;
    public final dfny ak;
    public final dfny al;
    public final dfny am;
    public final dfny an;
    public final dfny ao;
    public final dfny ap;
    public final dfny aq;
    public final dfny ar;
    public final dfny as;
    public final dfny at;
    public final dfny au;
    public final dfny av;
    public final dfny aw;
    public final dfny ax;
    public final dfny ay;
    public final dfny az;
    public final dfoa b;
    public final dfoa c;
    public final dfoa d;
    public final dfoa e;
    public final dfoa f;
    public final dfoa g;
    public final dfoa h;
    public final dfoa i;
    public final dfoa j;
    public final dfoa k;
    public final dfoa l;
    public final dfoa m;
    public final dfoa n;
    public final dfoa o;
    public final dfoa p;
    public final dfoa q;
    public final dfoa r;
    public final dfoa s;
    public final dfoa t;
    public final dfoa u;
    public final dfoa v;
    public final dfoa w;
    public final dfoa x;
    public final dfoa y;
    public final dfoa z;

    public dfof(dfog dfogVar) {
        this.a = dfogVar.i("is_jibe_sip_enabled", true);
        this.at = dfogVar.i("is_synced", false);
        this.b = dfogVar.g("periodic_metrics_send_interval_mins", 1440L);
        this.c = dfogVar.g("periodic_metrics_retry_backoff_mins", 60L);
        this.d = dfogVar.i("prefer_ipv6", false);
        this.e = dfogVar.i("force_ipv4", false);
        this.f = dfogVar.i("enable_destroy_jibe_service_in_cs_apk", false);
        this.g = dfogVar.i("enable_provisioning_task_in_bugle", true);
        this.h = dfogVar.i("enable_rcs_configuration_in_bugle", false);
        this.i = dfogVar.g("jibe_service_init_timeout_millis", 300000L);
        this.j = dfogVar.f("single_registration_cached_capability_query_timeout_millis", 100);
        this.k = dfogVar.i("enable_single_registration_provisioning", false);
        this.Z = dfogVar.g("pev3_otp_timeout_millis", 360000L);
        this.l = dfogVar.f("received_message_queue_dedup_cache_size", 100);
        this.m = dfogVar.i("enable_single_registration_tmo_features", false);
        this.n = dfogVar.i("enable_single_registration_tmo_gba_download_feature", false);
        this.o = dfogVar.i("enable_single_registration_wait_for_publish_after_registration", false);
        this.q = dfogVar.h("clearcut_banned_number_list", "+15551234567");
        this.r = dfogVar.i("disable_phone_number_normalization_in_cs", false);
        this.s = dfogVar.h("gba_auth_naf_id", "");
        this.t = dfogVar.g("pev3_otp_cache_ttl_seconds", 30L);
        this.u = dfogVar.i("enable_strict_mode_installer", false);
        this.v = dfogVar.i("enable_test_only_msrp_ft_feature_tag_for_single_registration", false);
        this.w = dfogVar.g("rcs_process_uptime_logging_duration_seconds", 3600L);
        this.x = dfogVar.i("enable_msrp_over_dedicated_bearer", false);
        this.y = dfogVar.i("enable_msrp_over_dedicated_bearer_address_verification", false);
        this.p = dfogVar.f("dedicated_bearer_setup_timeout_seconds", 10);
        this.z = dfogVar.i("enable_default_bearer_fallback", false);
        ewtl ewtlVar = (ewtl) ewtm.a.createBuilder();
        ewtlVar.a(5);
        ewtlVar.a(6);
        ewtlVar.a(7);
        ewtlVar.a(8);
        ewtlVar.a(9);
        this.A = new dfoa(dfogVar.d.k("dedicated_bearer_allowed_qci", (ewtm) ewtlVar.build(), new dzze() { // from class: dfnx
            @Override // defpackage.dzze
            public final Object a(byte[] bArr) {
                return (ewtm) evsn.parseFrom(ewtm.a, bArr);
            }
        }));
        this.B = dfogVar.g("single_registration_publish_response_timeout_millis", 5000L);
        this.C = dfogVar.h("single_registration_client_version", "RCSAndrd-1.0");
        this.F = dfogVar.h("single_registration_client_vendor", "Goog");
        this.E = dfogVar.h("single_registration_rcs_profile", "UP_2.3");
        this.D = dfogVar.h("single_registration_rcs_version", "6.0");
        this.G = dfogVar.h("single_registration_carrier_user_agent_delimiter", " ");
        this.H = dfogVar.i("enable_single_registration_indicator_in_ims_config_log", false);
        this.I = dfogVar.i("enable_session_store_waiting_established", false);
        this.J = dfogVar.i("use_sim_id_from_bugle_for_rcs_config", false);
        this.K = dfogVar.i("enable_single_registration_att_session_timer_requirements", false);
        this.L = dfogVar.i("enable_single_registration_att_download_feature", false);
        this.M = dfogVar.i("enable_single_registration_att_settings_tos_link", false);
        this.N = dfogVar.i("enable_single_registration_vzw_download_feature", false);
        this.O = dfogVar.i("enable_logging_dns_events", false);
        this.P = dfogVar.i("enable_logging_registration_events", false);
        this.Q = dfogVar.i("strip_quotes_from_user_count", false);
        this.Y = dfogVar.i("enable_ipc_error_clearcut_logging", false);
        this.R = dfogVar.i("enable_sim_removal_on_fi", false);
        this.S = dfogVar.i("modify_remote_capabilities_with_config_values", false);
        this.T = dfogVar.g("bugle_version_code_without_engine_migration", 999999999L);
        this.U = dfogVar.i("count_incoming_messages_queuing_latency", false);
        this.V = dfogVar.e("xsl_throttle_ratio", 1.0d);
        this.W = dfogVar.f("log_sample_size", 0);
        this.X = dfogVar.i("enable_sample_logging", false);
        this.aa = dfogVar.i("enable_single_registration_cricket_settings_tos_link", false);
        this.ab = dfogVar.i("use_messaging_identity_v2_factories", false);
        this.ac = dfogVar.i("shadow_launch_messaging_identity_v2_factories", false);
        this.ad = dfogVar.e("shadow_launch_miV2_throttle_ratio", 0.0d);
        this.ae = dfogVar.i("shadow_launch_messaging_identity_integration", false);
        this.af = dfogVar.e("shadow_launch_mi_integration_throttle_ratio", 0.0d);
        this.ag = dfogVar.i("enable_fallback_to_manual_msisdn_after_sim_number_attempt", false);
        this.ah = dfogVar.f("max_attempts_before_fallback_to_manual_msisdn", 2);
        this.ai = dfogVar.i("enable_link_properties_logging", false);
        this.aj = dfogVar.i("enable_network_factory_for_secure_msrp_sockets", false);
        this.ak = dfogVar.i("sub_utils_throws_for_invalid_sub_id", false);
        this.al = dfogVar.f("cache_default_sms_subscriber_id_seconds", 3);
        this.am = dfogVar.f("cache_subscription_country_seconds", 30);
        this.an = new dfoa(dfogVar.d.k("allowlisted_regions_for_short_code_rcs", ewto.a, new dzze() { // from class: dfnw
            @Override // defpackage.dzze
            public final Object a(byte[] bArr) {
                return (ewto) evsn.parseFrom(ewto.a, bArr);
            }
        }));
        this.ao = dfogVar.f("cached_country_code_detector_max_cache_size", 5);
        this.ap = dfogVar.f("cached_country_code_detector_cache_lifetime_in_seconds", 5);
        this.aq = dfogVar.i("phone_number_utils_uses_smarter_home_countries", false);
        this.ar = dfogVar.i("enable_send_slm", false);
        this.as = dfogVar.i("disable_mi_local_destination_sanitization", false);
        this.au = dfogVar.i("enable_single_registration_verizon_settings_tos_link", false);
        this.av = dfogVar.f("imdn_rate_limiting_capacity", 10);
        this.aw = dfogVar.f("imdn_rate_limiting_refill_tick_rate_ms", 100);
        this.ax = dfogVar.f("imdn_rate_limiting_refill_amount_per_tick", 1);
        this.ay = dfogVar.i("stop_presence_services_initialization", false);
        this.az = dfogVar.i("migrate_jibe_service_from_cs_apk_to_bugle", false);
        this.aA = dfogVar.i("enable_use_configuration_holder", false);
        this.aB = dfogVar.i("mark_rcs_profile_service_as_always_connected", false);
        this.aC = dfogVar.i("enable_white_listed_signatures_from_phenotype", false);
        this.aD = dfogVar.h("white_listed_signatures", "");
        this.aG = dfogVar.i("enable_single_registration_migration", false);
        this.aE = dfogVar.i("show_enabled_by_carrier_in_settings_with_link", false);
        this.aF = dfogVar.h("settings_tos_link_url", "");
        this.aH = dfogVar.h("tachyon_phone_url_override_for_testing", "");
        this.aI = dfogVar.i("enable_opt_in_consent_check", false);
        this.aJ = dfogVar.i("ignore_single_reg_provisioning_events_after_migration", false);
        this.aK = dfogVar.i("enable_send_negative_delivery_for_unsupported_content_types", false);
    }
}
