package defpackage;

import android.content.Context;
import com.google.android.ims.chatsession.ChatSessionEngine;
import com.google.android.ims.jibe.service.filetransfer.FileTransferEngine;
import com.google.android.ims.jibe.service.signup.SignupEngine;
import com.google.android.ims.rcs.engine.impl.RcsEngineImpl;
import com.google.android.ims.rcsservice.businessinfo.BusinessInfoDatabase;
import com.google.android.libraries.jibe.service.locationsharing.LocationSharingEngine;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dgug {
    private final fcsu A;
    private final fcsu B;
    private final fcsu C;
    private final fcsu D;
    private final fcsu E;
    private final fcsu F;
    private final fcsu G;
    private final fcsu H;
    private final fcsu I;
    private final fcsu J;
    private final fcsu K;
    private final fcsu L;
    private final fcsu M;
    private final fcsu N;
    private final fcsu O;
    private final fcsu P;
    private final fcsu Q;
    private final fcsu R;
    private final fcsu S;
    private final fcsu T;
    private final fcsu U;
    private final fcsu V;
    private final fcsu W;
    private final fcsu a;
    private final fcsu b;
    private final fcsu c;
    private final fcsu d;
    private final fcsu e;
    private final fcsu f;
    private final fcsu g;
    private final fcsu h;
    private final fcsu i;
    private final fcsu j;
    private final fcsu k;
    private final fcsu l;
    private final fcsu m;
    private final fcsu n;
    private final fcsu o;
    private final fcsu p;
    private final fcsu q;
    private final fcsu r;
    private final fcsu s;
    private final fcsu t;
    private final fcsu u;
    private final fcsu v;
    private final fcsu w;
    private final fcsu x;
    private final fcsu y;
    private final fcsu z;

    public dgug(fcsu fcsuVar, fcsu fcsuVar2, fcsu fcsuVar3, fcsu fcsuVar4, fcsu fcsuVar5, fcsu fcsuVar6, fcsu fcsuVar7, fcsu fcsuVar8, fcsu fcsuVar9, fcsu fcsuVar10, fcsu fcsuVar11, fcsu fcsuVar12, fcsu fcsuVar13, fcsu fcsuVar14, fcsu fcsuVar15, fcsu fcsuVar16, fcsu fcsuVar17, fcsu fcsuVar18, fcsu fcsuVar19, fcsu fcsuVar20, fcsu fcsuVar21, fcsu fcsuVar22, fcsu fcsuVar23, fcsu fcsuVar24, fcsu fcsuVar25, fcsu fcsuVar26, fcsu fcsuVar27, fcsu fcsuVar28, fcsu fcsuVar29, fcsu fcsuVar30, fcsu fcsuVar31, fcsu fcsuVar32, fcsu fcsuVar33, fcsu fcsuVar34, fcsu fcsuVar35, fcsu fcsuVar36, fcsu fcsuVar37, fcsu fcsuVar38, fcsu fcsuVar39, fcsu fcsuVar40, fcsu fcsuVar41, fcsu fcsuVar42, fcsu fcsuVar43, fcsu fcsuVar44, fcsu fcsuVar45, fcsu fcsuVar46, fcsu fcsuVar47, fcsu fcsuVar48, fcsu fcsuVar49) {
        this.a = fcsuVar;
        this.b = fcsuVar2;
        this.c = fcsuVar3;
        this.d = fcsuVar4;
        this.e = fcsuVar5;
        this.f = fcsuVar6;
        this.g = fcsuVar7;
        this.h = fcsuVar8;
        this.i = fcsuVar9;
        this.j = fcsuVar10;
        this.k = fcsuVar11;
        this.l = fcsuVar12;
        this.m = fcsuVar13;
        this.n = fcsuVar14;
        this.o = fcsuVar15;
        this.p = fcsuVar16;
        this.q = fcsuVar17;
        this.r = fcsuVar18;
        this.s = fcsuVar19;
        this.t = fcsuVar20;
        this.u = fcsuVar21;
        this.v = fcsuVar22;
        this.w = fcsuVar23;
        this.x = fcsuVar24;
        this.y = fcsuVar25;
        this.z = fcsuVar26;
        this.A = fcsuVar27;
        this.B = fcsuVar28;
        this.C = fcsuVar29;
        this.D = fcsuVar30;
        this.E = fcsuVar31;
        this.F = fcsuVar32;
        this.G = fcsuVar33;
        this.H = fcsuVar34;
        this.I = fcsuVar35;
        this.J = fcsuVar36;
        this.K = fcsuVar37;
        this.L = fcsuVar38;
        this.M = fcsuVar39;
        this.N = fcsuVar40;
        this.O = fcsuVar41;
        this.P = fcsuVar42;
        this.Q = fcsuVar43;
        this.R = fcsuVar44;
        this.S = fcsuVar45;
        this.T = fcsuVar46;
        this.U = fcsuVar47;
        this.V = fcsuVar48;
        this.W = fcsuVar49;
    }

    public final RcsEngineImpl a(dhki dhkiVar, dfyy dfyyVar, dffx dffxVar, dgxj dgxjVar) {
        Context context = (Context) this.a.b();
        BusinessInfoDatabase businessInfoDatabase = (BusinessInfoDatabase) this.b.b();
        dfdd dfddVar = (dfdd) this.c.b();
        dfdi dfdiVar = (dfdi) this.d.b();
        dfdiVar.getClass();
        dfcf dfcfVar = (dfcf) this.e.b();
        dfcfVar.getClass();
        dgxb dgxbVar = (dgxb) this.f.b();
        dgxbVar.getClass();
        dhgz dhgzVar = (dhgz) this.g.b();
        dfdv dfdvVar = (dfdv) this.h.b();
        dhel dhelVar = (dhel) this.i.b();
        dhelVar.getClass();
        dhbz dhbzVar = (dhbz) this.j.b();
        FileTransferEngine fileTransferEngine = (FileTransferEngine) this.k.b();
        fileTransferEngine.getClass();
        ChatSessionEngine chatSessionEngine = (ChatSessionEngine) this.l.b();
        chatSessionEngine.getClass();
        LocationSharingEngine locationSharingEngine = (LocationSharingEngine) this.m.b();
        locationSharingEngine.getClass();
        dhes dhesVar = (dhes) this.n.b();
        dfnp dfnpVar = (dfnp) this.o.b();
        dewk dewkVar = (dewk) this.p.b();
        dgto dgtoVar = (dgto) this.q.b();
        eosc eoscVar = (eosc) this.r.b();
        eosd eosdVar = (eosd) this.s.b();
        dfcj dfcjVar = (dfcj) this.t.b();
        crmx crmxVar = (crmx) this.u.b();
        dgiu dgiuVar = (dgiu) this.v.b();
        dgiuVar.getClass();
        dfdj dfdjVar = (dfdj) this.w.b();
        dfhn dfhnVar = (dfhn) this.x.b();
        dfyd dfydVar = (dfyd) this.y.b();
        ebja ebjaVar = (ebja) this.z.b();
        dgfu dgfuVar = (dgfu) this.A.b();
        dgxf dgxfVar = (dgxf) this.B.b();
        dhbc dhbcVar = (dhbc) this.C.b();
        dgrs dgrsVar = (dgrs) this.D.b();
        dgve dgveVar = (dgve) this.E.b();
        dfza dfzaVar = (dfza) this.F.b();
        dgwa dgwaVar = (dgwa) this.G.b();
        dgwaVar.getClass();
        eblg eblgVar = (eblg) this.H.b();
        eblgVar.getClass();
        dhgr dhgrVar = (dhgr) this.I.b();
        SignupEngine signupEngine = (SignupEngine) this.J.b();
        signupEngine.getClass();
        dfxx dfxxVar = (dfxx) this.K.b();
        fcsu fcsuVar = this.L;
        dhej dhejVar = (dhej) this.M.b();
        dhejVar.getClass();
        dhme dhmeVar = (dhme) this.N.b();
        dhdy dhdyVar = (dhdy) this.O.b();
        dfpv dfpvVar = (dfpv) this.P.b();
        diep diepVar = (diep) this.Q.b();
        dhnr dhnrVar = (dhnr) this.R.b();
        dfze dfzeVar = (dfze) this.S.b();
        dfzeVar.getClass();
        deza dezaVar = (deza) this.T.b();
        dezd dezdVar = (dezd) this.U.b();
        dezdVar.getClass();
        dfzz dfzzVar = (dfzz) this.V.b();
        dfzzVar.getClass();
        alpc alpcVar = (alpc) this.W.b();
        dhkiVar.getClass();
        dffxVar.getClass();
        return new RcsEngineImpl(context, businessInfoDatabase, dfddVar, dfdiVar, dfcfVar, dgxbVar, dhgzVar, dfdvVar, dhelVar, dhbzVar, fileTransferEngine, chatSessionEngine, locationSharingEngine, dhesVar, dfnpVar, dewkVar, dgtoVar, eoscVar, eosdVar, dfcjVar, crmxVar, dgiuVar, dfdjVar, dfhnVar, dfydVar, ebjaVar, dgfuVar, dgxfVar, dhbcVar, dgrsVar, dgveVar, dfzaVar, dgwaVar, eblgVar, dhgrVar, signupEngine, dfxxVar, fcsuVar, dhejVar, dhmeVar, dhdyVar, dfpvVar, diepVar, dhnrVar, dfzeVar, dezaVar, dezdVar, dfzzVar, alpcVar, dhkiVar, dfyyVar, dffxVar, dgxjVar);
    }
}
