package defpackage;

import androidx.car.app.hardware.common.CarZone;
import androidx.car.app.hardware.info.EnergyProfile;
import androidx.car.app.navigation.model.Maneuver;
import com.android.vcard.VCardConstants;
import com.google.android.apps.messaging.R;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;
import com.sun.jna.Function;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class djrt {
    public static final int a(djrr djrrVar) {
        switch (djrrVar.ordinal()) {
            case 0:
                return R.drawable.gs_accessibility_new_vd_theme_24;
            case 1:
                return R.drawable.gs_account_circle_vd_theme_24;
            case 2:
                return R.drawable.gs_account_circle_off_vd_theme_24;
            case 3:
                return R.drawable.gs_add_vd_theme_24;
            case 4:
                return R.drawable.gs_add_a_photo_vd_theme_24;
            case 5:
                return R.drawable.gs_add_call_vd_theme_24;
            case 6:
                return R.drawable.gs_add_circle_vd_theme_24;
            case 7:
                return R.drawable.gs_add_circle_fill1_vd_theme_24;
            case 8:
                return R.drawable.gs_add_photo_alternate_vd_theme_24;
            case 9:
                return R.drawable.gs_add_reaction_vd_theme_24;
            case 10:
                return R.drawable.gs_alarm_vd_theme_24;
            case 11:
                return R.drawable.gs_alarm_on_vd_theme_24;
            case 12:
                return R.drawable.gs_alarm_on_fill1_vd_theme_24;
            case 13:
                return R.drawable.gs_android_contacts_vd_theme_24;
            case 14:
                return R.drawable.gs_android_contacts_fill1_vd_theme_24;
            case 15:
                return R.drawable.gs_android_satellite_vd_theme_24;
            case 16:
                return R.drawable.gs_arrow_back_vd_theme_24;
            case 17:
                return R.drawable.gs_arrow_downward_vd_theme_24;
            case 18:
                return R.drawable.gs_arrow_drop_down_vd_theme_24;
            case 19:
                return R.drawable.gs_arrow_drop_up_vd_theme_24;
            case 20:
                return R.drawable.gs_arrow_forward_vd_theme_24;
            case 21:
                return R.drawable.gs_arrow_right_alt_vd_theme_24;
            case 22:
                return R.drawable.assistant_logo;
            case 23:
                return R.drawable.gs_attachment_vd_theme_24;
            case 24:
                return R.drawable.gs_attach_file_vd_theme_24;
            case 25:
                return R.drawable.gs_attach_money_vd_theme_24;
            case 26:
                return R.drawable.gs_autorenew_vd_theme_24;
            case 27:
                return R.drawable.ic_avatar_anonymous;
            case 28:
                return R.drawable.gs_backspace_vd_theme_24;
            case 29:
                return R.drawable.gs_back_hand_vd_theme_24;
            case 30:
                return R.drawable.gs_block_vd_theme_24;
            case 31:
                return R.drawable.gs_block_fill1_vd_theme_24;
            case 32:
                return R.drawable.gs_blur_on_vd_theme_24;
            case 33:
                return R.drawable.gs_bookmark_vd_theme_24;
            case 34:
                return R.drawable.gs_bottom_sheets_vd_theme_24;
            case 35:
                return R.drawable.gs_brightness_2_vd_theme_24;
            case 36:
                return R.drawable.gs_brightness_4_vd_theme_24;
            case 37:
                return R.drawable.gs_brightness_5_vd_theme_24;
            case 38:
                return R.drawable.gs_brightness_6_vd_theme_24;
            case Maneuver.TYPE_DESTINATION /* 39 */:
                return R.drawable.gs_buttons_alt_vd_theme_24;
            case 40:
                return R.drawable.gs_cake_vd_theme_24;
            case 41:
                return R.drawable.gs_calendar_add_on_vd_theme_24;
            case 42:
                return R.drawable.gs_calendar_add_on_rond100_vd_theme_24;
            case 43:
                return R.drawable.gs_calendar_month_vd_theme_24;
            case 44:
                return R.drawable.gs_calendar_today_vd_theme_24;
            case 45:
                return R.drawable.gs_call_vd_theme_24;
            case 46:
                return R.drawable.gs_call_end_vd_theme_24;
            case 47:
                return R.drawable.gs_call_end_fill1_vd_theme_24;
            case 48:
                return R.drawable.gs_call_fill1_vd_theme_24;
            case Maneuver.TYPE_FERRY_TRAIN_LEFT /* 49 */:
                return R.drawable.gs_call_merge_vd_theme_24;
            case 50:
                return R.drawable.ic_top_app_bar_call_dialer;
            case 51:
                return R.drawable.gs_cancel_vd_theme_24;
            case 52:
                return R.drawable.gs_cancel_fill1_vd_theme_24;
            case 53:
                return R.drawable.ic_cancel_filled_no_padding;
            case 54:
                return R.drawable.gs_chat_vd_theme_24;
            case 55:
                return R.drawable.gs_chat_bubble_vd_theme_24;
            case 56:
                return R.drawable.gs_chat_mirror_vd_theme_24;
            case 57:
                return R.drawable.gs_check_vd_theme_24;
            case 58:
                return R.drawable.gs_check_circle_vd_theme_24;
            case 59:
                return R.drawable.gs_check_circle_fill1_vd_theme_24;
            case 60:
                return R.drawable.gs_chevron_left_vd_theme_24;
            case 61:
                return R.drawable.gs_chevron_right_vd_theme_24;
            case 62:
                return R.drawable.gs_close_vd_theme_24;
            case Function.ALT_CONVENTION /* 63 */:
                return R.drawable.gs_close_fullscreen_vd_theme_24;
            case 64:
                return R.drawable.gs_cloud_off_vd_theme_24;
            case 65:
                return R.drawable.gs_comments_disabled_vd_theme_24;
            case 66:
                return R.drawable.gs_compare_arrows_vd_theme_24;
            case 67:
                return R.drawable.ic_compose_add_legacy;
            case 68:
                return R.drawable.ic_compose_add_legacy_selected;
            case 69:
                return R.drawable.ic_compose_emoji;
            case 70:
                return R.drawable.ic_compose_emoji_selected;
            case 71:
                return R.drawable.ic_compose_gallery;
            case 72:
                return R.drawable.ic_compose_gallery_legacy;
            case 73:
                return R.drawable.ic_compose_gallery_legacy_selected;
            case 74:
                return R.drawable.ic_compose_gallery_selected;
            case 75:
                return R.drawable.ic_compose_magic_compose;
            case 76:
                return R.drawable.ic_compose_magic_compose_selected;
            case 77:
                return R.drawable.ic_compose_sim;
            case 78:
                return R.drawable.ic_compose_sim_filled;
            case 79:
                return R.drawable.ic_compose_voice_filled;
            case CarZone.CAR_ZONE_COLUMN_DRIVER /* 80 */:
                return R.drawable.gs_contacts_vd_theme_24;
            case 81:
                return R.drawable.gs_contacts_product_vd_theme_24;
            case 82:
                return R.drawable.gs_content_copy_vd_theme_24;
            case 83:
                return R.drawable.gs_crop_vd_theme_24;
            case 84:
                return R.drawable.gs_delete_vd_theme_24;
            case 85:
                return R.drawable.gs_delete_rond100_vd_theme_24;
            case 86:
                return R.drawable.gs_description_vd_theme_24;
            case 87:
                return R.drawable.gs_devices_vd_theme_24;
            case 88:
                return R.drawable.gs_dialpad_vd_theme_24;
            case 89:
                return R.drawable.gs_directions_car_fill1_vd_theme_24;
            case 90:
                return R.drawable.gs_dogfood_vd_theme_24;
            case 91:
                return R.drawable.gs_domain_vd_theme_24;
            case 92:
                return R.drawable.gs_download_vd_theme_24;
            case 93:
                return R.drawable.gs_downloading_vd_theme_24;
            case 94:
                return R.drawable.gs_draft_vd_theme_24;
            case 95:
                return R.drawable.gs_drive_pdf_vd_theme_24;
            case CarZone.CAR_ZONE_COLUMN_PASSENGER /* 96 */:
                return R.drawable.gs_drive_presentation_vd_theme_24;
            case 97:
                return R.drawable.gs_drive_spreadsheet_vd_theme_24;
            case 98:
                return R.drawable.gs_drive_zip_vd_theme_24;
            case 99:
                return R.drawable.gs_edit_vd_theme_24;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return R.drawable.gs_emergency_vd_theme_24;
            case EnergyProfile.EVCONNECTOR_TYPE_OTHER /* 101 */:
                return R.drawable.ic_emergency_circle;
            case 102:
                return R.drawable.gs_encryption_shield_vd_theme_24;
            case 103:
                return R.drawable.gs_error_vd_theme_24;
            case 104:
                return R.drawable.gs_error_fill1_vd_theme_24;
            case 105:
                return R.drawable.gs_event_vd_theme_24;
            case 106:
                return R.drawable.gs_expand_less_vd_theme_24;
            case 107:
                return R.drawable.gs_expand_more_vd_theme_24;
            case 108:
                return R.drawable.gs_experiment_vd_theme_24;
            case 109:
                return R.drawable.gs_extension_vd_theme_24;
            case 110:
                return R.drawable.gs_fact_check_vd_theme_24;
            case 111:
                return R.drawable.gs_favorite_vd_theme_24;
            case 112:
                return R.drawable.gs_fiber_manual_record_fill1_vd_theme_24;
            case 113:
                return R.drawable.gs_find_in_page_vd_theme_24;
            case 114:
                return R.drawable.gs_flag_vd_theme_24;
            case 115:
                return R.drawable.gs_fmd_bad_fill1_vd_theme_24;
            case 116:
                return R.drawable.gs_folder_copy_vd_theme_24;
            case 117:
                return R.drawable.gs_format_size_vd_theme_24;
            case 118:
                return R.drawable.gs_forward_vd_theme_24;
            case 119:
                return R.drawable.gs_forward_rond100_vd_theme_24;
            case 120:
                return R.drawable.gs_fullscreen_vd_theme_24;
            case 121:
                return R.drawable.gemini_spark;
            case 122:
                return R.drawable.gemini_spark_filled;
            case 123:
                return R.drawable.gs_google_vd_theme_24;
            case 124:
                return R.drawable.gs_google_messages_vd_theme_24;
            case 125:
                return R.drawable.gs_google_messages_fill1_vd_theme_24;
            case 126:
                return R.drawable.gs_gpp_maybe_vd_theme_24;
            case 127:
                return R.drawable.gs_gpp_maybe_fill1_vd_theme_24;
            case 128:
                return R.drawable.gs_group_vd_theme_24;
            case 129:
                return R.drawable.gs_groups_vd_theme_24;
            case 130:
                return R.drawable.gs_group_add_vd_theme_24;
            case 131:
                return R.drawable.gs_group_add_fill1_vd_theme_24;
            case 132:
                return R.drawable.gs_group_fill1_vd_theme_24;
            case 133:
                return R.drawable.gs_group_off_vd_theme_24;
            case 134:
                return R.drawable.gs_group_remove_vd_theme_24;
            case 135:
                return R.drawable.gs_gshield_vd_theme_24;
            case 136:
                return R.drawable.gs_g_translate_vd_theme_24;
            case 137:
                return R.drawable.gs_handyman_vd_theme_24;
            case 138:
                return R.drawable.gs_hd_fill1_vd_theme_24;
            case 139:
                return R.drawable.ic_hd_plus_filled;
            case 140:
                return R.drawable.gs_headphones_vd_theme_24;
            case 141:
                return R.drawable.gs_headphones_fill1_vd_theme_24;
            case 142:
                return R.drawable.gs_help_vd_theme_24;
            case 143:
                return R.drawable.gs_help_fill1_vd_theme_24;
            case 144:
                return R.drawable.gs_hide_vd_theme_24;
            case 145:
                return R.drawable.gs_hide_image_vd_theme_24;
            case 146:
                return R.drawable.gs_history_vd_theme_24;
            case 147:
                return R.drawable.gs_image_vd_theme_24;
            case 148:
                return R.drawable.gs_info_vd_theme_24;
            case 149:
                return R.drawable.gs_info_fill1_vd_theme_24;
            case 150:
                return R.drawable.gs_info_spark_vd_theme_24;
            case 151:
                return R.drawable.gs_inventory_2_vd_theme_24;
            case 152:
                return R.drawable.gs_keep_vd_theme_24;
            case 153:
                return R.drawable.gs_keyboard_vd_theme_24;
            case 154:
                return R.drawable.gs_keyboard_arrow_down_vd_theme_24;
            case 155:
                return R.drawable.gs_keyboard_arrow_up_vd_theme_24;
            case 156:
                return R.drawable.gs_language_vd_theme_24;
            case 157:
                return R.drawable.gs_link_vd_theme_24;
            case 158:
                return R.drawable.gs_list_vd_theme_24;
            case 159:
                return R.drawable.gs_list_alt_vd_theme_24;
            case 160:
                return R.drawable.gs_local_fire_department_fill1_vd_theme_24;
            case 161:
                return R.drawable.gs_local_hospital_fill1_vd_theme_24;
            case 162:
                return R.drawable.gs_local_police_fill1_vd_theme_24;
            case 163:
                return R.drawable.gs_location_chip_vd_theme_24;
            case 164:
                return R.drawable.gs_location_on_vd_theme_24;
            case 165:
                return R.drawable.gs_lock_vd_theme_24;
            case 166:
                return R.drawable.gs_no_encryption_vd_theme_24;
            case 167:
                return R.drawable.gs_lock_open_vd_theme_24;
            case 168:
                return R.drawable.gs_lock_person_vd_theme_24;
            case 169:
                return R.drawable.gs_logout_vd_theme_24;
            case 170:
                return R.drawable.gs_magic_button_fill1_vd_theme_24;
            case 171:
                return R.drawable.ic_messages;
            case 172:
                return R.drawable.ic_messages_spark;
            case 173:
                return R.drawable.ic_messages_spark_filled;
            case 174:
                return R.drawable.gs_mic_vd_theme_24;
            case 175:
                return R.drawable.gs_mic_fill1_vd_theme_24;
            case 176:
                return R.drawable.gs_mic_off_vd_theme_24;
            case 177:
                return R.drawable.gs_mic_off_fill1_vd_theme_24;
            case 178:
                return R.drawable.gs_mms_vd_theme_24;
            case 179:
                return R.drawable.gs_mode_night_vd_theme_24;
            case 180:
                return R.drawable.gs_mood_vd_theme_24;
            case 181:
                return R.drawable.gs_mood_fill1_vd_theme_24;
            case 182:
                return R.drawable.gs_more_horiz_vd_theme_24;
            case 183:
                return R.drawable.gs_more_time_vd_theme_24;
            case 184:
                return R.drawable.gs_more_vert_vd_theme_24;
            case 185:
                return R.drawable.gs_movie_vd_theme_24;
            case 186:
                return R.drawable.gs_my_location_fill1_vd_theme_24;
            case 187:
                return R.drawable.gs_notifications_vd_theme_24;
            case 188:
                return R.drawable.gs_notifications_off_vd_theme_24;
            case 189:
                return R.drawable.gs_notifications_off_fill1_vd_theme_24;
            case 190:
                return R.drawable.gs_no_accounts_vd_theme_24;
            case 191:
                return R.drawable.gs_open_in_full_vd_theme_24;
            case 192:
                return R.drawable.gs_send_to_mobile_vd_theme_24;
            case 193:
                return R.drawable.gs_palette_vd_theme_24;
            case 194:
                return R.drawable.gs_partly_cloudy_day_vd_theme_24;
            case 195:
                return R.drawable.gs_pause_vd_theme_24;
            case 196:
                return R.drawable.gs_pause_circle_vd_theme_24;
            case 197:
                return R.drawable.gs_pause_circle_fill1_vd_theme_24;
            case 198:
                return R.drawable.gs_pause_fill1_vd_theme_24;
            case 199:
                return R.drawable.gs_pending_vd_theme_24;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return R.drawable.gs_pen_spark_vd_theme_24;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return R.drawable.gs_pen_spark_fill1_vd_theme_24;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return R.drawable.gs_people_vd_theme_24;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return R.drawable.gs_person_vd_theme_24;
            case 204:
                return R.drawable.gs_person_add_vd_theme_24;
            case 205:
                return R.drawable.gs_person_add_fill1_vd_theme_24;
            case 206:
                return R.drawable.gs_person_fill1_vd_theme_24;
            case 207:
                return R.drawable.gs_person_off_vd_theme_24;
            case 208:
                return R.drawable.gs_phonelink_erase_vd_theme_24;
            case 209:
                return R.drawable.comms_ic_phone_spark_vd_24;
            case 210:
                return R.drawable.gs_photo_vd_theme_24;
            case 211:
                return R.drawable.gs_photo_camera_vd_theme_24;
            case 212:
                return R.drawable.gs_pin_drop_vd_theme_24;
            case 213:
                return R.drawable.gs_play_arrow_vd_theme_24;
            case 214:
                return R.drawable.gs_play_arrow_fill1_vd_theme_24;
            case 215:
                return R.drawable.gs_play_circle_vd_theme_24;
            case 216:
                return R.drawable.gs_play_circle_fill1_vd_theme_24;
            case 217:
                return R.drawable.gs_public_vd_theme_24;
            case 218:
                return R.drawable.gs_qr_code_vd_theme_24;
            case 219:
                return R.drawable.gs_radio_button_checked_vd_theme_24;
            case 220:
                return R.drawable.ic_rcs_badge;
            case 221:
                return R.drawable.gs_refresh_vd_theme_24;
            case 222:
                return R.drawable.gs_reply_vd_theme_24;
            case 223:
                return R.drawable.gs_report_vd_theme_24;
            case 224:
                return R.drawable.gs_report_fill1_vd_theme_24;
            case 225:
                return R.drawable.gs_restaurant_vd_theme_24;
            case 226:
                return R.drawable.gs_rtt_vd_theme_24;
            case 227:
                return R.drawable.gs_satellite_vd_theme_24;
            case 228:
                return R.drawable.gs_satellite_alt_vd_theme_24;
            case 229:
                return R.drawable.gs_save_vd_theme_24;
            case 230:
                return R.drawable.gs_screen_rotation_vd_theme_24;
            case 231:
                return R.drawable.gs_search_vd_theme_24;
            case 232:
                return R.drawable.gs_select_all_vd_theme_24;
            case 233:
                return R.drawable.ic_selfie_gif;
            case 234:
                return R.drawable.ic_compose_send_no_modifier;
            case 235:
                return R.drawable.ic_compose_send_encrypted;
            case 236:
                return R.drawable.ic_compose_send_scheduled;
            case 237:
                return R.drawable.ic_compose_send_spark;
            case 238:
                return R.drawable.gs_sentiment_frustrated_vd_theme_24;
            case 239:
                return R.drawable.gs_sentiment_sad_vd_theme_24;
            case 240:
                return R.drawable.gs_settings_vd_theme_24;
            case 241:
                return R.drawable.gs_share_vd_theme_24;
            case 242:
                return R.drawable.gs_shield_locked_vd_theme_24;
            case 243:
                return R.drawable.gs_shield_spark_fill1_vd_theme_24;
            case 244:
                return R.drawable.gs_sim_card_vd_theme_24;
            case 245:
                return R.drawable.gs_smartphone_vd_theme_24;
            case 246:
                return R.drawable.gs_smartphone_fill1_vd_theme_24;
            case 247:
                return R.drawable.gs_sms_vd_theme_24;
            case 248:
                return R.drawable.gs_sms_failed_vd_theme_24;
            case 249:
                return R.drawable.gs_snooze_vd_theme_24;
            case 250:
                return R.drawable.gs_sort_by_alpha_vd_theme_24;
            case 251:
                return R.drawable.gs_sos_vd_theme_24;
            case 252:
                return R.drawable.gs_spark_vd_theme_24;
            case 253:
                return R.drawable.ic_sparkle_gallery;
            case 254:
                return R.drawable.gs_speech_to_text_vd_theme_24;
            case 255:
                return R.drawable.gs_star_vd_theme_24;
            case 256:
                return R.drawable.ic_start_chat;
            case 257:
                return R.drawable.gs_star_fill1_vd_theme_24;
            case 258:
                return R.drawable.gs_star_rond100_vd_theme_24;
            case 259:
                return R.drawable.ic_status_delivered;
            case 260:
                return R.drawable.ic_status_dots;
            case 261:
                return R.drawable.ic_status_double_check;
            case 262:
                return R.drawable.ic_status_double_check_v2;
            case 263:
                return R.drawable.ic_status_gemini;
            case 264:
                return R.drawable.ic_status_read;
            case 265:
                return R.drawable.ic_status_sending;
            case 266:
                return R.drawable.ic_status_sent;
            case 267:
                return R.drawable.ic_status_single_check;
            case 268:
                return R.drawable.gs_subtitles_vd_theme_24;
            case 269:
                return R.drawable.gs_summarize_auto_vd_theme_24;
            case 270:
                return R.drawable.gs_sunny_vd_theme_24;
            case 271:
                return R.drawable.gs_support_agent_vd_theme_24;
            case 272:
                return R.drawable.gs_swap_calls_vd_theme_24;
            case 273:
                return R.drawable.gs_swap_horiz_vd_theme_24;
            case 274:
                return R.drawable.gs_swap_vert_vd_theme_24;
            case 275:
                return R.drawable.gs_swipe_vd_theme_24;
            case 276:
                return R.drawable.gs_switch_account_vd_theme_24;
            case 277:
                return R.drawable.ic_switch_phone_to_watch;
            case 278:
                return R.drawable.ic_switch_watch_to_phone;
            case 279:
                return R.drawable.gs_thumb_down_vd_theme_24;
            case 280:
                return R.drawable.gs_thumb_up_vd_theme_24;
            case 281:
                return R.drawable.gs_title_vd_theme_24;
            case 282:
                return R.drawable.gs_toggle_on_vd_theme_24;
            case 283:
                return R.drawable.gs_trending_up_vd_theme_24;
            case 284:
                return R.drawable.ic_verified_badge;
            case 285:
                return R.drawable.gs_verified_user_vd_theme_24;
            case 286:
                return R.drawable.gs_verified_user_fill1_vd_theme_24;
            case 287:
                return R.drawable.gs_vertical_align_bottom_vd_theme_24;
            case 288:
                return R.drawable.gs_vertical_align_center_vd_theme_24;
            case 289:
                return R.drawable.gs_vertical_align_top_vd_theme_24;
            case 290:
                return R.drawable.comms_gm_ic_videocam_vd_theme_24;
            case 291:
                return R.drawable.gs_videocam_fill1_vd_theme_24;
            case 292:
                return R.drawable.gs_videocam_off_vd_theme_24;
            case 293:
                return R.drawable.comms_gm_ic_videocam_one_way_vd_theme_24;
            case 294:
                return R.drawable.gs_videocam_rond100_vd_theme_24;
            case 295:
                return R.drawable.gs_view_carousel_vd_theme_24;
            case 296:
                return R.drawable.gs_visibility_vd_theme_24;
            case 297:
                return R.drawable.gs_visibility_off_vd_theme_24;
            case 298:
                return R.drawable.gs_voicemail_vd_theme_24;
            case 299:
                return R.drawable.gs_volume_off_vd_theme_24;
            case 300:
                return R.drawable.gs_volume_off_fill1_vd_theme_24;
            case 301:
                return R.drawable.gs_volume_up_vd_theme_24;
            case 302:
                return R.drawable.gs_volume_up_fill1_vd_theme_24;
            case 303:
                return R.drawable.gs_volunteer_activism_vd_theme_24;
            case 304:
                return R.drawable.gs_warning_vd_theme_24;
            case 305:
                return R.drawable.gs_watch_vd_theme_24;
            case 306:
                return R.drawable.ic_whatsapp;
            case 307:
                return R.drawable.gs_wifi_vd_theme_24;
            case 308:
                return R.drawable.gs_signal_wifi_4_bar_fill1_vd_theme_24;
            case 309:
                return R.drawable.gs_wifi_off_vd_theme_24;
            case 310:
                return R.drawable.gs_work_fill1_vd_theme_24;
            default:
                throw new fctg();
        }
    }
}
