package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dlim {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    private final long G;
    private final long H;
    private final long I;
    private final long J;
    public final dtic a;
    public final dlij b;
    public final dljj c;
    public final dlih d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final boolean l;
    public final boolean m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public dlim(dtic dticVar, dlij dlijVar, dljj dljjVar, dlih dlihVar, long j, long j2, long j3, long j4, long j5, long j6, long j7, boolean z, boolean z2, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30) {
        dticVar.getClass();
        dljjVar.getClass();
        this.a = dticVar;
        this.b = dlijVar;
        this.c = dljjVar;
        this.d = dlihVar;
        this.e = j;
        this.f = j2;
        this.g = j3;
        this.h = j4;
        this.i = j5;
        this.j = j6;
        this.k = j7;
        this.l = z;
        this.m = z2;
        this.n = j8;
        this.o = j9;
        this.p = j10;
        this.q = j11;
        this.r = j12;
        this.s = j13;
        this.t = j14;
        this.G = j15;
        this.u = j16;
        this.H = j17;
        this.v = j18;
        this.w = j19;
        this.x = j20;
        this.y = j21;
        this.z = j22;
        this.A = j23;
        this.B = j24;
        this.C = j25;
        this.I = j26;
        this.D = j27;
        this.J = j28;
        this.E = j29;
        this.F = j30;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof dlim)) {
            return false;
        }
        dlim dlimVar = (dlim) obj;
        if (!fdbq.f(this.a, dlimVar.a) || !fdbq.f(this.b, dlimVar.b) || !fdbq.f(this.c, dlimVar.c) || !fdbq.f(this.d, dlimVar.d)) {
            return false;
        }
        long j = this.e;
        long j2 = dlimVar.e;
        long j3 = ije.a;
        return fcts.a(j, j2) && fcts.a(this.f, dlimVar.f) && fcts.a(this.g, dlimVar.g) && fcts.a(this.h, dlimVar.h) && fcts.a(this.i, dlimVar.i) && fcts.a(this.j, dlimVar.j) && fcts.a(this.k, dlimVar.k) && this.l == dlimVar.l && this.m == dlimVar.m && fcts.a(this.n, dlimVar.n) && fcts.a(this.o, dlimVar.o) && fcts.a(this.p, dlimVar.p) && fcts.a(this.q, dlimVar.q) && fcts.a(this.r, dlimVar.r) && fcts.a(this.s, dlimVar.s) && fcts.a(this.t, dlimVar.t) && fcts.a(this.G, dlimVar.G) && fcts.a(this.u, dlimVar.u) && fcts.a(this.H, dlimVar.H) && fcts.a(this.v, dlimVar.v) && fcts.a(this.w, dlimVar.w) && fcts.a(this.x, dlimVar.x) && fcts.a(this.y, dlimVar.y) && fcts.a(this.z, dlimVar.z) && fcts.a(this.A, dlimVar.A) && fcts.a(this.B, dlimVar.B) && fcts.a(this.C, dlimVar.C) && fcts.a(this.I, dlimVar.I) && fcts.a(this.D, dlimVar.D) && fcts.a(this.J, dlimVar.J) && fcts.a(this.E, dlimVar.E) && fcts.a(this.F, dlimVar.F);
    }

    public final int hashCode() {
        int iHashCode = (((((this.a.hashCode() * 31) + this.b.hashCode()) * 31) + this.c.hashCode()) * 31) + this.d.hashCode();
        long j = ije.a;
        long j2 = this.e;
        long j3 = this.f;
        int iA = ((iHashCode * 31) + fctr.a(j2)) * 31;
        long j4 = this.g;
        int iA2 = (iA + fctr.a(j3)) * 31;
        long j5 = this.h;
        int iA3 = (iA2 + fctr.a(j4)) * 31;
        long j6 = this.i;
        int iA4 = (iA3 + fctr.a(j5)) * 31;
        long j7 = this.j;
        int iA5 = (iA4 + fctr.a(j6)) * 31;
        long j8 = this.k;
        int iA6 = (iA5 + fctr.a(j7)) * 31;
        boolean z = this.l;
        int iA7 = (iA6 + fctr.a(j8)) * 31;
        boolean z2 = this.m;
        int iA8 = (iA7 + dlil.a(z)) * 31;
        long j9 = this.n;
        int iA9 = (iA8 + dlil.a(z2)) * 31;
        long j10 = this.o;
        int iA10 = (iA9 + fctr.a(j9)) * 31;
        long j11 = this.p;
        int iA11 = (iA10 + fctr.a(j10)) * 31;
        long j12 = this.q;
        int iA12 = (iA11 + fctr.a(j11)) * 31;
        long j13 = this.r;
        int iA13 = (iA12 + fctr.a(j12)) * 31;
        long j14 = this.s;
        int iA14 = (iA13 + fctr.a(j13)) * 31;
        long j15 = this.t;
        int iA15 = (iA14 + fctr.a(j14)) * 31;
        long j16 = this.G;
        int iA16 = (iA15 + fctr.a(j15)) * 31;
        long j17 = this.u;
        int iA17 = (iA16 + fctr.a(j16)) * 31;
        long j18 = this.H;
        int iA18 = (iA17 + fctr.a(j17)) * 31;
        long j19 = this.v;
        int iA19 = (iA18 + fctr.a(j18)) * 31;
        long j20 = this.w;
        return ((((((((((((((((((((((((iA19 + fctr.a(j19)) * 31) + fctr.a(j20)) * 31) + fctr.a(this.x)) * 31) + fctr.a(this.y)) * 31) + fctr.a(this.z)) * 31) + fctr.a(this.A)) * 31) + fctr.a(this.B)) * 31) + fctr.a(this.C)) * 31) + fctr.a(this.I)) * 31) + fctr.a(this.D)) * 31) + fctr.a(this.J)) * 31) + fctr.a(this.E)) * 31) + fctr.a(this.F);
    }

    public final String toString() {
        long j = this.F;
        long j2 = this.E;
        long j3 = this.J;
        long j4 = this.D;
        long j5 = this.I;
        long j6 = this.C;
        long j7 = this.B;
        long j8 = this.A;
        long j9 = this.z;
        long j10 = this.y;
        long j11 = this.x;
        long j12 = this.w;
        long j13 = this.v;
        long j14 = this.H;
        long j15 = this.u;
        long j16 = this.G;
        long j17 = this.t;
        long j18 = this.s;
        long j19 = this.r;
        long j20 = this.q;
        long j21 = this.p;
        long j22 = this.o;
        long j23 = this.n;
        long j24 = this.k;
        long j25 = this.j;
        long j26 = this.i;
        long j27 = this.h;
        long j28 = this.g;
        long j29 = this.f;
        String strG = ije.g(this.e);
        String strG2 = ije.g(j29);
        String strG3 = ije.g(j28);
        String strG4 = ije.g(j27);
        String strG5 = ije.g(j26);
        String strG6 = ije.g(j25);
        String strG7 = ije.g(j24);
        String strG8 = ije.g(j23);
        String strG9 = ije.g(j22);
        String strG10 = ije.g(j21);
        String strG11 = ije.g(j20);
        String strG12 = ije.g(j19);
        String strG13 = ije.g(j18);
        String strG14 = ije.g(j17);
        String strG15 = ije.g(j16);
        String strG16 = ije.g(j15);
        String strG17 = ije.g(j14);
        String strG18 = ije.g(j13);
        String strG19 = ije.g(j12);
        String strG20 = ije.g(j11);
        String strG21 = ije.g(j10);
        String strG22 = ije.g(j9);
        String strG23 = ije.g(j8);
        String strG24 = ije.g(j7);
        String strG25 = ije.g(j6);
        String strG26 = ije.g(j5);
        String strG27 = ije.g(j4);
        String strG28 = ije.g(j3);
        String strG29 = ije.g(j2);
        String strG30 = ije.g(j);
        StringBuilder sb = new StringBuilder("AbcColorScheme(tonalPalette=");
        sb.append(this.a);
        sb.append(", bubbleColors=");
        sb.append(this.b);
        sb.append(", monogramColors=");
        sb.append(this.c);
        sb.append(", backgroundColors=");
        sb.append(this.d);
        sb.append(", searchHighlight=");
        sb.append(strG);
        sb.append(", onSearchHighlight=");
        sb.append(strG2);
        sb.append(", searchHighlightFocused=");
        sb.append(strG3);
        sb.append(", onSearchHighlightFocused=");
        sb.append(strG4);
        sb.append(", mediaControlsBackground=");
        sb.append(strG5);
        sb.append(", mediaControlsTint=");
        sb.append(strG6);
        sb.append(", scrim=");
        sb.append(strG7);
        boolean z = this.m;
        boolean z2 = this.l;
        sb.append(", isDarkTheme=");
        sb.append(z2);
        sb.append(", isRichConversationTheme=");
        sb.append(z);
        sb.append(", emergencyRed=");
        sb.append(strG8);
        sb.append(", onEmergencyRed=");
        sb.append(strG9);
        sb.append(", recordingDotIndicator=");
        sb.append(strG10);
        sb.append(", swipeUpToLockPillBackground=");
        sb.append(strG11);
        sb.append(", swipeUpToLockPillIcon=");
        sb.append(strG12);
        sb.append(", bannerErrorBackground=");
        sb.append(strG13);
        sb.append(", genAiBackgroundStart=");
        sb.append(strG14);
        sb.append(", genAiBackgroundMiddle=");
        sb.append(strG15);
        sb.append(", genAiBackgroundEnd=");
        sb.append(strG16);
        sb.append(", solidAccentOnGenAiBackground=");
        sb.append(strG17);
        sb.append(", accentOnGenAiBackgroundStart=");
        sb.append(strG18);
        sb.append(", accentOnGenAiBackgroundEnd=");
        sb.append(strG19);
        sb.append(", geminiGradientStart=");
        sb.append(strG20);
        sb.append(", geminiGradientMiddle=");
        sb.append(strG21);
        sb.append(", geminiGradientEnd=");
        sb.append(strG22);
        sb.append(", onGenAiBackground=");
        sb.append(strG23);
        sb.append(", voiceMoodHighlight=");
        sb.append(strG24);
        sb.append(", semanticGreen=");
        sb.append(strG25);
        sb.append(", onSemanticGreen=");
        sb.append(strG26);
        sb.append(", semanticRed=");
        sb.append(strG27);
        sb.append(", onSemanticRed=");
        sb.append(strG28);
        sb.append(", backgroundSamsung=");
        sb.append(strG29);
        sb.append(", surfaceBlueChip=");
        sb.append(strG30);
        sb.append(")");
        return sb.toString();
    }
}
