package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dtjj {
    public static final kbj U;
    public static final kcc V;
    public static final kca W;
    public static final kbj X;
    public static final kcc Y;
    public static final kca Z;
    public static final kca aA;
    public static final kbj aB;
    public static final kcc aC;
    public static final kca aD;
    public static final kbj aE;
    public static final kcc aF;
    public static final kca aG;
    public static final kbj aH;
    public static final kcc aI;
    public static final kca aJ;
    public static final kbj aK;
    public static final kcc aL;
    public static final kbj aa;
    public static final kcc ab;
    public static final kca ac;
    public static final kbj ad;
    public static final kcc ae;
    public static final kca af;
    public static final kbj ag;
    public static final kcc ah;
    public static final kca ai;
    public static final kbj aj;
    public static final kcc ak;
    public static final kca al;
    public static final kbj am;
    public static final kcc an;
    public static final kca ao;
    public static final kbj ap;
    public static final kcc aq;
    public static final kca ar;
    public static final kbj as;
    public static final kcc at;
    public static final kca au;
    public static final kbj av;
    public static final kcc aw;
    public static final kca ax;
    public static final kbj ay;
    public static final kcc az;
    public static final long a = kjm.a(24.0d);
    private static final float aM = 16.0f;
    private static final float aN = 100.0f;
    public static final long b = kjm.c(16);
    public static final long c = kjm.a(0.0d);
    private static final float aO = 100.0f;
    private static final float aP = 500.0f;
    public static final long d = kjm.a(20.0d);
    private static final float aQ = 14.0f;
    private static final float aR = 100.0f;
    public static final long e = kjm.c(14);
    public static final long f = kjm.a(0.0d);
    private static final float aS = 100.0f;
    private static final float aT = 500.0f;
    public static final long g = kjm.a(16.0d);
    private static final float aU = 12.0f;
    private static final float aV = 100.0f;
    public static final long h = kjm.c(12);
    public static final long i = kjm.a(0.0d);
    private static final float aW = 100.0f;
    private static final float aX = 500.0f;
    public static final long j = kjm.a(64.0d);
    private static final float aY = 57.0f;
    private static final float aZ = 100.0f;
    public static final long k = kjm.c(57);
    public static final long l = kjm.a(0.0d);
    private static final float ba = 100.0f;
    private static final float bb = 500.0f;
    public static final long m = kjm.a(52.0d);
    private static final float bc = 45.0f;
    private static final float bd = 100.0f;
    public static final long n = kjm.c(45);
    public static final long o = kjm.a(0.0d);
    private static final float be = 100.0f;
    private static final float bf = 500.0f;
    public static final long p = kjm.a(44.0d);
    private static final float bg = 36.0f;
    private static final float bh = 100.0f;
    public static final long q = kjm.c(36);
    public static final long r = kjm.a(0.0d);
    private static final float bi = 100.0f;
    private static final float bj = 500.0f;
    public static final long s = kjm.a(40.0d);
    private static final float bk = 32.0f;
    private static final float bl = 100.0f;
    public static final long t = kjm.c(32);
    public static final long u = kjm.a(0.0d);
    private static final float bm = 100.0f;
    private static final float bn = 500.0f;
    public static final long v = kjm.a(36.0d);
    private static final float bo = 28.0f;
    private static final float bp = 100.0f;
    public static final long w = kjm.c(28);
    public static final long x = kjm.a(0.0d);
    private static final float bq = 100.0f;
    private static final float br = 500.0f;
    public static final long y = kjm.a(32.0d);
    private static final float bs = 24.0f;
    private static final float bt = 100.0f;
    public static final long z = kjm.c(24);
    public static final long A = kjm.a(0.0d);
    private static final float bu = 100.0f;
    private static final float bv = 500.0f;
    public static final long B = kjm.a(20.0d);
    private static final float bw = 14.0f;
    private static final float bx = 100.0f;
    public static final long C = kjm.c(14);
    public static final long D = kjm.a(0.0d);
    private static final float by = 100.0f;
    private static final float bz = 600.0f;
    public static final long E = kjm.a(16.0d);
    private static final float bA = 12.0f;
    private static final float bB = 100.0f;
    public static final long F = kjm.c(12);
    public static final long G = kjm.a(0.0d);
    private static final float bC = 100.0f;
    private static final float bD = 600.0f;
    public static final long H = kjm.a(16.0d);
    private static final float bE = 11.0f;
    private static final float bF = 100.0f;
    public static final long I = kjm.c(11);
    public static final long J = kjm.a(0.0d);
    private static final float bG = 100.0f;
    private static final float bH = 600.0f;
    public static final long K = kjm.a(28.0d);
    private static final float bI = 22.0f;
    private static final float bJ = 100.0f;
    public static final long L = kjm.c(22);
    public static final long M = kjm.a(0.0d);
    private static final float bK = 100.0f;
    private static final float bL = 500.0f;
    public static final long N = kjm.a(24.0d);
    private static final float bM = 16.0f;
    private static final float bN = 100.0f;
    public static final long O = kjm.c(16);
    public static final long P = kjm.a(0.0d);
    private static final float bO = 100.0f;
    private static final float bP = 600.0f;
    public static final long Q = kjm.a(20.0d);
    private static final float bQ = 14.0f;
    private static final float bR = 100.0f;
    public static final long R = kjm.c(14);
    public static final long S = kjm.a(0.0d);
    private static final float bS = 100.0f;
    private static final float bT = 600.0f;
    public static final kca T = new kca(kcb.a("ROND", 100.0f), kcb.a("slnt", 0.0f), kcb.a("opsz", 16.0f), kcb.a("GRAD", 0.0f), kcb.a("wdth", 100.0f), kcb.a("wght", 500.0f));

    static {
        kbj kbjVar = dtjc.a;
        U = dtjc.b;
        V = dtjc.d;
        W = new kca(kcb.a("GRAD", 0.0f), kcb.a("wght", 500.0f), kcb.a("opsz", 14.0f), kcb.a("slnt", 0.0f), kcb.a("wdth", 100.0f), kcb.a("ROND", 100.0f));
        X = dtjc.b;
        Y = dtjc.d;
        Z = new kca(kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f), kcb.a("GRAD", 0.0f), kcb.a("wght", 500.0f), kcb.a("opsz", 12.0f), kcb.a("ROND", 100.0f));
        aa = dtjc.b;
        ab = dtjc.d;
        ac = new kca(kcb.a("GRAD", 0.0f), kcb.a("ROND", 100.0f), kcb.a("opsz", 57.0f), kcb.a("wght", 500.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f));
        ad = dtjc.a;
        ae = dtjc.d;
        af = new kca(kcb.a("slnt", 0.0f), kcb.a("wdth", 100.0f), kcb.a("GRAD", 0.0f), kcb.a("wght", 500.0f), kcb.a("opsz", 45.0f), kcb.a("ROND", 100.0f));
        ag = dtjc.a;
        ah = dtjc.d;
        ai = new kca(kcb.a("opsz", 36.0f), kcb.a("wght", 500.0f), kcb.a("ROND", 100.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f), kcb.a("GRAD", 0.0f));
        aj = dtjc.a;
        ak = dtjc.d;
        al = new kca(kcb.a("slnt", 0.0f), kcb.a("GRAD", 0.0f), kcb.a("ROND", 100.0f), kcb.a("wdth", 100.0f), kcb.a("wght", 500.0f), kcb.a("opsz", 32.0f));
        am = dtjc.a;
        an = dtjc.d;
        ao = new kca(kcb.a("wght", 500.0f), kcb.a("GRAD", 0.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f), kcb.a("opsz", 28.0f), kcb.a("ROND", 100.0f));
        ap = dtjc.a;
        aq = dtjc.d;
        ar = new kca(kcb.a("GRAD", 0.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f), kcb.a("opsz", 24.0f), kcb.a("ROND", 100.0f), kcb.a("wght", 500.0f));
        as = dtjc.a;
        at = dtjc.d;
        au = new kca(kcb.a("wdth", 100.0f), kcb.a("opsz", 14.0f), kcb.a("wght", 600.0f), kcb.a("ROND", 100.0f), kcb.a("GRAD", 0.0f), kcb.a("slnt", 0.0f));
        av = dtjc.b;
        aw = dtjc.c;
        ax = new kca(kcb.a("wght", 600.0f), kcb.a("GRAD", 0.0f), kcb.a("ROND", 100.0f), kcb.a("slnt", 0.0f), kcb.a("wdth", 100.0f), kcb.a("opsz", 12.0f));
        ay = dtjc.b;
        az = dtjc.c;
        aA = new kca(kcb.a("wdth", 100.0f), kcb.a("wght", 600.0f), kcb.a("ROND", 100.0f), kcb.a("slnt", 0.0f), kcb.a("opsz", 11.0f), kcb.a("GRAD", 0.0f));
        aB = dtjc.b;
        aC = dtjc.c;
        aD = new kca(kcb.a("wght", 500.0f), kcb.a("ROND", 100.0f), kcb.a("slnt", 0.0f), kcb.a("GRAD", 0.0f), kcb.a("opsz", 22.0f), kcb.a("wdth", 100.0f));
        aE = dtjc.a;
        aF = dtjc.d;
        aG = new kca(kcb.a("ROND", 100.0f), kcb.a("opsz", 16.0f), kcb.a("GRAD", 0.0f), kcb.a("wght", 600.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f));
        aH = dtjc.b;
        aI = dtjc.c;
        aJ = new kca(kcb.a("wght", 600.0f), kcb.a("wdth", 100.0f), kcb.a("slnt", 0.0f), kcb.a("GRAD", 0.0f), kcb.a("opsz", 14.0f), kcb.a("ROND", 100.0f));
        aK = dtjc.b;
        aL = dtjc.c;
    }
}
