package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class dtkc {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final kcc D;
    public static final kbj E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final kcc I;
    public static final kbj J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final kcc N;
    public static final kbj O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final kcc S;
    public static final kbj T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final kcc X;
    public static final kbj Y;
    public static final long Z;
    public static final kbj a;
    public static final long aa;
    public static final long ab;
    public static final kcc ac;
    public static final kbj ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final kcc ah;
    public static final kbj ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final kcc am;
    public static final kbj an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final kcc ar;
    public static final kbj as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final kcc aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final kcc e;
    public static final kbj f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final kcc j;
    public static final kbj k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final kcc o;
    public static final kbj p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final kcc t;
    public static final kbj u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final kcc y;
    public static final kbj z;

    static {
        kbj kbjVar = dtkd.a;
        a = dtkd.b;
        b = kjm.a(24.0d);
        c = kjm.c(16);
        d = kjm.a(0.0d);
        e = dtkd.d;
        f = dtkd.b;
        g = kjm.a(20.0d);
        h = kjm.c(14);
        i = kjm.a(0.0d);
        j = dtkd.d;
        k = dtkd.b;
        l = kjm.a(16.0d);
        m = kjm.c(12);
        n = kjm.a(0.1d);
        o = dtkd.d;
        p = dtkd.a;
        q = kjm.a(64.0d);
        r = kjm.c(57);
        s = kjm.a(0.0d);
        t = dtkd.d;
        u = dtkd.a;
        v = kjm.a(52.0d);
        w = kjm.c(45);
        x = kjm.a(0.0d);
        y = dtkd.d;
        z = dtkd.a;
        A = kjm.a(44.0d);
        B = kjm.c(36);
        C = kjm.a(0.0d);
        D = dtkd.d;
        E = dtkd.a;
        F = kjm.a(40.0d);
        G = kjm.c(32);
        H = kjm.a(0.0d);
        I = dtkd.d;
        J = dtkd.a;
        K = kjm.a(36.0d);
        L = kjm.c(28);
        M = kjm.a(0.0d);
        N = dtkd.d;
        O = dtkd.a;
        P = kjm.a(32.0d);
        Q = kjm.c(24);
        R = kjm.a(0.0d);
        S = dtkd.d;
        T = dtkd.b;
        U = kjm.a(20.0d);
        V = kjm.c(14);
        W = kjm.a(0.0d);
        X = dtkd.c;
        Y = dtkd.b;
        Z = kjm.a(16.0d);
        aa = kjm.c(12);
        ab = kjm.a(0.1d);
        ac = dtkd.c;
        ad = dtkd.b;
        ae = kjm.a(16.0d);
        af = kjm.c(11);
        ag = kjm.a(0.1d);
        ah = dtkd.c;
        ai = dtkd.a;
        aj = kjm.a(28.0d);
        ak = kjm.c(22);
        al = kjm.a(0.0d);
        am = dtkd.d;
        an = dtkd.b;
        ao = kjm.a(24.0d);
        ap = kjm.c(16);
        aq = kjm.a(0.0d);
        ar = dtkd.c;
        as = dtkd.b;
        at = kjm.a(20.0d);
        au = kjm.c(14);
        av = kjm.a(0.0d);
        aw = dtkd.c;
    }
}
