package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes5.dex */
public final class eeod {
    public static final int[] a = {R.attr.height, R.attr.width, R.attr.color, com.google.android.apps.messaging.R.attr.expandedActiveIndicatorPaddingBottom, com.google.android.apps.messaging.R.attr.expandedActiveIndicatorPaddingEnd, com.google.android.apps.messaging.R.attr.expandedActiveIndicatorPaddingStart, com.google.android.apps.messaging.R.attr.expandedActiveIndicatorPaddingTop, com.google.android.apps.messaging.R.attr.expandedHeight, com.google.android.apps.messaging.R.attr.expandedMarginHorizontal, com.google.android.apps.messaging.R.attr.expandedWidth, com.google.android.apps.messaging.R.attr.marginHorizontal, com.google.android.apps.messaging.R.attr.shapeAppearance};
    public static final int[] b = {com.google.android.apps.messaging.R.attr.activeIndicatorLabelPadding, com.google.android.apps.messaging.R.attr.backgroundTint, com.google.android.apps.messaging.R.attr.elevation, com.google.android.apps.messaging.R.attr.horizontalItemTextAppearanceActive, com.google.android.apps.messaging.R.attr.horizontalItemTextAppearanceInactive, com.google.android.apps.messaging.R.attr.iconLabelHorizontalSpacing, com.google.android.apps.messaging.R.attr.itemActiveIndicatorStyle, com.google.android.apps.messaging.R.attr.itemBackground, com.google.android.apps.messaging.R.attr.itemGravity, com.google.android.apps.messaging.R.attr.itemIconGravity, com.google.android.apps.messaging.R.attr.itemIconSize, com.google.android.apps.messaging.R.attr.itemIconTint, com.google.android.apps.messaging.R.attr.itemPaddingBottom, com.google.android.apps.messaging.R.attr.itemPaddingTop, com.google.android.apps.messaging.R.attr.itemRippleColor, com.google.android.apps.messaging.R.attr.itemTextAppearanceActive, com.google.android.apps.messaging.R.attr.itemTextAppearanceActiveBoldEnabled, com.google.android.apps.messaging.R.attr.itemTextAppearanceInactive, com.google.android.apps.messaging.R.attr.itemTextColor, com.google.android.apps.messaging.R.attr.labelFontScalingEnabled, com.google.android.apps.messaging.R.attr.labelMaxLines, com.google.android.apps.messaging.R.attr.labelVisibilityMode, com.google.android.apps.messaging.R.attr.measureBottomPaddingFromLabelBaseline, com.google.android.apps.messaging.R.attr.menu};
}
