package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes5.dex */
public final class eeqg {
    public static final int[] a = {R.attr.textAppearance, R.attr.maxWidth, R.attr.text, R.attr.hint, com.google.android.apps.messaging.R.attr.backgroundTint, com.google.android.apps.messaging.R.attr.defaultMarginsEnabled, com.google.android.apps.messaging.R.attr.defaultScrollFlagsEnabled, com.google.android.apps.messaging.R.attr.elevation, com.google.android.apps.messaging.R.attr.forceDefaultNavigationOnClickListener, com.google.android.apps.messaging.R.attr.hideNavigationIcon, com.google.android.apps.messaging.R.attr.liftOnScroll, com.google.android.apps.messaging.R.attr.liftOnScrollColor, com.google.android.apps.messaging.R.attr.navigationIconTint, com.google.android.apps.messaging.R.attr.strokeColor, com.google.android.apps.messaging.R.attr.strokeWidth, com.google.android.apps.messaging.R.attr.textCentered, com.google.android.apps.messaging.R.attr.tintNavigationIcon};
    public static final int[] b = {R.attr.textAppearance, R.attr.focusable, R.attr.maxWidth, R.attr.text, R.attr.hint, R.attr.inputType, R.attr.imeOptions, com.google.android.apps.messaging.R.attr.animateMenuItems, com.google.android.apps.messaging.R.attr.animateNavigationIcon, com.google.android.apps.messaging.R.attr.autoShowKeyboard, com.google.android.apps.messaging.R.attr.backHandlingEnabled, com.google.android.apps.messaging.R.attr.backgroundTint, com.google.android.apps.messaging.R.attr.closeIcon, com.google.android.apps.messaging.R.attr.commitIcon, com.google.android.apps.messaging.R.attr.defaultQueryHint, com.google.android.apps.messaging.R.attr.goIcon, com.google.android.apps.messaging.R.attr.headerLayout, com.google.android.apps.messaging.R.attr.hideNavigationIcon, com.google.android.apps.messaging.R.attr.iconifiedByDefault, com.google.android.apps.messaging.R.attr.layout, com.google.android.apps.messaging.R.attr.queryBackground, com.google.android.apps.messaging.R.attr.queryHint, com.google.android.apps.messaging.R.attr.searchHintIcon, com.google.android.apps.messaging.R.attr.searchIcon, com.google.android.apps.messaging.R.attr.searchPrefixText, com.google.android.apps.messaging.R.attr.submitBackground, com.google.android.apps.messaging.R.attr.suggestionRowLayout, com.google.android.apps.messaging.R.attr.useDrawerArrowDrawable, com.google.android.apps.messaging.R.attr.voiceIcon};
}
