package defpackage;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

/* compiled from: PG */
/* loaded from: classes5.dex */
public final class eove {
    static final Map a;
    static final Map b;
    static final Map c;
    public static final /* synthetic */ int d = 0;

    static {
        Pattern.compile("^ +| +$|( )+");
        HashMap map = new HashMap(20);
        b = map;
        map.put((char) 197, 'A');
        map.put((char) 229, 'a');
        map.put((char) 196, 'A');
        map.put((char) 228, 'a');
        map.put((char) 224, 'a');
        map.put((char) 199, 'C');
        map.put((char) 201, 'E');
        map.put((char) 232, 'e');
        map.put((char) 233, 'e');
        map.put((char) 236, 'i');
        map.put((char) 209, 'N');
        map.put((char) 241, 'n');
        map.put((char) 214, 'O');
        map.put((char) 246, 'o');
        map.put((char) 242, 'o');
        map.put((char) 216, 'O');
        map.put((char) 248, 'o');
        map.put((char) 220, 'U');
        map.put((char) 252, 'u');
        map.put((char) 249, 'u');
        HashMap map2 = new HashMap(110);
        c = map2;
        map2.put((char) 0, ' ');
        map2.put((char) 1, ' ');
        map2.put((char) 2, ' ');
        map2.put((char) 3, ' ');
        map2.put((char) 4, ' ');
        map2.put((char) 5, ' ');
        map2.put((char) 6, ' ');
        map2.put((char) 7, ' ');
        map2.put('\b', ' ');
        map2.put('\t', ' ');
        map2.put('\n', ' ');
        map2.put((char) 11, ' ');
        map2.put('\f', ' ');
        map2.put('\r', ' ');
        map2.put((char) 14, ' ');
        map2.put((char) 15, ' ');
        map2.put((char) 17, ' ');
        map2.put((char) 18, ' ');
        map2.put((char) 19, ' ');
        map2.put((char) 20, ' ');
        map2.put((char) 21, ' ');
        map2.put((char) 22, ' ');
        map2.put((char) 23, ' ');
        map2.put((char) 24, ' ');
        map2.put((char) 25, ' ');
        map2.put((char) 26, ' ');
        map2.put((char) 27, ' ');
        map2.put((char) 28, ' ');
        map2.put((char) 29, ' ');
        map2.put((char) 30, ' ');
        map2.put((char) 31, ' ');
        map2.put((char) 127, ' ');
        map2.put((char) 128, ' ');
        map2.put((char) 129, ' ');
        map2.put((char) 130, ' ');
        map2.put((char) 131, ' ');
        map2.put((char) 132, ' ');
        map2.put((char) 133, ' ');
        map2.put((char) 134, ' ');
        map2.put((char) 135, ' ');
        map2.put((char) 136, ' ');
        map2.put((char) 137, ' ');
        map2.put((char) 138, ' ');
        map2.put((char) 139, ' ');
        map2.put((char) 140, ' ');
        map2.put((char) 141, ' ');
        map2.put((char) 142, ' ');
        map2.put((char) 143, ' ');
        map2.put((char) 144, ' ');
        map2.put((char) 145, ' ');
        map2.put((char) 146, ' ');
        map2.put((char) 147, ' ');
        map2.put((char) 148, ' ');
        map2.put((char) 149, ' ');
        map2.put((char) 150, ' ');
        map2.put((char) 151, ' ');
        map2.put((char) 152, ' ');
        map2.put((char) 153, ' ');
        map2.put((char) 154, ' ');
        map2.put((char) 155, ' ');
        map2.put((char) 156, ' ');
        map2.put((char) 157, ' ');
        map2.put((char) 158, ' ');
        map2.put((char) 159, ' ');
        map2.put((char) 160, ' ');
        map2.put((char) 5760, ' ');
        map2.put((char) 6158, ' ');
        map2.put((char) 8192, ' ');
        map2.put((char) 8193, ' ');
        map2.put((char) 8194, ' ');
        map2.put((char) 8195, ' ');
        map2.put((char) 8196, ' ');
        map2.put((char) 8197, ' ');
        map2.put((char) 8198, ' ');
        map2.put((char) 8199, ' ');
        map2.put((char) 8200, ' ');
        map2.put((char) 8201, ' ');
        map2.put((char) 8202, ' ');
        map2.put((char) 8203, ' ');
        map2.put((char) 8204, ' ');
        map2.put((char) 8205, ' ');
        map2.put((char) 8232, ' ');
        map2.put((char) 8233, ' ');
        map2.put((char) 8239, ' ');
        map2.put((char) 8287, ' ');
        map2.put((char) 8288, ' ');
        map2.put((char) 12288, ' ');
        map2.put((char) 65279, ' ');
        HashMap map3 = new HashMap(eovd.a.size() + map.size() + map2.size());
        a = map3;
        map3.putAll(eovd.a);
        map3.putAll(map2);
        map3.putAll(map);
    }
}
