package defpackage;

import com.sun.jna.Library;
import com.sun.jna.Native;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: PG */
/* loaded from: classes5.dex */
public final class eqbq {
    public static final eqbq A;
    public static final eqbq B;
    public static final eqbq C;
    public static final eqbq D;
    public static final eqbq E;
    public static final eqbq F;
    public static final eqbq G;
    public static final eqbq H;
    public static final eqbq I;
    public static final eqbq J;
    public static final eqbq K;
    public static final eqbq L;
    public static final eqbq M;
    public static final eqbq N;
    public static final eqbq O;
    public static final eqbq P;
    public static final eqbq Q;
    public static final eqbq R;
    public static final eqbq S;
    public static final eqbq T;
    public static final eqbq U;
    public static final eqbq V;
    public static final eqbq W;
    public static final eqbq X;
    public static final eqbq Y;
    public static final eqbq Z;
    public static final eqbq a;
    public static final eqbq aA;
    public static final eqbq aB;
    public static final eqbq aC;
    public static final eqbq aD;
    public static final /* synthetic */ fcza aE;
    private static final Class aF;
    private static final /* synthetic */ eqbq[] aG;
    public static final eqbq aa;
    public static final eqbq ab;
    public static final eqbq ac;
    public static final eqbq ad;
    public static final eqbq ae;
    public static final eqbq af;
    public static final eqbq ag;
    public static final eqbq ah;
    public static final eqbq ai;
    public static final eqbq aj;
    public static final eqbq ak;
    public static final eqbq al;
    public static final eqbq am;
    public static final eqbq an;
    public static final eqbq ao;
    public static final eqbq ap;
    public static final eqbq aq;
    public static final eqbq ar;
    public static final eqbq as;
    public static final eqbq at;
    public static final eqbq au;
    public static final eqbq av;
    public static final eqbq aw;
    public static final eqbq ax;
    public static final eqbq ay;
    public static final eqbq az;
    public static final eqbq b;
    public static final eqbq c;
    public static final eqbq d;
    public static final eqbq e;
    public static final eqbq f;
    public static final eqbq g;
    public static final eqbq h;
    public static final eqbq i;
    public static final eqbq j;
    public static final eqbq k;
    public static final eqbq l;
    public static final eqbq m;
    public static final eqbq n;
    public static final eqbq o;
    public static final eqbq p;
    public static final eqbq q;
    public static final eqbq r;
    public static final eqbq s;
    public static final eqbq t;
    public static final eqbq u;
    public static final eqbq v;
    public static final eqbq w;
    public static final eqbq x;
    public static final eqbq y;
    public static final eqbq z;

    static {
        eqbq eqbqVar = new eqbq("MissingMessage", 0);
        a = eqbqVar;
        eqbq eqbqVar2 = new eqbq("MissingGroupId", 1);
        b = eqbqVar2;
        eqbq eqbqVar3 = new eqbq("MissingMessageId", 2);
        c = eqbqVar3;
        eqbq eqbqVar4 = new eqbq("MissingEpochInMessageStorage", 3);
        d = eqbqVar4;
        eqbq eqbqVar5 = new eqbq("MissingPayload", 4);
        e = eqbqVar5;
        eqbq eqbqVar6 = new eqbq("CreateGroupError", 5);
        f = eqbqVar6;
        eqbq eqbqVar7 = new eqbq("JoinGroupError", 6);
        g = eqbqVar7;
        eqbq eqbqVar8 = new eqbq("EncryptMessageError", 7);
        h = eqbqVar8;
        eqbq eqbqVar9 = new eqbq("DecryptMessageError", 8);
        i = eqbqVar9;
        eqbq eqbqVar10 = new eqbq("MessageIdMismatch", 9);
        j = eqbqVar10;
        eqbq eqbqVar11 = new eqbq("ClientCreationError", 10);
        k = eqbqVar11;
        eqbq eqbqVar12 = new eqbq("RemoveFromGroupError", 11);
        l = eqbqVar12;
        eqbq eqbqVar13 = new eqbq("ProposeRemoveSelfFromGroupError", 12);
        m = eqbqVar13;
        eqbq eqbqVar14 = new eqbq("AddToGroupError", 13);
        n = eqbqVar14;
        eqbq eqbqVar15 = new eqbq("KeyPackageDataSerializationError", 14);
        o = eqbqVar15;
        eqbq eqbqVar16 = new eqbq("KeyPackageStorageError", 15);
        p = eqbqVar16;
        eqbq eqbqVar17 = new eqbq("GroupStateSerializationError", 16);
        q = eqbqVar17;
        eqbq eqbqVar18 = new eqbq("GroupAlreadyExistsError", 17);
        r = eqbqVar18;
        eqbq eqbqVar19 = new eqbq("EpochRecordSerializationError", 18);
        s = eqbqVar19;
        eqbq eqbqVar20 = new eqbq("GroupStateStorageWriteError", 19);
        t = eqbqVar20;
        eqbq eqbqVar21 = new eqbq("GroupInfoMessageExpected", 20);
        u = eqbqVar21;
        eqbq eqbqVar22 = new eqbq("GroupInfoExpired", 21);
        v = eqbqVar22;
        eqbq eqbqVar23 = new eqbq("StorageTraitError", 22);
        w = eqbqVar23;
        eqbq eqbqVar24 = new eqbq("ZinniaStateSerializationError", 23);
        x = eqbqVar24;
        eqbq eqbqVar25 = new eqbq("ZinniaStateDeserializationError", 24);
        y = eqbqVar25;
        eqbq eqbqVar26 = new eqbq("InvalidWireFormat", 25);
        z = eqbqVar26;
        eqbq eqbqVar27 = new eqbq("MissingRequiredGroupId", 26);
        A = eqbqVar27;
        eqbq eqbqVar28 = new eqbq("MissingRequiredEpoch", 27);
        B = eqbqVar28;
        eqbq eqbqVar29 = new eqbq("InvalidGroupId", 28);
        C = eqbqVar29;
        eqbq eqbqVar30 = new eqbq("OutOfOrderCommit", 29);
        D = eqbqVar30;
        eqbq eqbqVar31 = new eqbq("MissingDbPath", 30);
        E = eqbqVar31;
        eqbq eqbqVar32 = new eqbq("MissingSignatureKeyPair", 31);
        F = eqbqVar32;
        eqbq eqbqVar33 = new eqbq("MissingRootCertificates", 32);
        G = eqbqVar33;
        eqbq eqbqVar34 = new eqbq("MissingKeyPackages", 33);
        H = eqbqVar34;
        eqbq eqbqVar35 = new eqbq("MissingMembersToRemove", 34);
        I = eqbqVar35;
        eqbq eqbqVar36 = new eqbq("NoMembersMatchingSelector", 35);
        J = eqbqVar36;
        eqbq eqbqVar37 = new eqbq("DeliveryReceiptValidationError", 36);
        K = eqbqVar37;
        eqbq eqbqVar38 = new eqbq("DisplayReceiptValidationError", 37);
        L = eqbqVar38;
        eqbq eqbqVar39 = new eqbq("MissingDeliveryReceiptMetadata", 38);
        M = eqbqVar39;
        eqbq eqbqVar40 = new eqbq("MissingDisplayReceiptMetadata", 39);
        N = eqbqVar40;
        eqbq eqbqVar41 = new eqbq("KillSelfHealRequestAlreadyNone", 40);
        O = eqbqVar41;
        eqbq eqbqVar42 = new eqbq("KillSelfHealRequestAlreadyFailed", 41);
        P = eqbqVar42;
        eqbq eqbqVar43 = new eqbq("InvalidAuthenticatedDataVersion", 42);
        Q = eqbqVar43;
        eqbq eqbqVar44 = new eqbq("InvalidSecretPayloadVersion", 43);
        R = eqbqVar44;
        eqbq eqbqVar45 = new eqbq("InvalidSecretPayloadType", 44);
        S = eqbqVar45;
        eqbq eqbqVar46 = new eqbq("ValidatingNegativeDeliveryReceiptInPositiveFlow", 45);
        T = eqbqVar46;
        eqbq eqbqVar47 = new eqbq("ValidatingPositiveDeliveryReceiptInNegativeFlow", 46);
        U = eqbqVar47;
        eqbq eqbqVar48 = new eqbq("ReceiverIndexMismatch", 47);
        V = eqbqVar48;
        eqbq eqbqVar49 = new eqbq("GroupContextExtensionProposalChangesEraError", 48);
        W = eqbqVar49;
        eqbq eqbqVar50 = new eqbq("GroupContextExtensionProposalRemovesEraError", 49);
        X = eqbqVar50;
        eqbq eqbqVar51 = new eqbq("RatchetTreeSerializationError", 50);
        Y = eqbqVar51;
        eqbq eqbqVar52 = new eqbq("InvalidSelfHealStatus", 51);
        Z = eqbqVar52;
        eqbq eqbqVar53 = new eqbq("ExpectedSelfHealToBeOngoing", 52);
        aa = eqbqVar53;
        eqbq eqbqVar54 = new eqbq("InvalidProposalsInExternalCommit", 53);
        ab = eqbqVar54;
        eqbq eqbqVar55 = new eqbq("MissingSelfRemoveInExternalCommit", 54);
        ac = eqbqVar55;
        eqbq eqbqVar56 = new eqbq("MissingExternalInitInExternalCommit", 55);
        ad = eqbqVar56;
        eqbq eqbqVar57 = new eqbq("ReplayedMessage", 56);
        ae = eqbqVar57;
        eqbq eqbqVar58 = new eqbq("TimeRetrievalFailure", 57);
        af = eqbqVar58;
        eqbq eqbqVar59 = new eqbq("FileDecryptorMissingContext", 58);
        ag = eqbqVar59;
        eqbq eqbqVar60 = new eqbq("FileEncryptorMissingContext", 59);
        ah = eqbqVar60;
        eqbq eqbqVar61 = new eqbq("InvalidDeliveryNotificationStatus", 60);
        ai = eqbqVar61;
        eqbq eqbqVar62 = new eqbq("InvalidDisplayNotificationStatus", 61);
        aj = eqbqVar62;
        eqbq eqbqVar63 = new eqbq("InvalidMlsClientFailureReason", 62);
        ak = eqbqVar63;
        eqbq eqbqVar64 = new eqbq("InvalidDerivedContentVersion", 63);
        al = eqbqVar64;
        eqbq eqbqVar65 = new eqbq("InvalidEndMlsProposal", 64);
        am = eqbqVar65;
        eqbq eqbqVar66 = new eqbq("InvalidCommitList", 65);
        an = eqbqVar66;
        eqbq eqbqVar67 = new eqbq("EndingMlsNotSelfHealing", 66);
        ao = eqbqVar67;
        eqbq eqbqVar68 = new eqbq("IncorrectExpectedCommitKind", 67);
        ap = eqbqVar68;
        eqbq eqbqVar69 = new eqbq("InvalidParticipantProto", 68);
        aq = eqbqVar69;
        eqbq eqbqVar70 = new eqbq("InvalidEndMlsRevivialCommit", 69);
        ar = eqbqVar70;
        eqbq eqbqVar71 = new eqbq("InvalidOperationEndMlsActive", 70);
        as = eqbqVar71;
        eqbq eqbqVar72 = new eqbq("ExpectedSelfHealToBeRequested", 71);
        at = eqbqVar72;
        eqbq eqbqVar73 = new eqbq("ExistingPendingCommit", 72);
        au = eqbqVar73;
        eqbq eqbqVar74 = new eqbq("NonProposalMessageInProposalList", 73);
        av = eqbqVar74;
        eqbq eqbqVar75 = new eqbq("InvalidKeyUpdateTimestamp", 74);
        aw = eqbqVar75;
        eqbq eqbqVar76 = new eqbq("InvalidCertificate", 75);
        ax = eqbqVar76;
        eqbq eqbqVar77 = new eqbq("InvalidClientIdString", 76);
        ay = eqbqVar77;
        eqbq eqbqVar78 = new eqbq("IllegalMlsHealthStatusTransition", 77);
        az = eqbqVar78;
        eqbq eqbqVar79 = new eqbq("InvalidKeyPackageData", 78);
        aA = eqbqVar79;
        eqbq eqbqVar80 = new eqbq("SenderMismatch", 79);
        aB = eqbqVar80;
        eqbq eqbqVar81 = new eqbq("MembershipHistoryNotFound", 80);
        aC = eqbqVar81;
        eqbq eqbqVar82 = new eqbq("EpochAlreadyProcessed", 81);
        aD = eqbqVar82;
        eqbq[] eqbqVarArr = {eqbqVar, eqbqVar2, eqbqVar3, eqbqVar4, eqbqVar5, eqbqVar6, eqbqVar7, eqbqVar8, eqbqVar9, eqbqVar10, eqbqVar11, eqbqVar12, eqbqVar13, eqbqVar14, eqbqVar15, eqbqVar16, eqbqVar17, eqbqVar18, eqbqVar19, eqbqVar20, eqbqVar21, eqbqVar22, eqbqVar23, eqbqVar24, eqbqVar25, eqbqVar26, eqbqVar27, eqbqVar28, eqbqVar29, eqbqVar30, eqbqVar31, eqbqVar32, eqbqVar33, eqbqVar34, eqbqVar35, eqbqVar36, eqbqVar37, eqbqVar38, eqbqVar39, eqbqVar40, eqbqVar41, eqbqVar42, eqbqVar43, eqbqVar44, eqbqVar45, eqbqVar46, eqbqVar47, eqbqVar48, eqbqVar49, eqbqVar50, eqbqVar51, eqbqVar52, eqbqVar53, eqbqVar54, eqbqVar55, eqbqVar56, eqbqVar57, eqbqVar58, eqbqVar59, eqbqVar60, eqbqVar61, eqbqVar62, eqbqVar63, eqbqVar64, eqbqVar65, eqbqVar66, eqbqVar67, eqbqVar68, eqbqVar69, eqbqVar70, eqbqVar71, eqbqVar72, eqbqVar73, eqbqVar74, eqbqVar75, eqbqVar76, eqbqVar77, eqbqVar78, eqbqVar79, eqbqVar80, eqbqVar81, eqbqVar82};
        aG = eqbqVarArr;
        aE = fczb.a(eqbqVarArr);
        aF = eqbr.class;
        Library libraryLoad = Native.load("zinnia_jni", (Class<Library>) eqbr.class);
        libraryLoad.getClass();
    }

    private eqbq(String str, int i2) {
    }

    public static eqbq[] values() {
        return (eqbq[]) aG.clone();
    }
}
