package defpackage;

import j$.util.DesugarCollections;
import java.security.GeneralSecurityException;
import java.util.HashMap;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes5.dex */
public final class erbc {
    static {
        erna ernaVar = erna.a;
        try {
            a();
        } catch (GeneralSecurityException e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    public static void a() throws GeneralSecurityException {
        erey ereyVar = erey.a;
        ereyVar.c(erbl.a);
        ereyVar.b(erbl.b);
        ereyVar.c(erbp.a);
        ereyVar.b(erbp.b);
        eqtc.a();
        eqzl.a();
        if (eqzb.a()) {
            return;
        }
        erfp erfpVar = erad.a;
        if (!eqza.a(1)) {
            throw new GeneralSecurityException("Registering ECIES Hybrid Encryption is not supported in FIPS mode");
        }
        erfi erfiVar = erch.a;
        erfb erfbVar = erfb.a;
        erfbVar.h(erch.a);
        erfbVar.g(erch.b);
        erfbVar.f(erch.c);
        erfbVar.e(erch.d);
        erfbVar.f(erch.e);
        erfbVar.e(erch.f);
        erex erexVar = erex.a;
        HashMap map = new HashMap();
        Set set = erak.a;
        eraf erafVar = new eraf();
        erag eragVar = erag.a;
        erafVar.a = eragVar;
        erah erahVar = erah.c;
        erafVar.b = erahVar;
        erai eraiVar = erai.b;
        erafVar.c = eraiVar;
        eraj erajVar = eraj.a;
        erafVar.d = erajVar;
        equi equiVar = new equi();
        equiVar.b();
        equiVar.c(16);
        equiVar.d();
        equj equjVar = equj.c;
        equiVar.a = equjVar;
        erafVar.b(equiVar.a());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM", erafVar.a());
        eraf erafVar2 = new eraf();
        erafVar2.a = eragVar;
        erafVar2.b = erahVar;
        erafVar2.c = eraiVar;
        eraj erajVar2 = eraj.c;
        erafVar2.d = erajVar2;
        equi equiVar2 = new equi();
        equiVar2.b();
        equiVar2.c(16);
        equiVar2.d();
        equiVar2.a = equjVar;
        erafVar2.b(equiVar2.a());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_RAW", erafVar2.a());
        eraf erafVar3 = new eraf();
        erafVar3.a = eragVar;
        erafVar3.b = erahVar;
        erai eraiVar2 = erai.a;
        erafVar3.c = eraiVar2;
        erafVar3.d = erajVar;
        equi equiVar3 = new equi();
        equiVar3.b();
        equiVar3.c(16);
        equiVar3.d();
        equiVar3.a = equjVar;
        erafVar3.b(equiVar3.a());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM", erafVar3.a());
        eraf erafVar4 = new eraf();
        erafVar4.a = eragVar;
        erafVar4.b = erahVar;
        erafVar4.c = eraiVar2;
        erafVar4.d = erajVar2;
        equi equiVar4 = new equi();
        equiVar4.b();
        equiVar4.c(16);
        equiVar4.d();
        equiVar4.a = equjVar;
        erafVar4.b(equiVar4.a());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_GCM_RAW", erafVar4.a());
        eraf erafVar5 = new eraf();
        erafVar5.a = eragVar;
        erafVar5.b = erahVar;
        erafVar5.c = eraiVar2;
        erafVar5.d = erajVar2;
        equi equiVar5 = new equi();
        equiVar5.b();
        equiVar5.c(16);
        equiVar5.d();
        equiVar5.a = equjVar;
        erafVar5.b(equiVar5.a());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM_COMPRESSED_WITHOUT_PREFIX", erafVar5.a());
        eraf erafVar6 = new eraf();
        erafVar6.a = eragVar;
        erafVar6.b = erahVar;
        erafVar6.c = eraiVar;
        erafVar6.d = erajVar;
        eqtq eqtqVar = new eqtq();
        eqtqVar.b(16);
        eqtqVar.c(32);
        eqtqVar.e(16);
        eqtqVar.d(16);
        eqtr eqtrVar = eqtr.c;
        eqtqVar.a = eqtrVar;
        eqts eqtsVar = eqts.c;
        eqtqVar.b = eqtsVar;
        erafVar6.b(eqtqVar.a());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", erafVar6.a());
        eraf erafVar7 = new eraf();
        erafVar7.a = eragVar;
        erafVar7.b = erahVar;
        erafVar7.c = eraiVar;
        erafVar7.d = erajVar2;
        eqtq eqtqVar2 = new eqtq();
        eqtqVar2.b(16);
        eqtqVar2.c(32);
        eqtqVar2.e(16);
        eqtqVar2.d(16);
        eqtqVar2.a = eqtrVar;
        eqtqVar2.b = eqtsVar;
        erafVar7.b(eqtqVar2.a());
        map.put("ECIES_P256_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", erafVar7.a());
        eraf erafVar8 = new eraf();
        erafVar8.a = eragVar;
        erafVar8.b = erahVar;
        erafVar8.c = eraiVar2;
        erafVar8.d = erajVar;
        eqtq eqtqVar3 = new eqtq();
        eqtqVar3.b(16);
        eqtqVar3.c(32);
        eqtqVar3.e(16);
        eqtqVar3.d(16);
        eqtqVar3.a = eqtrVar;
        eqtqVar3.b = eqtsVar;
        erafVar8.b(eqtqVar3.a());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256", erafVar8.a());
        eraf erafVar9 = new eraf();
        erafVar9.a = eragVar;
        erafVar9.b = erahVar;
        erafVar9.c = eraiVar2;
        erafVar9.d = erajVar2;
        eqtq eqtqVar4 = new eqtq();
        eqtqVar4.b(16);
        eqtqVar4.c(32);
        eqtqVar4.e(16);
        eqtqVar4.d(16);
        eqtqVar4.a = eqtrVar;
        eqtqVar4.b = eqtsVar;
        erafVar9.b(eqtqVar4.a());
        map.put("ECIES_P256_COMPRESSED_HKDF_HMAC_SHA256_AES128_CTR_HMAC_SHA256_RAW", erafVar9.a());
        erexVar.b(DesugarCollections.unmodifiableMap(map));
        ereyVar.b(erad.a);
        ereyVar.b(erad.b);
        eres eresVar = eres.a;
        eresVar.b(erad.d, erak.class);
        erec erecVar = erec.a;
        erecVar.c(erad.e, true);
        erecVar.c(erad.c, false);
        erfp erfpVar2 = ercu.a;
        if (!eqza.a(1)) {
            throw new GeneralSecurityException("Registering HPKE Hybrid Encryption is not supported in FIPS mode");
        }
        erfbVar.h(erba.a);
        erfbVar.g(erba.b);
        erfbVar.f(erba.c);
        erfbVar.e(erba.d);
        erfbVar.f(erba.e);
        erfbVar.e(erba.f);
        HashMap map2 = new HashMap();
        erar erarVar = erar.a;
        eraq eraqVar = eraq.f;
        erap erapVar = erap.a;
        eran eranVar = eran.a;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", new eras(eraqVar, erapVar, eranVar, erarVar));
        erar erarVar2 = erar.c;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", new eras(eraqVar, erapVar, eranVar, erarVar2));
        eran eranVar2 = eran.b;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", new eras(eraqVar, erapVar, eranVar2, erarVar));
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", new eras(eraqVar, erapVar, eranVar2, erarVar2));
        eran eranVar3 = eran.c;
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305", new eras(eraqVar, erapVar, eranVar3, erarVar));
        map2.put("DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_CHACHA20_POLY1305_RAW", new eras(eraqVar, erapVar, eranVar3, erarVar2));
        eraq eraqVar2 = eraq.a;
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM", new eras(eraqVar2, erapVar, eranVar, erarVar));
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_128_GCM_RAW", new eras(eraqVar2, erapVar, eranVar, erarVar2));
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM", new eras(eraqVar2, erapVar, eranVar2, erarVar));
        map2.put("DHKEM_P256_HKDF_SHA256_HKDF_SHA256_AES_256_GCM_RAW", new eras(eraqVar2, erapVar, eranVar2, erarVar2));
        eraq eraqVar3 = eraq.b;
        erap erapVar2 = erap.b;
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM", new eras(eraqVar3, erapVar2, eranVar, erarVar));
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_128_GCM_RAW", new eras(eraqVar3, erapVar2, eranVar, erarVar2));
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM", new eras(eraqVar3, erapVar2, eranVar2, erarVar));
        map2.put("DHKEM_P384_HKDF_SHA384_HKDF_SHA384_AES_256_GCM_RAW", new eras(eraqVar3, erapVar2, eranVar2, erarVar2));
        eraq eraqVar4 = eraq.c;
        erap erapVar3 = erap.c;
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM", new eras(eraqVar4, erapVar3, eranVar, erarVar));
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_128_GCM_RAW", new eras(eraqVar4, erapVar3, eranVar, erarVar2));
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM", new eras(eraqVar4, erapVar3, eranVar2, erarVar));
        map2.put("DHKEM_P521_HKDF_SHA512_HKDF_SHA512_AES_256_GCM_RAW", new eras(eraqVar4, erapVar3, eranVar2, erarVar2));
        erexVar.b(DesugarCollections.unmodifiableMap(map2));
        ereyVar.b(ercu.a);
        ereyVar.b(ercu.b);
        eresVar.b(ercu.d, eras.class);
        erecVar.c(ercu.e, true);
        erecVar.c(ercu.c, false);
    }
}
