package defpackage;

import com.android.vcard.VCardConstants;
import j$.util.DesugarCollections;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/* compiled from: PG */
/* loaded from: classes5.dex */
public final class etdt {
    public static final Map a;

    static {
        HashMap map = new HashMap();
        map.put(1, a("US", "AG", "AI", "AS", "BB", "BM", "BS", "CA", "DM", "DO", "GD", "GU", "JM", "KN", "KY", "LC", "MP", "MS", "PR", "SX", "TC", "TT", "VC", "VG", "VI"));
        map.put(7, a("RU", "KZ"));
        map.put(20, a("EG"));
        map.put(27, a("ZA"));
        map.put(30, a("GR"));
        map.put(31, a("NL"));
        map.put(32, a("BE"));
        map.put(33, a("FR"));
        map.put(34, a("ES"));
        map.put(36, a("HU"));
        map.put(39, a("IT", "VA"));
        map.put(40, a("RO"));
        map.put(41, a("CH"));
        map.put(43, a("AT"));
        map.put(44, a("GB", "GG", "IM", "JE"));
        map.put(45, a("DK"));
        map.put(46, a("SE"));
        map.put(47, a("NO", "SJ"));
        map.put(48, a("PL"));
        map.put(49, a("DE"));
        map.put(51, a("PE"));
        map.put(52, a("MX"));
        map.put(53, a("CU"));
        map.put(54, a("AR"));
        map.put(55, a("BR"));
        map.put(56, a("CL"));
        map.put(57, a("CO"));
        map.put(58, a("VE"));
        map.put(60, a("MY"));
        map.put(61, a("AU", "CC", "CX"));
        map.put(62, a("ID"));
        map.put(63, a("PH"));
        map.put(64, a("NZ"));
        map.put(65, a("SG"));
        map.put(66, a("TH"));
        map.put(81, a("JP"));
        map.put(82, a("KR"));
        map.put(84, a("VN"));
        map.put(86, a("CN"));
        map.put(90, a("TR"));
        map.put(91, a("IN"));
        map.put(92, a("PK"));
        map.put(93, a("AF"));
        map.put(94, a("LK"));
        map.put(95, a("MM"));
        map.put(98, a("IR"));
        map.put(211, a("SS"));
        map.put(212, a("MA", "EH"));
        map.put(213, a("DZ"));
        map.put(216, a("TN"));
        map.put(218, a("LY"));
        map.put(220, a("GM"));
        map.put(221, a("SN"));
        map.put(222, a("MR"));
        map.put(223, a("ML"));
        map.put(224, a("GN"));
        map.put(225, a("CI"));
        map.put(226, a("BF"));
        map.put(227, a("NE"));
        map.put(228, a("TG"));
        map.put(229, a("BJ"));
        map.put(230, a("MU"));
        map.put(231, a("LR"));
        map.put(232, a("SL"));
        map.put(233, a("GH"));
        map.put(234, a("NG"));
        map.put(235, a("TD"));
        map.put(236, a("CF"));
        map.put(237, a("CM"));
        map.put(238, a("CV"));
        map.put(239, a("ST"));
        map.put(240, a("GQ"));
        map.put(241, a("GA"));
        map.put(242, a("CG"));
        map.put(243, a("CD"));
        map.put(244, a("AO"));
        map.put(245, a("GW"));
        map.put(246, a("IO"));
        map.put(247, a("AC"));
        map.put(248, a("SC"));
        map.put(249, a("SD"));
        map.put(250, a("RW"));
        map.put(251, a("ET"));
        map.put(252, a("SO"));
        map.put(253, a("DJ"));
        map.put(254, a("KE"));
        map.put(255, a(VCardConstants.PROPERTY_TZ));
        map.put(256, a("UG"));
        map.put(257, a("BI"));
        map.put(258, a("MZ"));
        map.put(260, a("ZM"));
        map.put(261, a("MG"));
        map.put(262, a("RE", "YT"));
        map.put(263, a("ZW"));
        map.put(264, a("NA"));
        map.put(265, a("MW"));
        map.put(266, a("LS"));
        map.put(267, a("BW"));
        map.put(268, a("SZ"));
        map.put(269, a("KM"));
        map.put(290, a("SH", "TA"));
        map.put(291, a("ER"));
        map.put(297, a("AW"));
        map.put(298, a("FO"));
        map.put(299, a("GL"));
        map.put(350, a("GI"));
        map.put(351, a("PT"));
        map.put(352, a("LU"));
        map.put(353, a("IE"));
        map.put(354, a("IS"));
        map.put(355, a("AL"));
        map.put(356, a("MT"));
        map.put(357, a("CY"));
        map.put(358, a("FI", "AX"));
        map.put(359, a("BG"));
        map.put(370, a("LT"));
        map.put(371, a("LV"));
        map.put(372, a("EE"));
        map.put(373, a("MD"));
        map.put(374, a("AM"));
        map.put(375, a("BY"));
        map.put(376, a("AD"));
        map.put(377, a("MC"));
        map.put(378, a("SM"));
        map.put(380, a("UA"));
        map.put(381, a("RS"));
        map.put(382, a("ME"));
        map.put(383, a("XK"));
        map.put(385, a("HR"));
        map.put(386, a("SI"));
        map.put(387, a("BA"));
        map.put(389, a("MK"));
        map.put(420, a("CZ"));
        map.put(421, a("SK"));
        map.put(423, a("LI"));
        map.put(500, a("FK"));
        map.put(501, a("BZ"));
        map.put(502, a("GT"));
        map.put(503, a("SV"));
        map.put(504, a("HN"));
        map.put(505, a("NI"));
        map.put(506, a("CR"));
        map.put(507, a("PA"));
        map.put(508, a("PM"));
        map.put(509, a("HT"));
        map.put(590, a("GP", "BL", "MF"));
        map.put(591, a("BO"));
        map.put(592, a("GY"));
        map.put(593, a("EC"));
        map.put(594, a("GF"));
        map.put(595, a("PY"));
        map.put(596, a("MQ"));
        map.put(597, a("SR"));
        map.put(598, a("UY"));
        map.put(599, a("CW", "BQ"));
        map.put(670, a("TL"));
        map.put(672, a("NF"));
        map.put(673, a("BN"));
        map.put(674, a("NR"));
        map.put(675, a("PG"));
        map.put(676, a("TO"));
        map.put(677, a("SB"));
        map.put(678, a("VU"));
        map.put(679, a("FJ"));
        map.put(680, a("PW"));
        map.put(681, a("WF"));
        map.put(682, a("CK"));
        map.put(683, a("NU"));
        map.put(685, a("WS"));
        map.put(686, a("KI"));
        map.put(687, a("NC"));
        map.put(688, a("TV"));
        map.put(689, a("PF"));
        map.put(690, a("TK"));
        map.put(691, a("FM"));
        map.put(692, a("MH"));
        map.put(800, a("001"));
        map.put(808, a("001"));
        map.put(850, a("KP"));
        map.put(852, a("HK"));
        map.put(853, a("MO"));
        map.put(855, a("KH"));
        map.put(856, a("LA"));
        map.put(870, a("001"));
        map.put(878, a("001"));
        map.put(880, a("BD"));
        map.put(881, a("001"));
        map.put(882, a("001"));
        map.put(883, a("001"));
        map.put(886, a("TW"));
        map.put(888, a("001"));
        map.put(960, a("MV"));
        map.put(961, a("LB"));
        map.put(962, a("JO"));
        map.put(963, a("SY"));
        map.put(964, a("IQ"));
        map.put(965, a("KW"));
        map.put(966, a("SA"));
        map.put(967, a("YE"));
        map.put(968, a("OM"));
        map.put(970, a("PS"));
        map.put(971, a("AE"));
        map.put(972, a("IL"));
        map.put(973, a("BH"));
        map.put(974, a("QA"));
        map.put(975, a("BT"));
        map.put(976, a("MN"));
        map.put(977, a("NP"));
        map.put(979, a("001"));
        map.put(992, a("TJ"));
        map.put(993, a("TM"));
        map.put(994, a("AZ"));
        map.put(995, a("GE"));
        map.put(996, a("KG"));
        map.put(998, a("UZ"));
        a = DesugarCollections.unmodifiableMap(map);
    }

    private static List a(String... strArr) {
        ArrayList arrayList = new ArrayList();
        for (String str : strArr) {
            arrayList.add(etdn.a(str));
        }
        return DesugarCollections.unmodifiableList(arrayList);
    }
}
