package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum ewnb implements evst {
    REGISTRATION_EVENT_MESSAGE_UNKNOWN(0),
    REGISTRATION_EVENT_MESSAGE_SEND_SIP_MESSAGE(1),
    REGISTRATION_EVENT_MESSAGE_RECEIVE_SIP_RESPONSE(2),
    REGISTRATION_EVENT_MESSAGE_SIP_REQUEST_TIMEOUT(3),
    REGISTRATION_EVENT_MESSAGE_CONNECTIVITY_EVENT(4),
    REGISTRATION_EVENT_MESSAGE_TRANSPORT_ERROR(5),
    REGISTRATION_EVENT_MESSAGE_START_REGISTRATION(6),
    REGISTRATION_EVENT_MESSAGE_STOP_REGISTRATION(7),
    REGISTRATION_EVENT_MESSAGE_DISCOVER_SIP_SERVER(8),
    REGISTRATION_EVENT_MESSAGE_CONNECT_TO_SERVER(9),
    REGISTRATION_EVENT_MESSAGE_CONNECTED_TO_SERVER(10),
    REGISTRATION_EVENT_MESSAGE_REFRESH_TIMEOUT(11),
    REGISTRATION_EVENT_MESSAGE_RETRY_TIMEOUT(12),
    REGISTRATION_EVENT_MESSAGE_REREGISTRATION_REQUIRED(13),
    REGISTRATION_EVENT_MESSAGE_SIM_DETECTED(14),
    REGISTRATION_EVENT_MESSAGE_SIM_REMOVED(15),
    REGISTRATION_EVENT_MESSAGE_CONNECTION_CREATED(16),
    REGISTRATION_EVENT_MESSAGE_CONNECTION_DESTROYED(17),
    REGISTRATION_EVENT_MESSAGE_CONFIGURED(18),
    REGISTRATION_EVENT_MESSAGE_ACTIVATE(19),
    REGISTRATION_EVENT_MESSAGE_DEACTIVATE(20),
    REGISTRATION_EVENT_MESSAGE_REGISTRATION_FAILED(21),
    REGISTRATION_EVENT_MESSAGE_REGISTER_TIMEOUT(22),
    REGISTRATION_EVENT_MESSAGE_PUBLISH_TIMEOUT(23),
    REGISTRATION_EVENT_MESSAGE_PUBLISH_200OK_RESPONSE(24),
    REGISTRATION_EVENT_MESSAGE_PUBLISH_FAILED_RESPONSE(25),
    REGISTRATION_EVENT_MESSAGE_CONNECTION_TIMEOUT(26),
    REGISTRATION_EVENT_MESSAGE_CONNECT_TO_SERVER_FAILURE(27);

    public final int C;

    ewnb(int i) {
        this.C = i;
    }

    @Override // defpackage.evst
    public final int a() {
        return this.C;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.C);
    }
}
