package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum ewnf implements evst {
    SIP_REGISTRATION_STATE_UNKNOWN(0),
    SIP_REGISTRATION_STOPPED_STATE(1),
    SIP_REGISTRATION_READY_STATE(2),
    SIP_REGISTRATION_WAIT_FOR_NETWORK_STATE(3),
    SIP_REGISTRATION_CONNECTING_STATE(4),
    SIP_REGISTRATION_REGISTERING_STATE(5),
    SIP_REGISTRATION_REGISTERED_STATE(6),
    SIP_REGISTRATION_SUBSCRIBING_STATE(7),
    SIP_REGISTRATION_SUBSCRIBED_STATE(8),
    SIP_REGISTRATION_REREGISTERING_STATE(9),
    SIP_REGISTRATION_REREGISTERED_STATE(10),
    SIP_REGISTRATION_DEREGISTERING_STATE(11),
    SIP_REGISTRATION_DEREGISTERED_STATE(12),
    SIP_REGISTRATION_RECONFIGURATION_REQUIRED_STATE(13),
    SIP_REGISTRATION_RETRY_STATE(14),
    SIP_REGISTRATION_DISABLED_STATE(15),
    SIP_REGISTRATION_SIM_REMOVED_STATE(16),
    SIP_REGISTRATION_RECEIVE_CONFIGURATION_STATE(17),
    SIP_REGISTRATION_RECEIVE_FEATURE_TAGS_STATE(18),
    SIP_REGISTRATION_INACTIVE_STATE(19),
    SIP_REGISTRATION_TERMINATED_STATE(20),
    SIP_REGISTRATION_PUBLISHED_STATE(21);

    public final int w;

    ewnf(int i) {
        this.w = i;
    }

    @Override // defpackage.evst
    public final int a() {
        return this.w;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.w);
    }
}
