package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum ewrp implements evst {
    RCS_PROVISIONING_UNKNOWN_STATE(0),
    RCS_PROVISIONING_ENABLED_STATE(1),
    RCS_PROVISIONING_DISABLED_STATE(2),
    RCS_PROVISIONING_READY_STATE(3),
    RCS_PROVISIONING_IN_PROGRESS_STATE(4),
    RCS_PROVISIONING_RETRY_STATE(5),
    RCS_PROVISIONING_CONFIGURED_STATE(6),
    RCS_PROVISIONING_WAITING_FOR_NETWORK_STATE(7),
    RCS_PROVISIONING_WAITING_FOR_CONSENT_STATE(8),
    RCS_PROVISIONING_WAITING_FOR_CONSTELLATION_CONSENT_STATE(9),
    RCS_PROVISIONING_WAITING_FOR_GOOGLE_TOS_STATE(10),
    RCS_PROVISIONING_WAITING_FOR_BATTERY_OPTIMIZATION_STATE(11),
    RCS_PROVISIONING_WAITING_FOR_TERMS_AND_CONDITIONS_STATE(12),
    RCS_PROVISIONING_WAITING_FOR_OTP_STATE(13),
    RCS_PROVISIONING_CHECK_PRECONDITIONS_STATE(14),
    RCS_PROVISIONING_REQUEST_WITH_HE_STATE(15),
    RCS_PROVISIONING_REQUEST_WITH_HE_PROXY_STATE(16),
    RCS_PROVISIONING_REQUEST_WITHOUT_AUTH_STATE(17),
    RCS_PROVISIONING_REQUEST_WITH_TOKEN_STATE(18),
    RCS_PROVISIONING_REQUEST_WITH_IMSI_STATE(19),
    RCS_PROVISIONING_REQUEST_WITH_MSISDN_STATE(20),
    RCS_PROVISIONING_PROCESS_CONFIGURATION_STATE(21),
    RCS_PROVISIONING_VERIFY_OTP_STATE(22),
    RCS_PROVISIONING_WAITING_FOR_MANUAL_MSISDN_ENTRY_STATE(23),
    RCS_PROVISIONING_REPLAY_REQUEST_STATE(24),
    RCS_PROVISIONING_SEND_DISABLE_RCS_STATE(25),
    RCS_PROVISIONING_DISABLE_RCS_RETRY_STATE(26),
    RCS_PROVISIONING_REPLAY_DISABLE_RCS_REQUEST_STATE(27),
    RCS_PROVISIONING_SET_GOOGLE_TOS_CONSENT_STATE(28),
    RCS_PROVISIONING_GET_GOOGLE_TOS_CONSENT_STATE(29),
    RCS_PROVISIONING_REQUEST_WITH_MSISDN_TOKEN_STATE(30),
    RCS_PROVISIONING_VERIFY_MSISDN_STATE(31),
    RCS_PROVISIONING_WAITING_FOR_RCS_DEFAULT_ON_STATE(32),
    RCS_PROVISIONING_WAITING_FOR_APP_OPEN_STATE(33),
    RCS_PROVISIONING_REQUEST_ATTESTATION_STATE(34);

    public final int J;

    ewrp(int i) {
        this.J = i;
    }

    @Override // defpackage.evst
    public final int a() {
        return this.J;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.J);
    }
}
