package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class fabg implements esob {
    public final ekgb H;
    public final ekhx I;
    private final ekgp L;
    public static final dzfh a = new dzfh("google.internal.communications.instantmessaging.v1.Registration.");
    private static final dzfh J = new dzfh("google.internal.communications.instantmessaging.v1.Registration/");
    public static final esoa b = new faal();
    public static final esoa c = new faaw();
    public static final esoa d = new faaz();
    public static final esoa e = new faba();
    public static final esoa f = new fabb();
    public static final esoa g = new fabc();
    public static final esoa h = new fabd();
    public static final esoa i = new fabe();
    public static final esoa j = new fabf();
    public static final esoa k = new faab();
    public static final esoa l = new faac();
    public static final esoa m = new faad();
    public static final esoa n = new faae();
    public static final esoa o = new faaf();
    public static final esoa p = new faag();
    public static final esoa q = new faah();
    public static final esoa r = new faai();
    public static final esoa s = new faaj();
    public static final esoa t = new faak();
    public static final esoa u = new faam();
    public static final esoa v = new faan();
    public static final esoa w = new faao();
    public static final esoa x = new faap();
    public static final esoa y = new faaq();
    public static final esoa z = new faar();
    public static final esoa A = new faas();
    public static final esoa B = new faat();
    public static final esoa C = new faau();
    public static final esoa D = new faav();
    public static final esoa E = new faax();
    public static final esoa F = new faay();
    public static final fabg G = new fabg();
    private static final dzfh K = new dzfh("instantmessaging-pa.googleapis.com");

    private fabg() {
        int i2 = ekgb.d;
        ekfw ekfwVar = new ekfw();
        ekfwVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-pa.mtls.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("zero-instantmessaging-pa.googleapis.com");
        ekfwVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        ekfwVar.h("instantmessaging-pa.googleapis.com");
        this.H = ekfwVar.g();
        this.I = new ekhv().g();
        esoa esoaVar = b;
        esoa esoaVar2 = c;
        esoa esoaVar3 = d;
        esoa esoaVar4 = e;
        esoa esoaVar5 = f;
        esoa esoaVar6 = g;
        esoa esoaVar7 = h;
        esoa esoaVar8 = i;
        esoa esoaVar9 = j;
        esoa esoaVar10 = k;
        esoa esoaVar11 = l;
        esoa esoaVar12 = m;
        esoa esoaVar13 = n;
        esoa esoaVar14 = o;
        esoa esoaVar15 = p;
        esoa esoaVar16 = q;
        esoa esoaVar17 = r;
        esoa esoaVar18 = s;
        esoa esoaVar19 = t;
        esoa esoaVar20 = u;
        esoa esoaVar21 = v;
        esoa esoaVar22 = w;
        esoa esoaVar23 = x;
        esoa esoaVar24 = y;
        esoa esoaVar25 = z;
        esoa esoaVar26 = A;
        esoa esoaVar27 = B;
        esoa esoaVar28 = C;
        esoa esoaVar29 = D;
        esoa esoaVar30 = E;
        esoa esoaVar31 = F;
        ekhx.v(esoaVar, esoaVar2, esoaVar3, esoaVar4, esoaVar5, esoaVar6, esoaVar7, esoaVar8, esoaVar9, esoaVar10, esoaVar11, esoaVar12, esoaVar13, esoaVar14, esoaVar15, esoaVar16, esoaVar17, esoaVar18, esoaVar19, esoaVar20, esoaVar21, esoaVar22, esoaVar23, esoaVar24, esoaVar25, esoaVar26, esoaVar27, esoaVar28, esoaVar29, esoaVar30, esoaVar31);
        ekgi ekgiVar = new ekgi();
        ekgiVar.i("Register", esoaVar);
        ekgiVar.i("RegisterSilent", esoaVar2);
        ekgiVar.i("PeriodicRegisterSilent", esoaVar3);
        ekgiVar.i("RegisterAnonymous", esoaVar4);
        ekgiVar.i("RegisterByAgent", esoaVar5);
        ekgiVar.i("RegisterRefresh", esoaVar6);
        ekgiVar.i("Verify", esoaVar7);
        ekgiVar.i("Unregister", esoaVar8);
        ekgiVar.i("DeleteAccount", esoaVar9);
        ekgiVar.i("LookupRegistered", esoaVar10);
        ekgiVar.i("LookupRegisteredSheddable", esoaVar11);
        ekgiVar.i("SetCapabilities", esoaVar12);
        ekgiVar.i("GetPreKey", esoaVar13);
        ekgiVar.i("GetPreKeyBatch", esoaVar14);
        ekgiVar.i("SetPreKeys", esoaVar15);
        ekgiVar.i("UpgradeAccount", esoaVar16);
        ekgiVar.i("DowngradeAccount", esoaVar17);
        ekgiVar.i("SignInGaia", esoaVar18);
        ekgiVar.i("SignInGaiaSilent", esoaVar19);
        ekgiVar.i("VerifyGaia", esoaVar20);
        ekgiVar.i("GetAccountInfo", esoaVar21);
        ekgiVar.i("AddPhoneReachability", esoaVar22);
        ekgiVar.i("VerifyPhoneReachability", esoaVar23);
        ekgiVar.i("RegisterGaiaSilent", esoaVar24);
        ekgiVar.i("ReplacePhoneReachability", esoaVar25);
        ekgiVar.i("UnregisterGoogleRCS", esoaVar26);
        ekgiVar.i("GetGaiaDeviceInfo", esoaVar27);
        ekgiVar.i("LinkIdentity", esoaVar28);
        ekgiVar.i("ListIdentities", esoaVar29);
        ekgiVar.i("SignInSecondary", esoaVar30);
        ekgiVar.i("UnlinkIdentity", esoaVar31);
        this.L = ekgiVar.c();
        new ekgi().c();
    }

    @Override // defpackage.esob
    public final dzfh a() {
        return K;
    }

    @Override // defpackage.esob
    public final esoa b(String str) {
        String str2 = J.a;
        if (!str.startsWith(str2)) {
            return null;
        }
        String strSubstring = str.substring(str2.length());
        ekgp ekgpVar = this.L;
        if (ekgpVar.containsKey(strSubstring)) {
            return (esoa) ekgpVar.get(strSubstring);
        }
        return null;
    }
}
