package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class facq implements esob {
    public final ekhx A;
    private final ekgp D;
    public final ekgb z;
    public static final dzfh a = new dzfh("google.internal.communications.instantmessaging.v1.UserData.");
    private static final dzfh B = new dzfh("google.internal.communications.instantmessaging.v1.UserData/");
    public static final esoa b = new facd();
    public static final esoa c = new faci();
    public static final esoa d = new facj();
    public static final esoa e = new fack();
    public static final esoa f = new facl();
    public static final esoa g = new facm();
    public static final esoa h = new facn();
    public static final esoa i = new faco();
    public static final esoa j = new facp();
    public static final esoa k = new fabt();
    public static final esoa l = new fabu();
    public static final esoa m = new fabv();
    public static final esoa n = new fabw();
    public static final esoa o = new fabx();
    public static final esoa p = new faby();
    public static final esoa q = new fabz();
    public static final esoa r = new faca();
    public static final esoa s = new facb();
    public static final esoa t = new facc();
    public static final esoa u = new face();
    public static final esoa v = new facf();
    public static final esoa w = new facg();
    public static final esoa x = new fach();
    public static final facq y = new facq();
    private static final dzfh C = new dzfh("instantmessaging-pa.googleapis.com");

    private facq() {
        int i2 = ekgb.d;
        ekfw ekfwVar = new ekfw();
        ekfwVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-pa.mtls.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ekfwVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ekfwVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        ekfwVar.h("zero-instantmessaging-pa.googleapis.com");
        ekfwVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        ekfwVar.h("instantmessaging-pa.googleapis.com");
        this.z = ekfwVar.g();
        this.A = new ekhv().g();
        esoa esoaVar = b;
        esoa esoaVar2 = c;
        esoa esoaVar3 = d;
        esoa esoaVar4 = e;
        esoa esoaVar5 = f;
        esoa esoaVar6 = g;
        esoa esoaVar7 = h;
        esoa esoaVar8 = i;
        esoa esoaVar9 = j;
        esoa esoaVar10 = k;
        esoa esoaVar11 = l;
        esoa esoaVar12 = m;
        esoa esoaVar13 = n;
        esoa esoaVar14 = o;
        esoa esoaVar15 = p;
        esoa esoaVar16 = q;
        esoa esoaVar17 = r;
        esoa esoaVar18 = s;
        esoa esoaVar19 = t;
        esoa esoaVar20 = u;
        esoa esoaVar21 = v;
        esoa esoaVar22 = w;
        esoa esoaVar23 = x;
        ekhx.v(esoaVar, esoaVar2, esoaVar3, esoaVar4, esoaVar5, esoaVar6, esoaVar7, esoaVar8, esoaVar9, esoaVar10, esoaVar11, esoaVar12, esoaVar13, esoaVar14, esoaVar15, esoaVar16, esoaVar17, esoaVar18, esoaVar19, esoaVar20, esoaVar21, esoaVar22, esoaVar23);
        ekgi ekgiVar = new ekgi();
        ekgiVar.i("SetContacts", esoaVar);
        ekgiVar.i("NetworkTransition", esoaVar2);
        ekgiVar.i("AddContacts", esoaVar3);
        ekgiVar.i("RemoveContacts", esoaVar4);
        ekgiVar.i("SetProfile", esoaVar5);
        ekgiVar.i("GetProfile", esoaVar6);
        ekgiVar.i("LookupContacts", esoaVar7);
        ekgiVar.i("LookupContactLite", esoaVar8);
        ekgiVar.i("GetSelfUserInviteLink", esoaVar9);
        ekgiVar.i("ResetSelfUserInviteLink", esoaVar10);
        ekgiVar.i("GetUserInviteLinkDetails", esoaVar11);
        ekgiVar.i("CreateShortLinks", esoaVar12);
        ekgiVar.i("GetUserInviterId", esoaVar13);
        ekgiVar.i("LookupUserInviterId", esoaVar14);
        ekgiVar.i("InformInviter", esoaVar15);
        ekgiVar.i("GetContacts", esoaVar16);
        ekgiVar.i("GetStates", esoaVar17);
        ekgiVar.i("ApplyStateMutations", esoaVar18);
        ekgiVar.i("SetDeviceMute", esoaVar19);
        ekgiVar.i("GetDeviceMute", esoaVar20);
        ekgiVar.i("SendNotification", esoaVar21);
        ekgiVar.i("GetOnlineStatus", esoaVar22);
        ekgiVar.i("UpdateAccountSetting", esoaVar23);
        this.D = ekgiVar.c();
        new ekgi().c();
    }

    @Override // defpackage.esob
    public final dzfh a() {
        return C;
    }

    @Override // defpackage.esob
    public final esoa b(String str) {
        String str2 = B.a;
        if (!str.startsWith(str2)) {
            return null;
        }
        String strSubstring = str.substring(str2.length());
        ekgp ekgpVar = this.D;
        if (ekgpVar.containsKey(strSubstring)) {
            return (esoa) ekgpVar.get(strSubstring);
        }
        return null;
    }
}
