package defpackage;

/* compiled from: PG */
/* loaded from: classes6.dex */
public enum febt implements evst {
    BUGLE_SENDING_INTERNAL_STATUS_UNSPECIFIED(0),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_CHATAPI(1),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_FILE_TRANSFER(13),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_RCS_FILE_TRANSFER(14),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_RCS_ENGINE(15),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_TELEPHONY_MANAGER_SMS(16),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_MMS_SENDER(17),
    BUGLE_SENDING_INTERNAL_STATUS_PASSING_TO_CLOUD_SYNC_SENDER(18),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_SMS(2),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_MMS(3),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_RCS(4),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_CHATAPI(5),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_SLMAPI(19),
    BUGLE_SENDING_INTERNAL_STATUS_RETURNED_FROM_FAST_FAILURE(6),
    BUGLE_SENDING_INTERNAL_STATUS_DISPLAYED(7),
    BUGLE_SENDING_INTERNAL_STATUS_DELIVERED(8),
    BUGLE_SENDING_INTERNAL_STATUS_DELIVERY_EVENT_UNHANDLED(9),
    BUGLE_SENDING_INTERNAL_STATUS_VERIFYING_MESSAGE(10),
    BUGLE_SENDING_INTERNAL_STATUS_NOT_SENT(11),
    BUGLE_SENDING_INTERNAL_STATUS_INSERTING_MESSAGE_FOR_SEND(12),
    BUGLE_SENDING_INTERNAL_STATUS_NOT_SENT_MISSING_SUB_ID(20),
    UNRECOGNIZED(-1);

    private final int x;

    febt(int i) {
        this.x = i;
    }

    @Override // defpackage.evst
    public final int a() {
        if (this != UNRECOGNIZED) {
            return this.x;
        }
        throw new IllegalArgumentException("Can't get the number of an unknown enum value.");
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.x);
    }
}
