package defpackage;

import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.Map;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class fexq {
    public static final fexp a = new fexp();
    public static final Comparator b = new fexo();
    public static final Map c = new LinkedHashMap();
    public static final fexq d;
    public static final fexq e;
    public static final fexq f;
    public static final fexq g;
    public static final fexq h;
    public static final fexq i;
    public static final fexq j;
    public static final fexq k;
    public static final fexq l;
    public static final fexq m;
    public static final fexq n;
    public static final fexq o;
    public static final fexq p;
    public static final fexq q;
    public static final fexq r;
    public static final fexq s;
    public final String t;

    static {
        fexp.b("SSL_RSA_WITH_NULL_MD5");
        fexp.b("SSL_RSA_WITH_NULL_SHA");
        fexp.b("SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        fexp.b("SSL_RSA_WITH_RC4_128_MD5");
        fexp.b("SSL_RSA_WITH_RC4_128_SHA");
        fexp.b("SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        fexp.b("SSL_RSA_WITH_DES_CBC_SHA");
        d = fexp.b("SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        fexp.b("SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        fexp.b("SSL_DHE_DSS_WITH_DES_CBC_SHA");
        fexp.b("SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        fexp.b("SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        fexp.b("SSL_DHE_RSA_WITH_DES_CBC_SHA");
        fexp.b("SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        fexp.b("SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        fexp.b("SSL_DH_anon_WITH_RC4_128_MD5");
        fexp.b("SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        fexp.b("SSL_DH_anon_WITH_DES_CBC_SHA");
        fexp.b("SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_KRB5_WITH_DES_CBC_SHA");
        fexp.b("TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_KRB5_WITH_RC4_128_SHA");
        fexp.b("TLS_KRB5_WITH_DES_CBC_MD5");
        fexp.b("TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        fexp.b("TLS_KRB5_WITH_RC4_128_MD5");
        fexp.b("TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        fexp.b("TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        fexp.b("TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        fexp.b("TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        e = fexp.b("TLS_RSA_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_DH_anon_WITH_AES_128_CBC_SHA");
        f = fexp.b("TLS_RSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_DH_anon_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_RSA_WITH_NULL_SHA256");
        fexp.b("TLS_RSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_RSA_WITH_AES_256_CBC_SHA256");
        fexp.b("TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        fexp.b("TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        fexp.b("TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        fexp.b("TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        fexp.b("TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        fexp.b("TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        fexp.b("TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        fexp.b("TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        fexp.b("TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        fexp.b("TLS_PSK_WITH_RC4_128_SHA");
        fexp.b("TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_PSK_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_PSK_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_RSA_WITH_SEED_CBC_SHA");
        g = fexp.b("TLS_RSA_WITH_AES_128_GCM_SHA256");
        h = fexp.b("TLS_RSA_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        fexp.b("TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        fexp.b("TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        fexp.b("TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        fexp.b("TLS_FALLBACK_SCSV");
        fexp.b("TLS_ECDH_ECDSA_WITH_NULL_SHA");
        fexp.b("TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        fexp.b("TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_ECDH_RSA_WITH_NULL_SHA");
        fexp.b("TLS_ECDH_RSA_WITH_RC4_128_SHA");
        fexp.b("TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_ECDHE_RSA_WITH_NULL_SHA");
        fexp.b("TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        fexp.b("TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        i = fexp.b("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        j = fexp.b("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_ECDH_anon_WITH_NULL_SHA");
        fexp.b("TLS_ECDH_anon_WITH_RC4_128_SHA");
        fexp.b("TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        fexp.b("TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        fexp.b("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        fexp.b("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        fexp.b("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        fexp.b("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        k = fexp.b("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        l = fexp.b("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        fexp.b("TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        m = fexp.b("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        n = fexp.b("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        fexp.b("TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        fexp.b("TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        fexp.b("TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        o = fexp.b("TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        p = fexp.b("TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        fexp.b("TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        fexp.b("TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        q = fexp.b("TLS_AES_128_GCM_SHA256");
        r = fexp.b("TLS_AES_256_GCM_SHA384");
        s = fexp.b("TLS_CHACHA20_POLY1305_SHA256");
        fexp.b("TLS_AES_128_CCM_SHA256");
        fexp.b("TLS_AES_128_CCM_8_SHA256");
    }

    public fexq(String str) {
        this.t = str;
    }

    public final String toString() {
        return this.t;
    }
}
