package defpackage;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.bc.BCObjectIdentifiers;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x509.AlgorithmIdentifier;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;

/* compiled from: PG */
/* loaded from: classes6.dex */
public final class ffso {
    private static final Map a;

    static {
        HashMap map = new HashMap();
        a = map;
        map.put(ffni.i, new ffsf());
        map.put(ffni.j, new ffsf());
        map.put(ffni.d, new ffsj());
        map.put(ffni.e, new ffsb());
        map.put(ffni.f, new ffsm());
        map.put(ffni.g, new ffsn());
        map.put(ffjh.a, new ffsm());
        map.put(ffjh.b, new ffsn());
        map.put(PKCSObjectIdentifiers.F, new ffrz());
        map.put(ffni.c, new ffsa());
        map.put(BCObjectIdentifiers.n, new ffsk());
        map.put(BCObjectIdentifiers.o, new ffsk());
        map.put(BCObjectIdentifiers.p, new ffsk());
        map.put(BCObjectIdentifiers.q, new ffsk());
        map.put(BCObjectIdentifiers.r, new ffsk());
        map.put(BCObjectIdentifiers.s, new ffsk());
        map.put(BCObjectIdentifiers.t, new ffsk());
        map.put(BCObjectIdentifiers.u, new ffsk());
        map.put(BCObjectIdentifiers.v, new ffsk());
        map.put(BCObjectIdentifiers.w, new ffsk());
        map.put(BCObjectIdentifiers.x, new ffsk());
        map.put(BCObjectIdentifiers.y, new ffsk());
        map.put(BCObjectIdentifiers.z, new ffsk());
        map.put(BCObjectIdentifiers.A, new ffsk());
        map.put(BCObjectIdentifiers.B, new ffsk());
        map.put(BCObjectIdentifiers.C, new ffsk());
        map.put(BCObjectIdentifiers.D, new ffsk());
        map.put(BCObjectIdentifiers.E, new ffsk());
        map.put(BCObjectIdentifiers.F, new ffsk());
        map.put(BCObjectIdentifiers.G, new ffsk());
        map.put(BCObjectIdentifiers.H, new ffsk());
        map.put(BCObjectIdentifiers.I, new ffsk());
        map.put(BCObjectIdentifiers.J, new ffsk());
        map.put(BCObjectIdentifiers.K, new ffsk());
        map.put(BCObjectIdentifiers.L, new ffsk());
        map.put(BCObjectIdentifiers.M, new ffsk());
        map.put(BCObjectIdentifiers.N, new ffsk());
        map.put(BCObjectIdentifiers.O, new ffsk());
        map.put(BCObjectIdentifiers.P, new ffsk());
        map.put(BCObjectIdentifiers.Q, new ffsk());
        map.put(BCObjectIdentifiers.R, new ffsk());
        map.put(BCObjectIdentifiers.S, new ffsk());
        map.put(BCObjectIdentifiers.T, new ffsk());
        map.put(BCObjectIdentifiers.U, new ffsk());
        map.put(BCObjectIdentifiers.V, new ffsk());
        map.put(BCObjectIdentifiers.W, new ffsk());
        map.put(BCObjectIdentifiers.X, new ffsk());
        map.put(BCObjectIdentifiers.aa, new ffsk());
        map.put(BCObjectIdentifiers.Z, new ffsk());
        map.put(BCObjectIdentifiers.ag, new ffsk());
        map.put(BCObjectIdentifiers.af, new ffsk());
        map.put(BCObjectIdentifiers.ac, new ffsk());
        map.put(BCObjectIdentifiers.ab, new ffsk());
        map.put(BCObjectIdentifiers.ai, new ffsk());
        map.put(BCObjectIdentifiers.ah, new ffsk());
        map.put(BCObjectIdentifiers.ae, new ffsk());
        map.put(BCObjectIdentifiers.ad, new ffsk());
        map.put(BCObjectIdentifiers.ak, new ffsk());
        map.put(BCObjectIdentifiers.aj, new ffsk());
        map.put(new ASN1ObjectIdentifier("1.3.9999.6.4.10"), new ffsk());
        map.put(BCObjectIdentifiers.aU, new ffrt());
        map.put(BCObjectIdentifiers.aV, new ffrt());
        map.put(BCObjectIdentifiers.aW, new ffrt());
        map.put(BCObjectIdentifiers.aX, new ffrt());
        map.put(BCObjectIdentifiers.aY, new ffrt());
        map.put(BCObjectIdentifiers.aZ, new ffrt());
        map.put(BCObjectIdentifiers.ba, new ffrt());
        map.put(BCObjectIdentifiers.bb, new ffrt());
        map.put(BCObjectIdentifiers.bc, new ffrt());
        map.put(BCObjectIdentifiers.bd, new ffrt());
        map.put(BCObjectIdentifiers.bf, new ffrw());
        map.put(BCObjectIdentifiers.bg, new ffrw());
        map.put(BCObjectIdentifiers.bh, new ffrw());
        map.put(BCObjectIdentifiers.bi, new ffrw());
        map.put(BCObjectIdentifiers.bj, new ffrw());
        map.put(BCObjectIdentifiers.bk, new ffrw());
        map.put(BCObjectIdentifiers.bm, new ffsh());
        map.put(BCObjectIdentifiers.bn, new ffsh());
        map.put(BCObjectIdentifiers.bo, new ffsh());
        map.put(BCObjectIdentifiers.bp, new ffsh());
        map.put(BCObjectIdentifiers.bq, new ffsh());
        map.put(BCObjectIdentifiers.br, new ffsh());
        map.put(BCObjectIdentifiers.bs, new ffsh());
        map.put(BCObjectIdentifiers.bt, new ffsh());
        map.put(BCObjectIdentifiers.bu, new ffsh());
        map.put(BCObjectIdentifiers.bv, new ffsh());
        map.put(BCObjectIdentifiers.bw, new ffsh());
        map.put(BCObjectIdentifiers.bx, new ffsh());
        map.put(BCObjectIdentifiers.by, new ffsh());
        map.put(BCObjectIdentifiers.bz, new ffsh());
        map.put(BCObjectIdentifiers.bA, new ffsh());
        map.put(BCObjectIdentifiers.bB, new ffsh());
        map.put(BCObjectIdentifiers.bC, new ffsh());
        map.put(BCObjectIdentifiers.bD, new ffsh());
        map.put(BCObjectIdentifiers.an, new ffse());
        map.put(BCObjectIdentifiers.ao, new ffse());
        map.put(BCObjectIdentifiers.ap, new ffse());
        map.put(BCObjectIdentifiers.aq, new ffse());
        map.put(BCObjectIdentifiers.ar, new ffse());
        map.put(BCObjectIdentifiers.as, new ffse());
        map.put(BCObjectIdentifiers.at, new ffse());
        map.put(BCObjectIdentifiers.au, new ffse());
        map.put(BCObjectIdentifiers.av, new ffse());
        map.put(BCObjectIdentifiers.aw, new ffse());
        map.put(BCObjectIdentifiers.ax, new ffse());
        map.put(BCObjectIdentifiers.ay, new ffse());
        map.put(BCObjectIdentifiers.bG, new ffsd());
        map.put(BCObjectIdentifiers.bH, new ffsd());
        map.put(BCObjectIdentifiers.bI, new ffsd());
        map.put(BCObjectIdentifiers.bK, new ffsd());
        map.put(BCObjectIdentifiers.bJ, new ffsd());
        map.put(BCObjectIdentifiers.bL, new ffsd());
        map.put(BCObjectIdentifiers.aA, new ffrv());
        map.put(BCObjectIdentifiers.aB, new ffrv());
        map.put(BCObjectIdentifiers.bN, new ffry());
        map.put(BCObjectIdentifiers.bO, new ffry());
        map.put(BCObjectIdentifiers.bP, new ffry());
        map.put(BCObjectIdentifiers.bQ, new ffry());
        map.put(BCObjectIdentifiers.bR, new ffry());
        map.put(BCObjectIdentifiers.bS, new ffry());
        map.put(BCObjectIdentifiers.bV, new ffsc());
        map.put(BCObjectIdentifiers.bW, new ffsc());
        map.put(BCObjectIdentifiers.bX, new ffsc());
        map.put(BCObjectIdentifiers.bY, new ffsc());
        map.put(BCObjectIdentifiers.bZ, new ffsc());
        map.put(BCObjectIdentifiers.ca, new ffsc());
        map.put(BCObjectIdentifiers.cc, new ffsi());
        map.put(BCObjectIdentifiers.cd, new ffsi());
        map.put(BCObjectIdentifiers.ce, new ffsi());
        map.put(BCObjectIdentifiers.cf, new ffsi());
        map.put(BCObjectIdentifiers.cg, new ffsi());
        map.put(BCObjectIdentifiers.ch, new ffsi());
        map.put(BCObjectIdentifiers.aC, new ffru());
        map.put(BCObjectIdentifiers.aD, new ffru());
        map.put(BCObjectIdentifiers.aE, new ffru());
        map.put(BCObjectIdentifiers.aF, new ffru());
        map.put(BCObjectIdentifiers.aG, new ffru());
        map.put(BCObjectIdentifiers.aH, new ffru());
        map.put(BCObjectIdentifiers.cj, new ffrs());
        map.put(BCObjectIdentifiers.ck, new ffrs());
        map.put(BCObjectIdentifiers.cl, new ffrs());
        map.put(BCObjectIdentifiers.cn, new ffrx());
        map.put(BCObjectIdentifiers.co, new ffrx());
        map.put(BCObjectIdentifiers.cp, new ffrx());
        map.put(BCObjectIdentifiers.aJ, new ffsg());
        map.put(BCObjectIdentifiers.aK, new ffsg());
        map.put(BCObjectIdentifiers.aL, new ffsg());
        map.put(BCObjectIdentifiers.aM, new ffsg());
        map.put(BCObjectIdentifiers.aN, new ffsg());
        map.put(BCObjectIdentifiers.aO, new ffsg());
    }

    public static ffiz a(SubjectPublicKeyInfo subjectPublicKeyInfo) throws IOException {
        if (subjectPublicKeyInfo == null) {
            throw new IllegalArgumentException("keyInfo argument null");
        }
        AlgorithmIdentifier algorithmIdentifier = subjectPublicKeyInfo.a;
        ffsl ffslVar = (ffsl) a.get(algorithmIdentifier.a);
        if (ffslVar != null) {
            return ffslVar.a(subjectPublicKeyInfo);
        }
        throw new IOException("algorithm identifier in public key not recognised: ".concat(String.valueOf(String.valueOf(algorithmIdentifier.a))));
    }
}
