package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class hlq {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final kcc D;
    public static final kce E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final kcc I;
    public static final kce J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final kcc N;
    public static final kce O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final kcc S;
    public static final kce T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final kcc X;
    public static final kce Y;
    public static final long Z;
    public static final kce a;
    public static final long aA;
    public static final kcc aB;
    public static final kce aC;
    public static final long aD;
    public static final long aE;
    public static final long aF;
    public static final kcc aG;
    public static final kce aH;
    public static final long aI;
    public static final long aJ;
    public static final long aK;
    public static final kcc aL;
    public static final kce aM;
    public static final long aN;
    public static final long aO;
    public static final long aP;
    public static final kcc aQ;
    public static final kce aR;
    public static final long aS;
    public static final long aT;
    public static final long aU;
    public static final kcc aV;
    public static final kce aW;
    public static final long aX;
    public static final long aY;
    public static final long aZ;
    public static final long aa;
    public static final long ab;
    public static final kcc ac;
    public static final kce ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final kcc ah;
    public static final kce ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final kcc am;
    public static final kce an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final kcc ar;
    public static final kce as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final kcc aw;
    public static final kce ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final kce bA;
    public static final long bB;
    public static final long bC;
    public static final long bD;
    public static final kcc bE;
    public static final kce bF;
    public static final long bG;
    public static final long bH;
    public static final long bI;
    public static final kcc bJ;
    public static final kce bK;
    public static final long bL;
    public static final long bM;
    public static final long bN;
    public static final kcc bO;
    public static final kce bP;
    public static final long bQ;
    public static final long bR;
    public static final long bS;
    public static final kcc bT;
    public static final kcc ba;
    public static final kce bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final kcc bf;
    public static final kce bg;
    public static final long bh;
    public static final long bi;
    public static final long bj;
    public static final kcc bk;
    public static final kce bl;
    public static final long bm;
    public static final long bn;
    public static final long bo;
    public static final kcc bp;
    public static final kce bq;
    public static final long br;
    public static final long bs;
    public static final long bt;
    public static final kcc bu;
    public static final kce bv;
    public static final long bw;
    public static final long bx;
    public static final long by;
    public static final kcc bz;
    public static final long c;
    public static final long d;
    public static final kcc e;
    public static final kce f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final kcc j;
    public static final kce k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final kcc o;
    public static final kce p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final kcc t;
    public static final kce u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final kcc y;
    public static final kce z;

    static {
        kce kceVar = hlr.a;
        a = hlr.b;
        b = kjm.a(24.0d);
        c = kjm.c(16);
        d = kjm.a(0.5d);
        e = hlr.e;
        f = hlr.b;
        g = kjm.a(20.0d);
        h = kjm.c(14);
        i = kjm.a(0.2d);
        j = hlr.e;
        k = hlr.b;
        l = kjm.a(16.0d);
        m = kjm.c(12);
        n = kjm.a(0.4d);
        o = hlr.e;
        p = hlr.a;
        q = kjm.a(64.0d);
        r = kjm.c(57);
        long jA = kjm.a(0.2d);
        kjm.e(jA);
        s = kjm.d(kjl.b(jA), -kjl.a(jA));
        t = hlr.e;
        u = hlr.a;
        v = kjm.a(52.0d);
        w = kjm.c(45);
        x = kjm.a(0.0d);
        y = hlr.e;
        z = hlr.a;
        A = kjm.a(44.0d);
        B = kjm.c(36);
        C = kjm.a(0.0d);
        D = hlr.e;
        E = hlr.a;
        F = kjm.a(40.0d);
        G = kjm.c(32);
        H = kjm.a(0.0d);
        I = hlr.e;
        J = hlr.a;
        K = kjm.a(36.0d);
        L = kjm.c(28);
        M = kjm.a(0.0d);
        N = hlr.e;
        O = hlr.a;
        P = kjm.a(32.0d);
        Q = kjm.c(24);
        R = kjm.a(0.0d);
        S = hlr.e;
        T = hlr.b;
        U = kjm.a(20.0d);
        V = kjm.c(14);
        W = kjm.a(0.1d);
        X = hlr.d;
        Y = hlr.b;
        Z = kjm.a(16.0d);
        aa = kjm.c(12);
        ab = kjm.a(0.5d);
        ac = hlr.d;
        ad = hlr.b;
        ae = kjm.a(16.0d);
        af = kjm.c(11);
        ag = kjm.a(0.5d);
        ah = hlr.d;
        ai = hlr.a;
        aj = kjm.a(28.0d);
        ak = kjm.c(22);
        al = kjm.a(0.0d);
        am = hlr.e;
        an = hlr.b;
        ao = kjm.a(24.0d);
        ap = kjm.c(16);
        aq = kjm.a(0.2d);
        ar = hlr.d;
        as = hlr.b;
        at = kjm.a(20.0d);
        au = kjm.c(14);
        av = kjm.a(0.1d);
        aw = hlr.d;
        ax = hlr.b;
        ay = kjm.a(24.0d);
        az = kjm.c(16);
        aA = kjm.a(0.15d);
        aB = hlr.d;
        aC = hlr.b;
        aD = kjm.a(20.0d);
        aE = kjm.c(14);
        aF = kjm.a(0.25d);
        aG = hlr.d;
        aH = hlr.b;
        aI = kjm.a(16.0d);
        aJ = kjm.c(12);
        aK = kjm.a(0.4d);
        aL = hlr.d;
        aM = hlr.a;
        aN = kjm.a(64.0d);
        aO = kjm.c(57);
        aP = kjm.c(0);
        aQ = hlr.d;
        aR = hlr.a;
        aS = kjm.a(52.0d);
        aT = kjm.c(45);
        aU = kjm.c(0);
        aV = hlr.d;
        aW = hlr.a;
        aX = kjm.a(44.0d);
        aY = kjm.c(36);
        aZ = kjm.c(0);
        ba = hlr.d;
        bb = hlr.a;
        bc = kjm.a(40.0d);
        bd = kjm.c(32);
        be = kjm.c(0);
        bf = hlr.d;
        bg = hlr.a;
        bh = kjm.a(36.0d);
        bi = kjm.c(28);
        bj = kjm.c(0);
        bk = hlr.d;
        bl = hlr.a;
        bm = kjm.a(32.0d);
        bn = kjm.c(24);
        bo = kjm.c(0);
        bp = hlr.d;
        bq = hlr.b;
        br = kjm.a(20.0d);
        bs = kjm.c(14);
        bt = kjm.a(0.1d);
        bu = hlr.c;
        bv = hlr.b;
        bw = kjm.a(16.0d);
        bx = kjm.c(12);
        by = kjm.a(0.5d);
        bz = hlr.c;
        bA = hlr.b;
        bB = kjm.a(16.0d);
        bC = kjm.c(11);
        bD = kjm.a(0.5d);
        bE = hlr.c;
        bF = hlr.a;
        bG = kjm.a(28.0d);
        bH = kjm.c(22);
        bI = kjm.c(0);
        bJ = hlr.d;
        bK = hlr.b;
        bL = kjm.a(24.0d);
        bM = kjm.c(16);
        bN = kjm.a(0.15d);
        bO = hlr.c;
        bP = hlr.b;
        bQ = kjm.a(20.0d);
        bR = kjm.c(14);
        bS = kjm.a(0.1d);
        bT = hlr.c;
    }
}
