package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class ktk {
    int a;
    public final ktn b = new ktn();
    public final ktm c = new ktm();
    public final ktl d = new ktl();
    public final kto e = new kto();
    public HashMap f = new HashMap();
    ktj g;

    public final void a(kte kteVar) {
        ktl ktlVar = this.d;
        kteVar.e = ktlVar.j;
        kteVar.f = ktlVar.k;
        kteVar.g = ktlVar.l;
        kteVar.h = ktlVar.m;
        kteVar.i = ktlVar.n;
        kteVar.j = ktlVar.o;
        kteVar.k = ktlVar.p;
        kteVar.l = ktlVar.q;
        kteVar.m = ktlVar.r;
        kteVar.n = ktlVar.s;
        kteVar.o = ktlVar.t;
        kteVar.s = ktlVar.u;
        kteVar.t = ktlVar.v;
        kteVar.u = ktlVar.w;
        kteVar.v = ktlVar.x;
        kteVar.leftMargin = ktlVar.H;
        kteVar.rightMargin = ktlVar.I;
        kteVar.topMargin = ktlVar.J;
        kteVar.bottomMargin = ktlVar.K;
        kteVar.A = ktlVar.T;
        kteVar.B = ktlVar.S;
        kteVar.x = ktlVar.P;
        kteVar.z = ktlVar.R;
        kteVar.G = ktlVar.y;
        kteVar.H = ktlVar.z;
        kteVar.p = ktlVar.B;
        kteVar.q = ktlVar.C;
        kteVar.r = ktlVar.D;
        kteVar.I = ktlVar.A;
        kteVar.X = ktlVar.E;
        kteVar.Y = ktlVar.F;
        kteVar.M = ktlVar.V;
        kteVar.L = ktlVar.W;
        kteVar.O = ktlVar.Y;
        kteVar.N = ktlVar.X;
        kteVar.aa = ktlVar.an;
        kteVar.ab = ktlVar.ao;
        kteVar.P = ktlVar.Z;
        kteVar.Q = ktlVar.aa;
        kteVar.T = ktlVar.ab;
        kteVar.U = ktlVar.ac;
        kteVar.R = ktlVar.ad;
        kteVar.S = ktlVar.ae;
        kteVar.V = ktlVar.af;
        kteVar.W = ktlVar.ag;
        kteVar.Z = ktlVar.G;
        kteVar.c = ktlVar.h;
        kteVar.a = ktlVar.f;
        kteVar.b = ktlVar.g;
        kteVar.width = ktlVar.d;
        kteVar.height = ktlVar.e;
        String str = ktlVar.am;
        if (str != null) {
            kteVar.ac = str;
        }
        kteVar.ad = ktlVar.aq;
        kteVar.setMarginStart(ktlVar.M);
        kteVar.setMarginEnd(ktlVar.L);
        kteVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ktk ktkVar = new ktk();
        ktl ktlVar = ktkVar.d;
        ktl ktlVar2 = this.d;
        ktlVar.b = ktlVar2.b;
        ktlVar.d = ktlVar2.d;
        ktlVar.c = ktlVar2.c;
        ktlVar.e = ktlVar2.e;
        ktlVar.f = ktlVar2.f;
        ktlVar.g = ktlVar2.g;
        ktlVar.h = ktlVar2.h;
        ktlVar.i = ktlVar2.i;
        ktlVar.j = ktlVar2.j;
        ktlVar.k = ktlVar2.k;
        ktlVar.l = ktlVar2.l;
        ktlVar.m = ktlVar2.m;
        ktlVar.n = ktlVar2.n;
        ktlVar.o = ktlVar2.o;
        ktlVar.p = ktlVar2.p;
        ktlVar.q = ktlVar2.q;
        ktlVar.r = ktlVar2.r;
        ktlVar.s = ktlVar2.s;
        ktlVar.t = ktlVar2.t;
        ktlVar.u = ktlVar2.u;
        ktlVar.v = ktlVar2.v;
        ktlVar.w = ktlVar2.w;
        ktlVar.x = ktlVar2.x;
        ktlVar.y = ktlVar2.y;
        ktlVar.z = ktlVar2.z;
        ktlVar.A = ktlVar2.A;
        ktlVar.B = ktlVar2.B;
        ktlVar.C = ktlVar2.C;
        ktlVar.D = ktlVar2.D;
        ktlVar.E = ktlVar2.E;
        ktlVar.F = ktlVar2.F;
        ktlVar.G = ktlVar2.G;
        ktlVar.H = ktlVar2.H;
        ktlVar.I = ktlVar2.I;
        ktlVar.J = ktlVar2.J;
        ktlVar.K = ktlVar2.K;
        ktlVar.L = ktlVar2.L;
        ktlVar.M = ktlVar2.M;
        ktlVar.N = ktlVar2.N;
        ktlVar.O = ktlVar2.O;
        ktlVar.P = ktlVar2.P;
        ktlVar.Q = ktlVar2.Q;
        ktlVar.R = ktlVar2.R;
        ktlVar.S = ktlVar2.S;
        ktlVar.T = ktlVar2.T;
        ktlVar.U = ktlVar2.U;
        ktlVar.V = ktlVar2.V;
        ktlVar.W = ktlVar2.W;
        ktlVar.X = ktlVar2.X;
        ktlVar.Y = ktlVar2.Y;
        ktlVar.Z = ktlVar2.Z;
        ktlVar.aa = ktlVar2.aa;
        ktlVar.ab = ktlVar2.ab;
        ktlVar.ac = ktlVar2.ac;
        ktlVar.ad = ktlVar2.ad;
        ktlVar.ae = ktlVar2.ae;
        ktlVar.af = ktlVar2.af;
        ktlVar.ag = ktlVar2.ag;
        ktlVar.ah = ktlVar2.ah;
        ktlVar.ai = ktlVar2.ai;
        ktlVar.aj = ktlVar2.aj;
        ktlVar.am = ktlVar2.am;
        int[] iArr = ktlVar2.ak;
        if (iArr == null || ktlVar2.al != null) {
            ktlVar.ak = null;
        } else {
            ktlVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        ktlVar.al = ktlVar2.al;
        ktlVar.an = ktlVar2.an;
        ktlVar.ao = ktlVar2.ao;
        ktlVar.ap = ktlVar2.ap;
        ktlVar.aq = ktlVar2.aq;
        ktm ktmVar = ktkVar.c;
        ktm ktmVar2 = this.c;
        ktmVar.b = ktmVar2.b;
        ktmVar.c = ktmVar2.c;
        ktmVar.e = ktmVar2.e;
        ktmVar.f = ktmVar2.f;
        ktmVar.g = ktmVar2.g;
        ktmVar.j = ktmVar2.j;
        ktmVar.h = ktmVar2.h;
        ktmVar.i = ktmVar2.i;
        ktn ktnVar = ktkVar.b;
        ktn ktnVar2 = this.b;
        ktnVar.a = ktnVar2.a;
        ktnVar.b = ktnVar2.b;
        ktnVar.d = ktnVar2.d;
        ktnVar.e = ktnVar2.e;
        ktnVar.c = ktnVar2.c;
        kto ktoVar = ktkVar.e;
        kto ktoVar2 = this.e;
        ktoVar.b = ktoVar2.b;
        ktoVar.c = ktoVar2.c;
        ktoVar.d = ktoVar2.d;
        ktoVar.e = ktoVar2.e;
        ktoVar.f = ktoVar2.f;
        ktoVar.g = ktoVar2.g;
        ktoVar.h = ktoVar2.h;
        ktoVar.i = ktoVar2.i;
        ktoVar.j = ktoVar2.j;
        ktoVar.k = ktoVar2.k;
        ktoVar.l = ktoVar2.l;
        ktoVar.m = ktoVar2.m;
        ktoVar.n = ktoVar2.n;
        ktoVar.o = ktoVar2.o;
        ktkVar.a = this.a;
        ktkVar.g = this.g;
        return ktkVar;
    }
}
