package org.bouncycastle.asn1.x500.style;

import com.android.vcard.VCardConstants;
import java.util.Hashtable;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x500.RDN;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x500.X500NameStyle;
import org.bouncycastle.asn1.x509.X509ObjectIdentifiers;

/* compiled from: PG */
/* loaded from: classes6.dex */
public class BCStyle extends AbstractX500NameStyle {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final X500NameStyle N;
    private static final Hashtable P;
    private static final Hashtable Q;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;
    protected final Hashtable O = d(P);

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifierI = new ASN1ObjectIdentifier("2.5.4.6").i();
        a = aSN1ObjectIdentifierI;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI2 = new ASN1ObjectIdentifier("2.5.4.10").i();
        b = aSN1ObjectIdentifierI2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI3 = new ASN1ObjectIdentifier("2.5.4.11").i();
        c = aSN1ObjectIdentifierI3;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI4 = new ASN1ObjectIdentifier("2.5.4.12").i();
        d = aSN1ObjectIdentifierI4;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI5 = new ASN1ObjectIdentifier("2.5.4.3").i();
        e = aSN1ObjectIdentifierI5;
        new ASN1ObjectIdentifier("2.5.4.5").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifierI6 = new ASN1ObjectIdentifier("2.5.4.9").i();
        f = aSN1ObjectIdentifierI6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI7 = new ASN1ObjectIdentifier("2.5.4.5").i();
        g = aSN1ObjectIdentifierI7;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI8 = new ASN1ObjectIdentifier("2.5.4.7").i();
        h = aSN1ObjectIdentifierI8;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI9 = new ASN1ObjectIdentifier("2.5.4.8").i();
        i = aSN1ObjectIdentifierI9;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI10 = new ASN1ObjectIdentifier("2.5.4.4").i();
        j = aSN1ObjectIdentifierI10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI11 = new ASN1ObjectIdentifier("2.5.4.42").i();
        k = aSN1ObjectIdentifierI11;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI12 = new ASN1ObjectIdentifier("2.5.4.43").i();
        l = aSN1ObjectIdentifierI12;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI13 = new ASN1ObjectIdentifier("2.5.4.44").i();
        m = aSN1ObjectIdentifierI13;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI14 = new ASN1ObjectIdentifier("2.5.4.45").i();
        n = aSN1ObjectIdentifierI14;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI15 = new ASN1ObjectIdentifier("2.5.4.13").i();
        o = aSN1ObjectIdentifierI15;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI16 = new ASN1ObjectIdentifier("2.5.4.15").i();
        p = aSN1ObjectIdentifierI16;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI17 = new ASN1ObjectIdentifier("2.5.4.17").i();
        q = aSN1ObjectIdentifierI17;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI18 = new ASN1ObjectIdentifier("2.5.4.46").i();
        r = aSN1ObjectIdentifierI18;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI19 = new ASN1ObjectIdentifier("2.5.4.65").i();
        s = aSN1ObjectIdentifierI19;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI20 = new ASN1ObjectIdentifier("2.5.4.72").i();
        t = aSN1ObjectIdentifierI20;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI21 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.1").i();
        u = aSN1ObjectIdentifierI21;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI22 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.2").i();
        v = aSN1ObjectIdentifierI22;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI23 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.3").i();
        w = aSN1ObjectIdentifierI23;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI24 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.4").i();
        x = aSN1ObjectIdentifierI24;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI25 = new ASN1ObjectIdentifier("1.3.6.1.5.5.7.9.5").i();
        y = aSN1ObjectIdentifierI25;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI26 = new ASN1ObjectIdentifier("1.3.36.8.3.14").i();
        z = aSN1ObjectIdentifierI26;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI27 = new ASN1ObjectIdentifier("2.5.4.16").i();
        A = aSN1ObjectIdentifierI27;
        new ASN1ObjectIdentifier("2.5.4.54").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifier = X509ObjectIdentifiers.b;
        B = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = X509ObjectIdentifiers.c;
        C = aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = X509ObjectIdentifiers.d;
        D = aSN1ObjectIdentifier3;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = PKCSObjectIdentifiers.w;
        E = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = PKCSObjectIdentifiers.x;
        F = aSN1ObjectIdentifier5;
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = PKCSObjectIdentifiers.z;
        G = aSN1ObjectIdentifier6;
        H = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.25");
        I = aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.1");
        J = aSN1ObjectIdentifier8;
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.3");
        K = aSN1ObjectIdentifier9;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.2");
        L = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.60.2.1.1");
        M = aSN1ObjectIdentifier11;
        Hashtable hashtable = new Hashtable();
        P = hashtable;
        Hashtable hashtable2 = new Hashtable();
        Q = hashtable2;
        hashtable.put(aSN1ObjectIdentifierI, "C");
        hashtable.put(aSN1ObjectIdentifierI2, "O");
        hashtable.put(aSN1ObjectIdentifierI4, "T");
        hashtable.put(aSN1ObjectIdentifierI3, "OU");
        hashtable.put(aSN1ObjectIdentifierI5, "CN");
        hashtable.put(aSN1ObjectIdentifierI8, "L");
        hashtable.put(aSN1ObjectIdentifierI9, "ST");
        hashtable.put(aSN1ObjectIdentifierI7, "SERIALNUMBER");
        hashtable.put(aSN1ObjectIdentifier4, "E");
        hashtable.put(aSN1ObjectIdentifier7, "DC");
        hashtable.put(aSN1ObjectIdentifier8, VCardConstants.PROPERTY_UID);
        hashtable.put(aSN1ObjectIdentifierI6, "STREET");
        hashtable.put(aSN1ObjectIdentifierI10, "SURNAME");
        hashtable.put(aSN1ObjectIdentifierI11, "GIVENNAME");
        hashtable.put(aSN1ObjectIdentifierI12, "INITIALS");
        hashtable.put(aSN1ObjectIdentifierI13, "GENERATION");
        hashtable.put(aSN1ObjectIdentifierI15, "DESCRIPTION");
        hashtable.put(aSN1ObjectIdentifierI20, VCardConstants.PROPERTY_ROLE);
        hashtable.put(aSN1ObjectIdentifier6, "unstructuredAddress");
        hashtable.put(aSN1ObjectIdentifier5, "unstructuredName");
        hashtable.put(aSN1ObjectIdentifierI14, "UniqueIdentifier");
        hashtable.put(aSN1ObjectIdentifierI18, "DN");
        hashtable.put(aSN1ObjectIdentifierI19, "Pseudonym");
        hashtable.put(aSN1ObjectIdentifierI27, "PostalAddress");
        hashtable.put(aSN1ObjectIdentifierI26, "NameAtBirth");
        hashtable.put(aSN1ObjectIdentifierI24, "CountryOfCitizenship");
        hashtable.put(aSN1ObjectIdentifierI25, "CountryOfResidence");
        hashtable.put(aSN1ObjectIdentifierI23, "Gender");
        hashtable.put(aSN1ObjectIdentifierI22, "PlaceOfBirth");
        hashtable.put(aSN1ObjectIdentifierI21, "DateOfBirth");
        hashtable.put(aSN1ObjectIdentifierI17, "PostalCode");
        hashtable.put(aSN1ObjectIdentifierI16, "BusinessCategory");
        hashtable.put(aSN1ObjectIdentifier, "TelephoneNumber");
        hashtable.put(aSN1ObjectIdentifier2, "Name");
        hashtable.put(aSN1ObjectIdentifier3, "organizationIdentifier");
        hashtable.put(aSN1ObjectIdentifier9, "jurisdictionCountry");
        hashtable.put(aSN1ObjectIdentifier10, "jurisdictionState");
        hashtable.put(aSN1ObjectIdentifier11, "jurisdictionLocality");
        hashtable2.put("c", aSN1ObjectIdentifierI);
        hashtable2.put("o", aSN1ObjectIdentifierI2);
        hashtable2.put("t", aSN1ObjectIdentifierI4);
        hashtable2.put("ou", aSN1ObjectIdentifierI3);
        hashtable2.put("cn", aSN1ObjectIdentifierI5);
        hashtable2.put("l", aSN1ObjectIdentifierI8);
        hashtable2.put("st", aSN1ObjectIdentifierI9);
        hashtable2.put("sn", aSN1ObjectIdentifierI10);
        hashtable2.put("serialnumber", aSN1ObjectIdentifierI7);
        hashtable2.put("street", aSN1ObjectIdentifierI6);
        hashtable2.put("emailaddress", aSN1ObjectIdentifier4);
        hashtable2.put("dc", aSN1ObjectIdentifier7);
        hashtable2.put("e", aSN1ObjectIdentifier4);
        hashtable2.put("uid", aSN1ObjectIdentifier8);
        hashtable2.put("surname", aSN1ObjectIdentifierI10);
        hashtable2.put("givenname", aSN1ObjectIdentifierI11);
        hashtable2.put("initials", aSN1ObjectIdentifierI12);
        hashtable2.put("generation", aSN1ObjectIdentifierI13);
        hashtable2.put("description", aSN1ObjectIdentifierI15);
        hashtable2.put("role", aSN1ObjectIdentifierI20);
        hashtable2.put("unstructuredaddress", aSN1ObjectIdentifier6);
        hashtable2.put("unstructuredname", aSN1ObjectIdentifier5);
        hashtable2.put("uniqueidentifier", aSN1ObjectIdentifierI14);
        hashtable2.put("dn", aSN1ObjectIdentifierI18);
        hashtable2.put("pseudonym", aSN1ObjectIdentifierI19);
        hashtable2.put("postaladdress", aSN1ObjectIdentifierI27);
        hashtable2.put("nameatbirth", aSN1ObjectIdentifierI26);
        hashtable2.put("countryofcitizenship", aSN1ObjectIdentifierI24);
        hashtable2.put("countryofresidence", aSN1ObjectIdentifierI25);
        hashtable2.put("gender", aSN1ObjectIdentifierI23);
        hashtable2.put("placeofbirth", aSN1ObjectIdentifierI22);
        hashtable2.put("dateofbirth", aSN1ObjectIdentifierI21);
        hashtable2.put("postalcode", aSN1ObjectIdentifierI17);
        hashtable2.put("businesscategory", aSN1ObjectIdentifierI16);
        hashtable2.put("telephonenumber", aSN1ObjectIdentifier);
        hashtable2.put("name", aSN1ObjectIdentifier2);
        hashtable2.put("organizationidentifier", aSN1ObjectIdentifier3);
        hashtable2.put("jurisdictionCountry", aSN1ObjectIdentifier9);
        hashtable2.put("jurisdictionState", aSN1ObjectIdentifier10);
        hashtable2.put("jurisdictionLocality", aSN1ObjectIdentifier11);
        N = new BCStyle();
    }

    protected BCStyle() {
        d(Q);
    }

    @Override // org.bouncycastle.asn1.x500.X500NameStyle
    public final String b(X500Name x500Name) {
        StringBuffer stringBuffer = new StringBuffer();
        RDN[] rdnArrC = x500Name.c();
        boolean z2 = true;
        int i2 = 0;
        while (i2 < rdnArrC.length) {
            if (!z2) {
                stringBuffer.append(',');
            }
            IETFUtils.c(stringBuffer, rdnArrC[i2], this.O);
            i2++;
            z2 = false;
        }
        return stringBuffer.toString();
    }
}
