package org.bouncycastle.asn1.x500.style;

import com.google.android.ims.rcsservice.chatsession.message.ConversationSuggestion;
import java.util.Hashtable;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.x500.RDN;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x500.X500NameStyle;

/* compiled from: PG */
/* loaded from: classes6.dex */
public class RFC4519Style extends AbstractX500NameStyle {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final X500NameStyle R;
    private static final Hashtable T;
    private static final Hashtable U;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;
    protected final Hashtable S = d(T);

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifierI = new ASN1ObjectIdentifier("2.5.4.15").i();
        a = aSN1ObjectIdentifierI;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI2 = new ASN1ObjectIdentifier("2.5.4.6").i();
        b = aSN1ObjectIdentifierI2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI3 = new ASN1ObjectIdentifier("2.5.4.3").i();
        c = aSN1ObjectIdentifierI3;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI4 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.25").i();
        d = aSN1ObjectIdentifierI4;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI5 = new ASN1ObjectIdentifier("2.5.4.13").i();
        e = aSN1ObjectIdentifierI5;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI6 = new ASN1ObjectIdentifier("2.5.4.27").i();
        f = aSN1ObjectIdentifierI6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI7 = new ASN1ObjectIdentifier("2.5.4.49").i();
        g = aSN1ObjectIdentifierI7;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI8 = new ASN1ObjectIdentifier("2.5.4.46").i();
        h = aSN1ObjectIdentifierI8;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI9 = new ASN1ObjectIdentifier("2.5.4.47").i();
        i = aSN1ObjectIdentifierI9;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI10 = new ASN1ObjectIdentifier("2.5.4.23").i();
        j = aSN1ObjectIdentifierI10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI11 = new ASN1ObjectIdentifier("2.5.4.44").i();
        k = aSN1ObjectIdentifierI11;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI12 = new ASN1ObjectIdentifier("2.5.4.42").i();
        l = aSN1ObjectIdentifierI12;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI13 = new ASN1ObjectIdentifier("2.5.4.51").i();
        m = aSN1ObjectIdentifierI13;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI14 = new ASN1ObjectIdentifier("2.5.4.43").i();
        n = aSN1ObjectIdentifierI14;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI15 = new ASN1ObjectIdentifier("2.5.4.25").i();
        o = aSN1ObjectIdentifierI15;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI16 = new ASN1ObjectIdentifier("2.5.4.7").i();
        p = aSN1ObjectIdentifierI16;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI17 = new ASN1ObjectIdentifier("2.5.4.31").i();
        q = aSN1ObjectIdentifierI17;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI18 = new ASN1ObjectIdentifier("2.5.4.41").i();
        r = aSN1ObjectIdentifierI18;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI19 = new ASN1ObjectIdentifier("2.5.4.10").i();
        s = aSN1ObjectIdentifierI19;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI20 = new ASN1ObjectIdentifier("2.5.4.11").i();
        t = aSN1ObjectIdentifierI20;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI21 = new ASN1ObjectIdentifier("2.5.4.32").i();
        u = aSN1ObjectIdentifierI21;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI22 = new ASN1ObjectIdentifier("2.5.4.19").i();
        v = aSN1ObjectIdentifierI22;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI23 = new ASN1ObjectIdentifier("2.5.4.16").i();
        w = aSN1ObjectIdentifierI23;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI24 = new ASN1ObjectIdentifier("2.5.4.17").i();
        x = aSN1ObjectIdentifierI24;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI25 = new ASN1ObjectIdentifier("2.5.4.18").i();
        y = aSN1ObjectIdentifierI25;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI26 = new ASN1ObjectIdentifier("2.5.4.28").i();
        z = aSN1ObjectIdentifierI26;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI27 = new ASN1ObjectIdentifier("2.5.4.26").i();
        A = aSN1ObjectIdentifierI27;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI28 = new ASN1ObjectIdentifier("2.5.4.33").i();
        B = aSN1ObjectIdentifierI28;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI29 = new ASN1ObjectIdentifier("2.5.4.14").i();
        C = aSN1ObjectIdentifierI29;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI30 = new ASN1ObjectIdentifier("2.5.4.34").i();
        D = aSN1ObjectIdentifierI30;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI31 = new ASN1ObjectIdentifier("2.5.4.5").i();
        E = aSN1ObjectIdentifierI31;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI32 = new ASN1ObjectIdentifier("2.5.4.4").i();
        F = aSN1ObjectIdentifierI32;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI33 = new ASN1ObjectIdentifier("2.5.4.8").i();
        G = aSN1ObjectIdentifierI33;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI34 = new ASN1ObjectIdentifier("2.5.4.9").i();
        H = aSN1ObjectIdentifierI34;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI35 = new ASN1ObjectIdentifier("2.5.4.20").i();
        I = aSN1ObjectIdentifierI35;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI36 = new ASN1ObjectIdentifier("2.5.4.22").i();
        J = aSN1ObjectIdentifierI36;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI37 = new ASN1ObjectIdentifier("2.5.4.21").i();
        K = aSN1ObjectIdentifierI37;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI38 = new ASN1ObjectIdentifier("2.5.4.12").i();
        L = aSN1ObjectIdentifierI38;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI39 = new ASN1ObjectIdentifier("0.9.2342.19200300.100.1.1").i();
        M = aSN1ObjectIdentifierI39;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI40 = new ASN1ObjectIdentifier("2.5.4.50").i();
        N = aSN1ObjectIdentifierI40;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI41 = new ASN1ObjectIdentifier("2.5.4.35").i();
        O = aSN1ObjectIdentifierI41;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI42 = new ASN1ObjectIdentifier("2.5.4.24").i();
        P = aSN1ObjectIdentifierI42;
        ASN1ObjectIdentifier aSN1ObjectIdentifierI43 = new ASN1ObjectIdentifier("2.5.4.45").i();
        Q = aSN1ObjectIdentifierI43;
        Hashtable hashtable = new Hashtable();
        T = hashtable;
        Hashtable hashtable2 = new Hashtable();
        U = hashtable2;
        hashtable.put(aSN1ObjectIdentifierI, "businessCategory");
        hashtable.put(aSN1ObjectIdentifierI2, "c");
        hashtable.put(aSN1ObjectIdentifierI3, "cn");
        hashtable.put(aSN1ObjectIdentifierI4, "dc");
        hashtable.put(aSN1ObjectIdentifierI5, "description");
        hashtable.put(aSN1ObjectIdentifierI6, "destinationIndicator");
        hashtable.put(aSN1ObjectIdentifierI7, "distinguishedName");
        hashtable.put(aSN1ObjectIdentifierI8, "dnQualifier");
        hashtable.put(aSN1ObjectIdentifierI9, "enhancedSearchGuide");
        hashtable.put(aSN1ObjectIdentifierI10, "facsimileTelephoneNumber");
        hashtable.put(aSN1ObjectIdentifierI11, "generationQualifier");
        hashtable.put(aSN1ObjectIdentifierI12, "givenName");
        hashtable.put(aSN1ObjectIdentifierI13, "houseIdentifier");
        hashtable.put(aSN1ObjectIdentifierI14, "initials");
        hashtable.put(aSN1ObjectIdentifierI15, "internationalISDNNumber");
        hashtable.put(aSN1ObjectIdentifierI16, "l");
        hashtable.put(aSN1ObjectIdentifierI17, "member");
        hashtable.put(aSN1ObjectIdentifierI18, "name");
        hashtable.put(aSN1ObjectIdentifierI19, "o");
        hashtable.put(aSN1ObjectIdentifierI20, "ou");
        hashtable.put(aSN1ObjectIdentifierI21, "owner");
        hashtable.put(aSN1ObjectIdentifierI22, "physicalDeliveryOfficeName");
        hashtable.put(aSN1ObjectIdentifierI23, "postalAddress");
        hashtable.put(aSN1ObjectIdentifierI24, "postalCode");
        hashtable.put(aSN1ObjectIdentifierI25, "postOfficeBox");
        hashtable.put(aSN1ObjectIdentifierI26, "preferredDeliveryMethod");
        hashtable.put(aSN1ObjectIdentifierI27, "registeredAddress");
        hashtable.put(aSN1ObjectIdentifierI28, "roleOccupant");
        hashtable.put(aSN1ObjectIdentifierI29, "searchGuide");
        hashtable.put(aSN1ObjectIdentifierI30, "seeAlso");
        hashtable.put(aSN1ObjectIdentifierI31, "serialNumber");
        hashtable.put(aSN1ObjectIdentifierI32, "sn");
        hashtable.put(aSN1ObjectIdentifierI33, "st");
        hashtable.put(aSN1ObjectIdentifierI34, "street");
        hashtable.put(aSN1ObjectIdentifierI35, "telephoneNumber");
        hashtable.put(aSN1ObjectIdentifierI36, "teletexTerminalIdentifier");
        hashtable.put(aSN1ObjectIdentifierI37, "telexNumber");
        hashtable.put(aSN1ObjectIdentifierI38, ConversationSuggestion.SUGGESTION_PROPERTY_CALENDAR_TITLE);
        hashtable.put(aSN1ObjectIdentifierI39, "uid");
        hashtable.put(aSN1ObjectIdentifierI40, "uniqueMember");
        hashtable.put(aSN1ObjectIdentifierI41, "userPassword");
        hashtable.put(aSN1ObjectIdentifierI42, "x121Address");
        hashtable.put(aSN1ObjectIdentifierI43, "x500UniqueIdentifier");
        hashtable2.put("businesscategory", aSN1ObjectIdentifierI);
        hashtable2.put("c", aSN1ObjectIdentifierI2);
        hashtable2.put("cn", aSN1ObjectIdentifierI3);
        hashtable2.put("dc", aSN1ObjectIdentifierI4);
        hashtable2.put("description", aSN1ObjectIdentifierI5);
        hashtable2.put("destinationindicator", aSN1ObjectIdentifierI6);
        hashtable2.put("distinguishedname", aSN1ObjectIdentifierI7);
        hashtable2.put("dnqualifier", aSN1ObjectIdentifierI8);
        hashtable2.put("enhancedsearchguide", aSN1ObjectIdentifierI9);
        hashtable2.put("facsimiletelephonenumber", aSN1ObjectIdentifierI10);
        hashtable2.put("generationqualifier", aSN1ObjectIdentifierI11);
        hashtable2.put("givenname", aSN1ObjectIdentifierI12);
        hashtable2.put("houseidentifier", aSN1ObjectIdentifierI13);
        hashtable2.put("initials", aSN1ObjectIdentifierI14);
        hashtable2.put("internationalisdnnumber", aSN1ObjectIdentifierI15);
        hashtable2.put("l", aSN1ObjectIdentifierI16);
        hashtable2.put("member", aSN1ObjectIdentifierI17);
        hashtable2.put("name", aSN1ObjectIdentifierI18);
        hashtable2.put("o", aSN1ObjectIdentifierI19);
        hashtable2.put("ou", aSN1ObjectIdentifierI20);
        hashtable2.put("owner", aSN1ObjectIdentifierI21);
        hashtable2.put("physicaldeliveryofficename", aSN1ObjectIdentifierI22);
        hashtable2.put("postaladdress", aSN1ObjectIdentifierI23);
        hashtable2.put("postalcode", aSN1ObjectIdentifierI24);
        hashtable2.put("postofficebox", aSN1ObjectIdentifierI25);
        hashtable2.put("preferreddeliverymethod", aSN1ObjectIdentifierI26);
        hashtable2.put("registeredaddress", aSN1ObjectIdentifierI27);
        hashtable2.put("roleoccupant", aSN1ObjectIdentifierI28);
        hashtable2.put("searchguide", aSN1ObjectIdentifierI29);
        hashtable2.put("seealso", aSN1ObjectIdentifierI30);
        hashtable2.put("serialnumber", aSN1ObjectIdentifierI31);
        hashtable2.put("sn", aSN1ObjectIdentifierI32);
        hashtable2.put("st", aSN1ObjectIdentifierI33);
        hashtable2.put("street", aSN1ObjectIdentifierI34);
        hashtable2.put("telephonenumber", aSN1ObjectIdentifierI35);
        hashtable2.put("teletexterminalidentifier", aSN1ObjectIdentifierI36);
        hashtable2.put("telexnumber", aSN1ObjectIdentifierI37);
        hashtable2.put(ConversationSuggestion.SUGGESTION_PROPERTY_CALENDAR_TITLE, aSN1ObjectIdentifierI38);
        hashtable2.put("uid", aSN1ObjectIdentifierI39);
        hashtable2.put("uniquemember", aSN1ObjectIdentifierI40);
        hashtable2.put("userpassword", aSN1ObjectIdentifierI41);
        hashtable2.put("x121address", aSN1ObjectIdentifierI42);
        hashtable2.put("x500uniqueidentifier", aSN1ObjectIdentifierI43);
        R = new RFC4519Style();
    }

    protected RFC4519Style() {
        d(U);
    }

    @Override // org.bouncycastle.asn1.x500.X500NameStyle
    public final String b(X500Name x500Name) {
        StringBuffer stringBuffer = new StringBuffer();
        RDN[] rdnArrC = x500Name.c();
        int length = rdnArrC.length - 1;
        boolean z2 = true;
        while (length >= 0) {
            if (!z2) {
                stringBuffer.append(',');
            }
            IETFUtils.c(stringBuffer, rdnArrC[length], this.S);
            length--;
            z2 = false;
        }
        return stringBuffer.toString();
    }
}
