package org.bouncycastle.asn1.bc;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier aA;
    public static final ASN1ObjectIdentifier aB;
    public static final ASN1ObjectIdentifier aC;
    public static final ASN1ObjectIdentifier aD;
    public static final ASN1ObjectIdentifier aE;
    public static final ASN1ObjectIdentifier aF;
    public static final ASN1ObjectIdentifier aG;
    public static final ASN1ObjectIdentifier aH;
    public static final ASN1ObjectIdentifier aI;
    public static final ASN1ObjectIdentifier aJ;
    public static final ASN1ObjectIdentifier aK;
    public static final ASN1ObjectIdentifier aL;
    public static final ASN1ObjectIdentifier aM;
    public static final ASN1ObjectIdentifier aN;
    public static final ASN1ObjectIdentifier aO;
    public static final ASN1ObjectIdentifier aP;
    public static final ASN1ObjectIdentifier aQ;
    public static final ASN1ObjectIdentifier aR;
    public static final ASN1ObjectIdentifier aS;
    public static final ASN1ObjectIdentifier aT;
    public static final ASN1ObjectIdentifier aU;
    public static final ASN1ObjectIdentifier aV;
    public static final ASN1ObjectIdentifier aW;
    public static final ASN1ObjectIdentifier aX;
    public static final ASN1ObjectIdentifier aY;
    public static final ASN1ObjectIdentifier aZ;
    public static final ASN1ObjectIdentifier aa;
    public static final ASN1ObjectIdentifier ab;
    public static final ASN1ObjectIdentifier ac;
    public static final ASN1ObjectIdentifier ad;
    public static final ASN1ObjectIdentifier ae;
    public static final ASN1ObjectIdentifier af;
    public static final ASN1ObjectIdentifier ag;
    public static final ASN1ObjectIdentifier ah;
    public static final ASN1ObjectIdentifier ai;
    public static final ASN1ObjectIdentifier aj;
    public static final ASN1ObjectIdentifier ak;
    public static final ASN1ObjectIdentifier al;
    public static final ASN1ObjectIdentifier am;
    public static final ASN1ObjectIdentifier an;
    public static final ASN1ObjectIdentifier ao;
    public static final ASN1ObjectIdentifier ap;
    public static final ASN1ObjectIdentifier aq;
    public static final ASN1ObjectIdentifier ar;
    public static final ASN1ObjectIdentifier as;
    public static final ASN1ObjectIdentifier at;
    public static final ASN1ObjectIdentifier au;
    public static final ASN1ObjectIdentifier av;
    public static final ASN1ObjectIdentifier aw;
    public static final ASN1ObjectIdentifier ax;
    public static final ASN1ObjectIdentifier ay;
    public static final ASN1ObjectIdentifier az;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier bA;
    public static final ASN1ObjectIdentifier bB;
    public static final ASN1ObjectIdentifier bC;
    public static final ASN1ObjectIdentifier bD;
    public static final ASN1ObjectIdentifier bE;
    public static final ASN1ObjectIdentifier bF;
    public static final ASN1ObjectIdentifier bG;
    public static final ASN1ObjectIdentifier bH;
    public static final ASN1ObjectIdentifier bI;
    public static final ASN1ObjectIdentifier bJ;
    public static final ASN1ObjectIdentifier bK;
    public static final ASN1ObjectIdentifier bL;
    public static final ASN1ObjectIdentifier bM;
    public static final ASN1ObjectIdentifier bN;
    public static final ASN1ObjectIdentifier bO;
    public static final ASN1ObjectIdentifier bP;
    public static final ASN1ObjectIdentifier bQ;
    public static final ASN1ObjectIdentifier bR;
    public static final ASN1ObjectIdentifier bS;
    public static final ASN1ObjectIdentifier bT;
    public static final ASN1ObjectIdentifier bU;
    public static final ASN1ObjectIdentifier bV;
    public static final ASN1ObjectIdentifier bW;
    public static final ASN1ObjectIdentifier bX;
    public static final ASN1ObjectIdentifier bY;
    public static final ASN1ObjectIdentifier bZ;
    public static final ASN1ObjectIdentifier ba;
    public static final ASN1ObjectIdentifier bb;
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bd;
    public static final ASN1ObjectIdentifier be;
    public static final ASN1ObjectIdentifier bf;
    public static final ASN1ObjectIdentifier bg;
    public static final ASN1ObjectIdentifier bh;
    public static final ASN1ObjectIdentifier bi;
    public static final ASN1ObjectIdentifier bj;
    public static final ASN1ObjectIdentifier bk;
    public static final ASN1ObjectIdentifier bl;
    public static final ASN1ObjectIdentifier bm;
    public static final ASN1ObjectIdentifier bn;
    public static final ASN1ObjectIdentifier bo;
    public static final ASN1ObjectIdentifier bp;
    public static final ASN1ObjectIdentifier bq;
    public static final ASN1ObjectIdentifier br;
    public static final ASN1ObjectIdentifier bs;
    public static final ASN1ObjectIdentifier bt;
    public static final ASN1ObjectIdentifier bu;
    public static final ASN1ObjectIdentifier bv;
    public static final ASN1ObjectIdentifier bw;
    public static final ASN1ObjectIdentifier bx;
    public static final ASN1ObjectIdentifier by;
    public static final ASN1ObjectIdentifier bz;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier ca;
    public static final ASN1ObjectIdentifier cb;
    public static final ASN1ObjectIdentifier cc;
    public static final ASN1ObjectIdentifier cd;
    public static final ASN1ObjectIdentifier ce;
    public static final ASN1ObjectIdentifier cf;
    public static final ASN1ObjectIdentifier cg;
    public static final ASN1ObjectIdentifier ch;
    public static final ASN1ObjectIdentifier ci;
    public static final ASN1ObjectIdentifier cj;
    public static final ASN1ObjectIdentifier ck;
    public static final ASN1ObjectIdentifier cl;
    public static final ASN1ObjectIdentifier cm;
    public static final ASN1ObjectIdentifier cn;
    public static final ASN1ObjectIdentifier co;
    public static final ASN1ObjectIdentifier cp;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF = aSN1ObjectIdentifier.f("1");
        b = aSN1ObjectIdentifierF;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF2 = aSN1ObjectIdentifierF.f("1");
        c = aSN1ObjectIdentifierF2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF3 = aSN1ObjectIdentifierF.f(VCardConstants.VERSION_V21);
        d = aSN1ObjectIdentifierF3;
        aSN1ObjectIdentifierF.f("2.2");
        aSN1ObjectIdentifierF.f("2.3");
        aSN1ObjectIdentifierF.f("2.4");
        aSN1ObjectIdentifierF2.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF4 = aSN1ObjectIdentifierF2.f("2");
        e = aSN1ObjectIdentifierF4;
        aSN1ObjectIdentifierF3.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF5 = aSN1ObjectIdentifierF3.f("2");
        f = aSN1ObjectIdentifierF5;
        aSN1ObjectIdentifierF4.f("1.2");
        aSN1ObjectIdentifierF4.f("1.22");
        aSN1ObjectIdentifierF4.f("1.42");
        aSN1ObjectIdentifierF5.f("1.2");
        aSN1ObjectIdentifierF5.f("1.22");
        aSN1ObjectIdentifierF5.f("1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF6 = aSN1ObjectIdentifier.f("2");
        g = aSN1ObjectIdentifierF6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF7 = aSN1ObjectIdentifierF6.f("1");
        h = aSN1ObjectIdentifierF7;
        aSN1ObjectIdentifierF7.f("1");
        aSN1ObjectIdentifierF7.f("2");
        aSN1ObjectIdentifierF7.f("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF8 = aSN1ObjectIdentifierF6.f("2");
        i = aSN1ObjectIdentifierF8;
        aSN1ObjectIdentifierF8.f("1");
        aSN1ObjectIdentifierF8.f("2");
        aSN1ObjectIdentifierF8.f("3");
        aSN1ObjectIdentifierF8.f("4");
        aSN1ObjectIdentifierF8.f("5");
        aSN1ObjectIdentifierF8.f("6");
        aSN1ObjectIdentifierF8.f("7");
        aSN1ObjectIdentifierF8.f("8");
        aSN1ObjectIdentifierF8.f("9");
        aSN1ObjectIdentifierF8.f("10");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF9 = aSN1ObjectIdentifierF6.f("3");
        j = aSN1ObjectIdentifierF9;
        aSN1ObjectIdentifierF9.f("1");
        aSN1ObjectIdentifierF9.f("2");
        aSN1ObjectIdentifierF9.f("3");
        aSN1ObjectIdentifierF9.f("4");
        aSN1ObjectIdentifierF9.f("5");
        aSN1ObjectIdentifierF9.f("6");
        aSN1ObjectIdentifierF9.f("7");
        aSN1ObjectIdentifierF9.f("8");
        aSN1ObjectIdentifierF9.f("9");
        aSN1ObjectIdentifierF9.f("10");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF10 = aSN1ObjectIdentifierF6.f("4");
        k = aSN1ObjectIdentifierF10;
        aSN1ObjectIdentifierF10.f("1");
        aSN1ObjectIdentifierF10.f("2");
        aSN1ObjectIdentifierF10.f("3");
        aSN1ObjectIdentifierF10.f("4");
        aSN1ObjectIdentifierF10.f("5");
        l = aSN1ObjectIdentifierF10.f("11");
        m = aSN1ObjectIdentifierF10.f("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF11 = aSN1ObjectIdentifierF6.f("5");
        n = aSN1ObjectIdentifierF11;
        o = aSN1ObjectIdentifierF11.f("1");
        p = aSN1ObjectIdentifierF11.f("2");
        q = aSN1ObjectIdentifierF11.f("3");
        r = aSN1ObjectIdentifierF11.f("4");
        s = aSN1ObjectIdentifierF11.f("5");
        t = aSN1ObjectIdentifierF11.f("6");
        u = aSN1ObjectIdentifierF11.f("7");
        v = aSN1ObjectIdentifierF11.f("8");
        w = aSN1ObjectIdentifierF11.f("9");
        x = aSN1ObjectIdentifierF11.f("10");
        y = aSN1ObjectIdentifierF11.f("11");
        z = aSN1ObjectIdentifierF11.f("12");
        A = aSN1ObjectIdentifierF11.f("13");
        B = aSN1ObjectIdentifierF11.f("14");
        C = aSN1ObjectIdentifierF11.f("15");
        D = aSN1ObjectIdentifierF11.f("16");
        E = aSN1ObjectIdentifierF11.f("17");
        F = aSN1ObjectIdentifierF11.f("18");
        G = aSN1ObjectIdentifierF11.f("19");
        H = aSN1ObjectIdentifierF11.f("20");
        I = aSN1ObjectIdentifierF11.f("21");
        J = aSN1ObjectIdentifierF11.f("22");
        K = aSN1ObjectIdentifierF11.f("23");
        L = aSN1ObjectIdentifierF11.f("24");
        M = aSN1ObjectIdentifierF11.f("25");
        N = aSN1ObjectIdentifierF11.f("26");
        O = aSN1ObjectIdentifierF11.f("27");
        P = aSN1ObjectIdentifierF11.f("28");
        Q = aSN1ObjectIdentifierF11.f("29");
        R = aSN1ObjectIdentifierF11.f("30");
        S = aSN1ObjectIdentifierF11.f("31");
        T = aSN1ObjectIdentifierF11.f("32");
        U = aSN1ObjectIdentifierF11.f("33");
        V = aSN1ObjectIdentifierF11.f("34");
        W = aSN1ObjectIdentifierF11.f("35");
        X = aSN1ObjectIdentifierF11.f("36");
        Y = new ASN1ObjectIdentifier("1.3.9999.6");
        Z = new ASN1ObjectIdentifier("1.3.9999.6.4.13");
        aa = new ASN1ObjectIdentifier("1.3.9999.6.4.16");
        ab = new ASN1ObjectIdentifier("1.3.9999.6.5.10");
        ac = new ASN1ObjectIdentifier("1.3.9999.6.5.12");
        ad = new ASN1ObjectIdentifier("1.3.9999.6.6.10");
        ae = new ASN1ObjectIdentifier("1.3.9999.6.6.12");
        af = new ASN1ObjectIdentifier("1.3.9999.6.7.13");
        ag = new ASN1ObjectIdentifier("1.3.9999.6.7.16");
        ah = new ASN1ObjectIdentifier("1.3.9999.6.8.10");
        ai = new ASN1ObjectIdentifier("1.3.9999.6.8.12");
        aj = new ASN1ObjectIdentifier("1.3.9999.6.9.10");
        ak = new ASN1ObjectIdentifier("1.3.9999.6.9.12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF12 = aSN1ObjectIdentifierF6.f("6");
        al = aSN1ObjectIdentifierF12;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF13 = aSN1ObjectIdentifierF12.f("1");
        am = aSN1ObjectIdentifierF13;
        an = aSN1ObjectIdentifierF13.f("1");
        ao = aSN1ObjectIdentifierF13.f("2");
        ap = aSN1ObjectIdentifierF13.f("3");
        aq = aSN1ObjectIdentifierF13.f("4");
        ar = aSN1ObjectIdentifierF13.f("5");
        as = aSN1ObjectIdentifierF13.f("6");
        at = aSN1ObjectIdentifierF13.f("7");
        au = aSN1ObjectIdentifierF13.f("8");
        av = aSN1ObjectIdentifierF13.f("9");
        aw = aSN1ObjectIdentifierF13.f("10");
        ax = aSN1ObjectIdentifierF13.f("11");
        ay = aSN1ObjectIdentifierF13.f("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF14 = aSN1ObjectIdentifierF12.f("2");
        az = aSN1ObjectIdentifierF14;
        aSN1ObjectIdentifierF14.f("1");
        aSN1ObjectIdentifierF14.f("2");
        aSN1ObjectIdentifierF14.f("3");
        aSN1ObjectIdentifierF6.f("7");
        aA = new ASN1ObjectIdentifier("1.3.9999.3.6");
        aB = new ASN1ObjectIdentifier("1.3.9999.3.9");
        aSN1ObjectIdentifierF6.f("8");
        aC = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.4.4");
        aD = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.6.5");
        aE = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.8.7");
        aF = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.4.4");
        aG = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.6.5");
        aH = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.8.7");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF15 = aSN1ObjectIdentifierF6.f("9");
        aI = aSN1ObjectIdentifierF15;
        aJ = aSN1ObjectIdentifierF15.f("1");
        aK = aSN1ObjectIdentifierF15.f("2");
        aL = aSN1ObjectIdentifierF15.f("3");
        aM = aSN1ObjectIdentifierF15.f("4");
        aN = aSN1ObjectIdentifierF15.f("5");
        aO = aSN1ObjectIdentifierF15.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF16 = aSN1ObjectIdentifier.f("3");
        aP = aSN1ObjectIdentifierF16;
        aQ = aSN1ObjectIdentifierF16.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF17 = aSN1ObjectIdentifier.f("4");
        aR = aSN1ObjectIdentifierF17;
        aSN1ObjectIdentifierF17.f("1");
        aSN1ObjectIdentifierF17.f("2");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF18 = aSN1ObjectIdentifier.f("5");
        aS = aSN1ObjectIdentifierF18;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF19 = aSN1ObjectIdentifierF18.f("1");
        aT = aSN1ObjectIdentifierF19;
        aU = aSN1ObjectIdentifierF19.f("1");
        aV = aSN1ObjectIdentifierF19.f("2");
        aW = aSN1ObjectIdentifierF19.f("3");
        aX = aSN1ObjectIdentifierF19.f("4");
        aY = aSN1ObjectIdentifierF19.f("5");
        aZ = aSN1ObjectIdentifierF19.f("6");
        ba = aSN1ObjectIdentifierF19.f("7");
        bb = aSN1ObjectIdentifierF19.f("8");
        bc = aSN1ObjectIdentifierF19.f("9");
        bd = aSN1ObjectIdentifierF19.f("10");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF20 = aSN1ObjectIdentifierF18.f("2");
        be = aSN1ObjectIdentifierF20;
        bf = aSN1ObjectIdentifierF20.f("1");
        bg = aSN1ObjectIdentifierF20.f("2");
        bh = aSN1ObjectIdentifierF20.f("3");
        bi = aSN1ObjectIdentifierF20.f("4");
        bj = aSN1ObjectIdentifierF20.f("5");
        bk = aSN1ObjectIdentifierF20.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF21 = aSN1ObjectIdentifierF18.f("3");
        bl = aSN1ObjectIdentifierF21;
        bm = aSN1ObjectIdentifierF21.f("1");
        bn = aSN1ObjectIdentifierF21.f("2");
        bo = aSN1ObjectIdentifierF21.f("3");
        bp = aSN1ObjectIdentifierF21.f("4");
        bq = aSN1ObjectIdentifierF21.f("5");
        br = aSN1ObjectIdentifierF21.f("6");
        bs = aSN1ObjectIdentifierF21.f("7");
        bt = aSN1ObjectIdentifierF21.f("8");
        bu = aSN1ObjectIdentifierF21.f("9");
        bv = aSN1ObjectIdentifierF21.f("10");
        bw = aSN1ObjectIdentifierF21.f("11");
        bx = aSN1ObjectIdentifierF21.f("12");
        by = aSN1ObjectIdentifierF21.f("13");
        bz = aSN1ObjectIdentifierF21.f("14");
        bA = aSN1ObjectIdentifierF21.f("15");
        bB = aSN1ObjectIdentifierF21.f("16");
        bC = aSN1ObjectIdentifierF21.f("17");
        bD = aSN1ObjectIdentifierF21.f("18");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF22 = aSN1ObjectIdentifierF18.f("4");
        bE = aSN1ObjectIdentifierF22;
        aSN1ObjectIdentifierF22.f("1");
        aSN1ObjectIdentifierF22.f("2");
        aSN1ObjectIdentifierF22.f("3");
        aSN1ObjectIdentifierF22.f("4");
        aSN1ObjectIdentifierF22.f("5");
        aSN1ObjectIdentifierF22.f("6");
        aSN1ObjectIdentifierF22.f("7");
        aSN1ObjectIdentifierF22.f("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF23 = aSN1ObjectIdentifierF18.f("5");
        bF = aSN1ObjectIdentifierF23;
        bG = aSN1ObjectIdentifierF23.f("1");
        bH = aSN1ObjectIdentifierF23.f("2");
        bI = aSN1ObjectIdentifierF23.f("3");
        bJ = aSN1ObjectIdentifierF23.f("4");
        bK = aSN1ObjectIdentifierF23.f("5");
        bL = aSN1ObjectIdentifierF23.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF24 = aSN1ObjectIdentifierF18.f("6");
        bM = aSN1ObjectIdentifierF24;
        bN = aSN1ObjectIdentifierF24.f("1");
        bO = aSN1ObjectIdentifierF24.f("2");
        bP = aSN1ObjectIdentifierF24.f("3");
        bQ = aSN1ObjectIdentifierF24.f("4");
        bR = aSN1ObjectIdentifierF24.f("5");
        bS = aSN1ObjectIdentifierF24.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF25 = aSN1ObjectIdentifierF18.f("7");
        bT = aSN1ObjectIdentifierF25;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF26 = aSN1ObjectIdentifierF25.f("1");
        bU = aSN1ObjectIdentifierF26;
        bV = aSN1ObjectIdentifierF26.f("1");
        bW = aSN1ObjectIdentifierF26.f("2");
        bX = aSN1ObjectIdentifierF26.f("3");
        bY = aSN1ObjectIdentifierF26.f("4");
        bZ = aSN1ObjectIdentifierF26.f("5");
        ca = aSN1ObjectIdentifierF26.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF27 = aSN1ObjectIdentifierF25.f("2");
        cb = aSN1ObjectIdentifierF27;
        cc = aSN1ObjectIdentifierF27.f("1");
        cd = aSN1ObjectIdentifierF27.f("2");
        ce = aSN1ObjectIdentifierF27.f("3");
        cf = aSN1ObjectIdentifierF27.f("4");
        cg = aSN1ObjectIdentifierF27.f("5");
        ch = aSN1ObjectIdentifierF27.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF28 = aSN1ObjectIdentifierF18.f("8");
        ci = aSN1ObjectIdentifierF28;
        cj = aSN1ObjectIdentifierF28.f("1");
        ck = aSN1ObjectIdentifierF28.f("2");
        cl = aSN1ObjectIdentifierF28.f("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF29 = aSN1ObjectIdentifierF18.f("9");
        cm = aSN1ObjectIdentifierF29;
        cn = aSN1ObjectIdentifierF29.f("1");
        co = aSN1ObjectIdentifierF29.f("2");
        cp = aSN1ObjectIdentifierF29.f("3");
    }
}
