package org.bouncycastle.asn1.x9;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        c = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF = aSN1ObjectIdentifier.f("1");
        d = aSN1ObjectIdentifierF;
        e = aSN1ObjectIdentifierF.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF2 = aSN1ObjectIdentifierF.f("2");
        f = aSN1ObjectIdentifierF2;
        aSN1ObjectIdentifierF2.f("3.1");
        g = aSN1ObjectIdentifierF2.f("3.2");
        h = aSN1ObjectIdentifierF2.f("3.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF3 = aSN1ObjectIdentifier.f("4");
        i = aSN1ObjectIdentifierF3;
        j = aSN1ObjectIdentifierF3.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF4 = aSN1ObjectIdentifier.f("2");
        k = aSN1ObjectIdentifierF4;
        l = aSN1ObjectIdentifierF4.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF5 = aSN1ObjectIdentifierF3.f("3");
        m = aSN1ObjectIdentifierF5;
        n = aSN1ObjectIdentifierF5.f("1");
        o = aSN1ObjectIdentifierF5.f("2");
        p = aSN1ObjectIdentifierF5.f("3");
        q = aSN1ObjectIdentifierF5.f("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF6 = aSN1ObjectIdentifier.f("3");
        r = aSN1ObjectIdentifierF6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF7 = aSN1ObjectIdentifierF6.f("0");
        s = aSN1ObjectIdentifierF7;
        t = aSN1ObjectIdentifierF7.f("1");
        u = aSN1ObjectIdentifierF7.f("2");
        v = aSN1ObjectIdentifierF7.f("3");
        w = aSN1ObjectIdentifierF7.f("4");
        x = aSN1ObjectIdentifierF7.f("5");
        y = aSN1ObjectIdentifierF7.f("6");
        z = aSN1ObjectIdentifierF7.f("7");
        aSN1ObjectIdentifierF7.f("8");
        aSN1ObjectIdentifierF7.f("9");
        A = aSN1ObjectIdentifierF7.f("10");
        B = aSN1ObjectIdentifierF7.f("11");
        C = aSN1ObjectIdentifierF7.f("12");
        D = aSN1ObjectIdentifierF7.f("13");
        aSN1ObjectIdentifierF7.f("14");
        aSN1ObjectIdentifierF7.f("15");
        E = aSN1ObjectIdentifierF7.f("16");
        F = aSN1ObjectIdentifierF7.f("17");
        G = aSN1ObjectIdentifierF7.f("18");
        H = aSN1ObjectIdentifierF7.f("19");
        I = aSN1ObjectIdentifierF7.f("20");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF8 = aSN1ObjectIdentifierF6.f("1");
        J = aSN1ObjectIdentifierF8;
        K = aSN1ObjectIdentifierF8.f("1");
        L = aSN1ObjectIdentifierF8.f("2");
        M = aSN1ObjectIdentifierF8.f("3");
        N = aSN1ObjectIdentifierF8.f("4");
        O = aSN1ObjectIdentifierF8.f("5");
        P = aSN1ObjectIdentifierF8.f("6");
        Q = aSN1ObjectIdentifierF8.f("7");
        R = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        S = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        T = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.f("2");
        aSN1ObjectIdentifier2.f("3");
        aSN1ObjectIdentifier2.f("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.10046");
        U = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.f(VCardConstants.VERSION_V21);
        ASN1ObjectIdentifier aSN1ObjectIdentifierF9 = aSN1ObjectIdentifier3.f("3");
        V = aSN1ObjectIdentifierF9;
        aSN1ObjectIdentifierF9.f("1");
        aSN1ObjectIdentifierF9.f("2");
        aSN1ObjectIdentifierF9.f("3");
        aSN1ObjectIdentifierF9.f("4");
        aSN1ObjectIdentifierF9.f("5");
        aSN1ObjectIdentifierF9.f("6");
        aSN1ObjectIdentifierF9.f("7");
        aSN1ObjectIdentifierF9.f("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        W = aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF10 = aSN1ObjectIdentifier4.f("1");
        X = aSN1ObjectIdentifierF10;
        aSN1ObjectIdentifierF10.f("1");
        aSN1ObjectIdentifierF10.f("2");
    }
}
