package org.bouncycastle.asn1.pkcs;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes6.dex */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier wA;
    public static final ASN1ObjectIdentifier wB;
    public static final ASN1ObjectIdentifier wC;
    public static final ASN1ObjectIdentifier wD;
    public static final ASN1ObjectIdentifier wE;
    public static final ASN1ObjectIdentifier wF;
    public static final ASN1ObjectIdentifier wG;
    public static final ASN1ObjectIdentifier wH;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        wA = aSN1ObjectIdentifier;
        wB = aSN1ObjectIdentifier.f("1");
        wC = aSN1ObjectIdentifier.f("2");
        aSN1ObjectIdentifier.f("3");
        wD = aSN1ObjectIdentifier.f("4");
        wE = aSN1ObjectIdentifier.f("5");
        aSN1ObjectIdentifier.f("6");
        aSN1ObjectIdentifier.f("7");
        wF = aSN1ObjectIdentifier.f("8");
        wG = aSN1ObjectIdentifier.f("9");
        wH = aSN1ObjectIdentifier.f("10");
        i = aSN1ObjectIdentifier.f("11");
        j = aSN1ObjectIdentifier.f("12");
        k = aSN1ObjectIdentifier.f("13");
        l = aSN1ObjectIdentifier.f("14");
        aSN1ObjectIdentifier.f("15");
        aSN1ObjectIdentifier.f("16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        m = aSN1ObjectIdentifier2;
        aSN1ObjectIdentifier2.f("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        n = aSN1ObjectIdentifier3;
        aSN1ObjectIdentifier3.f("1");
        aSN1ObjectIdentifier3.f("4");
        aSN1ObjectIdentifier3.f("3");
        aSN1ObjectIdentifier3.f("6");
        aSN1ObjectIdentifier3.f("10");
        aSN1ObjectIdentifier3.f("11");
        aSN1ObjectIdentifier3.f("12");
        aSN1ObjectIdentifier3.f("13");
        aSN1ObjectIdentifier3.f("14");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        o = aSN1ObjectIdentifier4;
        aSN1ObjectIdentifier4.f("7");
        aSN1ObjectIdentifier4.f("2");
        aSN1ObjectIdentifier4.f("4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        p = aSN1ObjectIdentifier5;
        q = aSN1ObjectIdentifier5.f("2");
        r = aSN1ObjectIdentifier5.f("4");
        s = aSN1ObjectIdentifier5.f("5");
        aSN1ObjectIdentifier5.f("7").i();
        aSN1ObjectIdentifier5.f("8").i();
        aSN1ObjectIdentifier5.f("9").i();
        aSN1ObjectIdentifier5.f("10").i();
        aSN1ObjectIdentifier5.f("11").i();
        aSN1ObjectIdentifier5.f("12").i();
        aSN1ObjectIdentifier5.f("13").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").i();
        t = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").i();
        u = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").i();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        v = aSN1ObjectIdentifier6;
        w = aSN1ObjectIdentifier6.f("1").i();
        x = aSN1ObjectIdentifier6.f("2").i();
        aSN1ObjectIdentifier6.f("3").i();
        aSN1ObjectIdentifier6.f("4").i();
        aSN1ObjectIdentifier6.f("5").i();
        aSN1ObjectIdentifier6.f("6").i();
        y = aSN1ObjectIdentifier6.f("7").i();
        z = aSN1ObjectIdentifier6.f("8").i();
        aSN1ObjectIdentifier6.f("9").i();
        aSN1ObjectIdentifier6.f("13").i();
        aSN1ObjectIdentifier6.f("14").i();
        aSN1ObjectIdentifier6.f("15").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifierI = aSN1ObjectIdentifier6.f("16").i();
        A = aSN1ObjectIdentifierI;
        aSN1ObjectIdentifier6.f("16.2.46").i();
        aSN1ObjectIdentifier6.f("20").i();
        aSN1ObjectIdentifier6.f("21").i();
        aSN1ObjectIdentifier6.f("22.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF = aSN1ObjectIdentifier6.f("22");
        B = aSN1ObjectIdentifierF;
        aSN1ObjectIdentifierF.f("1").i();
        aSN1ObjectIdentifierF.f("2").i();
        ASN1ObjectIdentifier aSN1ObjectIdentifierF2 = aSN1ObjectIdentifier6.f("23");
        C = aSN1ObjectIdentifierF2;
        aSN1ObjectIdentifierF2.f("1").i();
        aSN1ObjectIdentifier6.f("52").i();
        aSN1ObjectIdentifier6.f("15.1");
        aSN1ObjectIdentifier6.f("15.2");
        aSN1ObjectIdentifier6.f("15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        D = aSN1ObjectIdentifier7;
        aSN1ObjectIdentifier7.f("2");
        aSN1ObjectIdentifier7.f("4");
        aSN1ObjectIdentifier7.f("9");
        aSN1ObjectIdentifier7.f("23");
        aSN1ObjectIdentifier7.f("31");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF3 = aSN1ObjectIdentifierI.f("3");
        E = aSN1ObjectIdentifierF3;
        aSN1ObjectIdentifierF3.f("5");
        aSN1ObjectIdentifierF3.f("6");
        aSN1ObjectIdentifierF3.f("7");
        aSN1ObjectIdentifierF3.f("8");
        aSN1ObjectIdentifierF3.f("9");
        aSN1ObjectIdentifierF3.f("10");
        aSN1ObjectIdentifierF3.f("14");
        F = aSN1ObjectIdentifierF3.f("17");
        aSN1ObjectIdentifierF3.f("18");
        aSN1ObjectIdentifierF3.f("28");
        aSN1ObjectIdentifierF3.f("29");
        aSN1ObjectIdentifierF3.f("30");
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        G = aSN1ObjectIdentifier8;
        aSN1ObjectIdentifier8.f("1");
        aSN1ObjectIdentifier8.f("2");
        aSN1ObjectIdentifier8.f("3");
        aSN1ObjectIdentifier8.f("4");
        aSN1ObjectIdentifier8.f("5");
        aSN1ObjectIdentifier8.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        H = aSN1ObjectIdentifier9;
        aSN1ObjectIdentifier9.f("1");
        aSN1ObjectIdentifier9.f("4");
        aSN1ObjectIdentifier9.f("5");
        aSN1ObjectIdentifier9.f("10");
        aSN1ObjectIdentifier9.f("11");
        aSN1ObjectIdentifier9.f("12");
        aSN1ObjectIdentifier9.f("47");
        aSN1ObjectIdentifier9.f("7");
        aSN1ObjectIdentifier9.f("14");
        aSN1ObjectIdentifier9.f("15");
        aSN1ObjectIdentifier9.f("16");
        aSN1ObjectIdentifier9.f("17");
        aSN1ObjectIdentifier9.f("18");
        aSN1ObjectIdentifier9.f("19");
        aSN1ObjectIdentifier9.f("20");
        aSN1ObjectIdentifier9.f("21");
        aSN1ObjectIdentifier9.f("22");
        aSN1ObjectIdentifier9.f("23");
        aSN1ObjectIdentifier9.f("24");
        aSN1ObjectIdentifier9.f("25");
        aSN1ObjectIdentifier9.f("26");
        aSN1ObjectIdentifier9.f("27");
        aSN1ObjectIdentifier9.f("37");
        aSN1ObjectIdentifier9.f("38");
        aSN1ObjectIdentifier9.f("54");
        aSN1ObjectIdentifier9.f("43");
        aSN1ObjectIdentifier9.f("40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        I = aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierF4 = aSN1ObjectIdentifier10.f("10.1");
        J = aSN1ObjectIdentifierF4;
        aSN1ObjectIdentifierF4.f("1");
        aSN1ObjectIdentifierF4.f("2");
        aSN1ObjectIdentifierF4.f("3");
        aSN1ObjectIdentifierF4.f("4");
        aSN1ObjectIdentifierF4.f("5");
        aSN1ObjectIdentifierF4.f("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierF5 = aSN1ObjectIdentifier10.f("1");
        K = aSN1ObjectIdentifierF5;
        aSN1ObjectIdentifierF5.f("1");
        aSN1ObjectIdentifierF5.f("2");
        aSN1ObjectIdentifierF5.f("3");
        aSN1ObjectIdentifierF5.f("4");
        aSN1ObjectIdentifierF5.f("5");
        aSN1ObjectIdentifierF5.f("6");
        aSN1ObjectIdentifierF5.f("6");
    }
}
